package com.example.arzu.finalproject;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.GridView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

public class yemek_ara extends AppCompatActivity implements TextWatcher {
    List tüm_yemekler;
    TextView txt_null;
    TextView txt_msg;
    AutoCompleteTextView txt_autocomplte1;
    AutoCompleteTextView txt_autocomplte2;
    AutoCompleteTextView txt_autocomplte3;
    GridView grid;
    Button ara;
    ArrayList bulunan;
    String[] web;
    int[] imageId;

    String[] malzemeler={"domates","patlıcan","pirinç","salatalık","kıyma","tavuk","mantar",
            "biber","yufka","peynir","kuzu eti","patates","pırasa","bulgur","nohut","yoğurt","soğan","şeker","un",
            "yumurta","margarin","tereyağı","havuç","bezelye","kabak","fasulye","mısır unu","palamut","maydanoz","sarımsak",
            "irmik", "milföy","kadayıf","kaymak","tahin","tulum","börülce","incir","süt","nişasta",
            "yaprak","et","maya","ekmek","bayat ekmek","üzüm","kişniş","barbunya","karalahana",
            "kuru fasulye","kereviz","pekmez","şehriye","bamya","madımak","lahana","pancar","buğday",
            "ciğer","koyun eti","masala","kakule","portakal","mercimek","karides","midye","kalamar",
            "makarna","sucuk","salam","zeytin","hindi eti","lazanya","soya sosu","somon","levrek","ton balığı","avokado",
             "ıspanak"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_yemek_ara);

        tüm_yemekler = new ArrayList<>();
        tüm_yemekler.add(new Yemek("Kemalpaşa Tatlısı", "60 dk", "6 kişilik", R.drawable.kemalpasa, "Şerbeti hazırlamak için su ve şekeri tencereye alıp kaynatın. Limon suyunu ekleyip 1-2 taşım daha kaynatın. Ocaktan alıp soğumaya bırakın. Tuzsuz taze beyaz peyniri rendeleyin. 2 kaşık unu daha sonra kullanmak üzere ayırın, " + "kalan unu elekten geçirerek geniş bir tepsiye alın. Ortasını havuç şeklinde açıp yumurta ve karbonat ekleyin." + " Oda ısısında yumuşatılmış 4 yemek kaşığı margarin ve peyniri ekleyip 3-4 dakika yoğurun." + " Hamuru 18 parçaya bölüp ayırdığınız una hafifçe bulayarak elinizde yuvarlayın." + " Hamur toplarını yağlanmış fırın tepsisine aralıklı olarak dizin. Önceden ısıtılmış" + " 180 dereceye ayarlı fırında pembeleşinceye kadar 20-25 dakika pişirin." + " Pişen hamurları ılık şerbete atıp yumuşayıncaya kadar yaklaşık 15 dakika kaynatın." + " Kevgirle alıp servis tabağına dizin." + " Soğuyunca rendelenmiş Hindistan cevizi ile süsleyip servis yapın.", "2 su bardağı toz şeker\n" + "2 su bardağı su\n" + "2 tatlı kaşığı limon suyu\n" + "2 su bardağı un\n" + "Yarım tatlı kaşığı karbonat\n" + "2 yumurta\n" + "5 yemek kaşığı margarin\n" + "250 gr tuzsuz taze beyaz peynir"));
        tüm_yemekler.add(new Yemek("Sebzeli Pilav", "45 dk", "6 kişilik", R.drawable.sebzelipilav, "Pirinci yıkayıp üzerini örtecek kadar suda 1 saat bekletin." + " Suyu süzüp pirinçleri birkaç kez yıkayın. 3 yemek kaşığı tereyağını tencerede eritip pirinci ekleyin ve kavurun. " + "Et suyunu ekleyin. Tuzla tatlandırın. Su kaynamaya" + " başladığında ateşi kısıp pirinçler yumuşayana kadar pişirin. Havuç, biber ve kabağı tavla zarı büyüklügünde doğrayın. Havucu kaynar suda 15 dakika," + " biberi 8 dakika, kabağı 5 dakika haşlayıp suyunu süzün. Sebzeleri kalan" + " tereyağıyla kavurun." + " Pilava ekleyip ezmeden harmanlayın. Sıcak servis yapın.", "2.5 su bardağı baldo pirinç\n" + "3.5 su bardağı et suyu\n" + "4 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı tuz\n" + "1 küçük havuç\n" + "1 su bardağı haşlanmış bezelye\n" + "1 kabak\n" + "1 dolmalık yeşil biber"));
        tüm_yemekler.add(new Yemek("Şaşa Şura", "60 dk", "4 kişilik", R.drawable.sasasura, "Soğanı soyup iri kıyın. Biberleri kalın halkalar şeklinde doğrayın. Domatesleri soyup küp şeklinde doğrayın. Fasulyeleri temizleyip ikiye bölün. Patates, kabak ve patlıcanları soyup küp şeklinde doğrayın. Sebzeleri bir kaba alıp karıştırın.\n" + " \n" + "Ayçiçeği yağını tencerede ısıtıp soğanı pembeleşinceye kadar kavurun. Biber ve domates ve bir çorba kaşığı ılık suda inceltilmiş salçayı ekleyip 12 dakika daha kavurun. Sebzeler, 1.5 su bardağı sıcak su, tuz ve karabiberi ilave edin. Bir taşım kaynatıp kısık ateşte 30 dakika kadar pişirin. Ilık veya soğuk servis yapın.", "500 gr taze fasulye\n" + "2 kabak\n" + "1 büyük kemer patlıcan\n" + "1 büyük patates\n" + "50 gr çarliston biber\n" + "1 soğan\n" + "1 kahve fincanı ayçiçeği yağı\n" + "1.5 su bardağı sıcak su\n" + "2 domates\n" + "2 çorba kaşığı domates salçası\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Kaçamak", "20 dk", "6 kişilik", R.drawable.kacamak, "Suyu bir tencereye alıp kaynatın. Tuzunu ekleyip karıştırın. Mısır ununu azar azar eklerken tahta kaşıkla sürekli karıştırın. Kek hamuru kıvamına gelince tahta kaşığı 2-3 yerine batırıp 1 dakika daha pişirerek suyunu çektirin. Katılaşınca ocaktan alıp tepsiye boşaltın.\n" + "\n" + "Tereyağını bir tavada kızdırıp üzerine gezdirin. Tahta kaşıkla yedirerek iyice karıştırın. Kaşığın sırtı ile üzerini düzeltin. Lor peyniri serpiştirip sıcak olarak servis yapın.", "8 su bardağı su\n" + "Aldığı kadar mısır unu\n" + "20 gr tereyağı\n" + "Tuz\n" + "Üzeri için: Lor peyniri"));
        tüm_yemekler.add(new Yemek("Palamut Köftesi", "35 dk", "4 kişilik", R.drawable.palamutkofte, "Palamutu temizleyin. İyice yıkayıp süzgece alın. Soğanları soyun. 1 bütün soğan ve balığı tuzlu suda 20 dakika haşlayın. Balığı süzgece alıp soğutun. Derisini, siyah kısımlarını ve kılçıklarını ayıklayın. Beyaz etleri bir kaba alıp didikleyin.\n" + "\n" + "Kalan 2 soğanı rendeleyip suyunu sıkın. Patatesleri haşlayıp soyun ve rendeleyin. Maydanozu temizleyip kıyın. \n" + "\n" + "Soğan, patates, maydanoz, fıstık, kuşüzümü, 2 yumurta, 1 kaşık un, tuz, yenibahar ve karabiberi balığa ekleyip yoğurun. Elinizle uzun köfteler hazırlayın. Galeta ununa bulayıp sıvıyağda kızartın. Sıcak servis yapın.", "1 palamut\n" + "3 soğan\n" + "2 orta boy patates\n" + "Yarım demet maydanoz\n" + "1 kahve fincanı dolmalık fıstık\n" + "1 kahve fincanı kuşüzümü\n" + "2 yumurta1 çorba kaşığı yenibahar\n" + "1 çorba kaşığı un\n" + "Kızartma için sıvıyağ\n" + "Galeta unu\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("İnegöl Köftesi", "30 dk", "6 kişilik", R.drawable.inegol, "Kıymayı iyice yoğurup buzlukta 4 gün bekletin. Buzluktan çıkarıp buzu çözülünceye kadar oda ısısında bekletin. Bir kez daha kıyma makinesinden geçirip yoğurun. \n" + "Soğanı çok ince doğrayıp kıymaya ekleyin. Tuz ilave edip yoğurun. Küçük parçalar koparıp elinizde parmak şekli verin. Izgarada veya mangalda pişirip sıcak olarak servis yapın. ", "Kıyma\n" + "Soğan\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Hoşmerim", "35 dk", "6 kişilik", R.drawable.hosmerim, "Peynire yumurta sarılarını ekleyip tahta kaşıkla karıştırın. Karışımı bir tencereye alıp tereyağını ilave edin. Azar azar un ekleyip tahta kaşıkla karıştırarak pişirin. Koyu kıvama geldiğinde şekeri ekleyip karıştırarak 10 dakika daha pişirin. \n" + "\n" + "Höşmerimi servis tabağına alın. İri çekilmiş ceviz içi ya da hindistancevizi ile süsleyip servis yapın.", "500 gr tuzsuz taze peynir (yağlı) veya lor peyniri\n" + "2 yumurta sarısı\n" + "1 su bardağı un\n" + "15 gr tereyağı\n" + "750 gr tozşeker\n" + "Üzeri için: İri çekilmiş ceviz içi veya hindistan cevizi"));
        tüm_yemekler.add(new Yemek("Kaysepi", "45 dk", "6 kişilik", R.drawable.kaysepi, "Kurutulmuş mürdüm eriğini yıkayıp tencereye alın. Bir miktar su ekleyip yumuşayana kadar pişirin. Suyunu süzün ve eriklerin çekirdeklerini çıkarın. Tencereye alıp 1 bardak kaynar su ekleyin. Üzerine şekeri ilave edip pişirin. \n" + "\n" + "Bir tavada tereyağını eritin. Erikleri servis tabağına alıp üzerine tereyağını gezdirin. Ceviz içi serpiştirip sıcak olarak servis yapın. ", "2 su bardağı kurutulmuş mürdüm eriği\n" + "1 su bardağı su\n" + "1.5 su bardağı tozşeker\n" + "30 gr tereyağı\n" + "1 çay bardağı çekilmiş ceviz içi"));
        tüm_yemekler.add(new Yemek("Kabaklı Saroz Böreği", "60 dk", "6 kişilik", R.drawable.kabakli, "Böreğin iç harcı için, kabakların kabuğunu temizleyip rendenin iri yanıyla rendeleyin. Süzgece alıp suyunu süzün. Yumurta, lor peyniri, tuz, karabiber ve pul biber ekleyip karıştırın. Yufkalaradan ilkini geniş düz bir zemine yayın. Su ve ayçiçeği yağını bir kasede iyice çırpın. Yufkanın üzerine fırçayla sürün. İç harçtan paylaştırıp rulo şeklinde sarın. Bir kenarı sabitleyip diğer kenarı çevresinde sararak şekil verin. Tüm malzemeyi aynı şekilde hazırlayın. Kapaklı bir kabın içine börekleri dizip buzdolabında bir gece bekletin. Fırın tepsisine dizip üzerine yağlı su sürün. Önceden ısıtılmış 180 derece fırında 35 dakika pişirin. Ilık servis yapın.", "3 hazır yufka\n" + "Sos için:\n" + "\n" + "1 kahve fincanı ayçiçeği yağı\n" + "1 kahve fincanı su\n" + "İç harcı için:\n" + "\n" + "2 orta boy kabak\n" + "1 yumurta\n" + "1 su bardağı lor peyniri\n" + "1 çay kaşığı tuz\n" + "Karabiber\n" + "Kırmızı pul biber"));
        tüm_yemekler.add(new Yemek("Köbete", "70 dk", "8 kişilik", R.drawable.kobete, "Unu hamur yoğurma kabına alıp ortasını havuz gibi açın. Tuz, yumurta ve mayayı ilave edip azar azar su ekleyerek kulak memesi yumuşaklığında bir hamur yoğurun. Hamuru ılık ortamda 15 dakika dinlendirin. \n" + "\n" + "Tavuk göğüs etini tencereye alıp 3 bardak su ile haşlayın ve tel tel ayırın. Tavuk suyunu daha sonra kullanmak üzere muhafaza edin. \n" + "\n" + "Soğanları piyazlık doğrayıp sıvıyağda pembeleştirin. Sivri biberleri ve domatesleri doğrayıp soğana ekleyin, 5 dakika pişirin. Tavuk göğüs etini, tuz ve karabiberi ilave edip ateşten alın. \n" + "\n" + "Hamuru iki eşit parçaya ayırıp merdaneyle tepsi büyüklüğünde açın. Bir parçasını tepsiye yerleştirip iç malzemeyi üzerine yayın. Diğer hamuru üzerine kapatın. Yumurta sarısı ile sıvıyağı karıştırıp hamurun üzerine sürün. Önceden ısıtılmış 180 dereceye ayarlı fırında üzeri pembeleşinceye kadar pişirin. Fırından alıp börek sıcakken üzerine tavuk suyunu gezdirerek dökün. Suyunu çekince dilimleyip sıcak olarak servis yapın.", "Hamur malzemesi:\n" + "4 su bardağı un\n" + "1 yumurta\n" + "1 su bardağı su\n" + "1 çay kaşığı toz maya\n" + "Tuz\n " + "İç malzemesi: 1 tavuk göğüs eti\n" + "3 su bardağı su\n " + "3 soğan\n " + "3 sivri biber\n " + "1 domates\n " + "Yarım çay bardağı sıvıyağ\n" + "Tuz\n" + "Karabiber\n" + "Üzeri için: 1 yumurta sarısı\n" + "1 çorba kaşığı sıvıyağ"));


        tüm_yemekler.add(new Yemek("Sini KÖfte", "70 dk", "4 kişilik", R.drawable.sini, "Köftenin dış harcı için çiğ köftelik kıyma, ince bulgur, un, rendelenmiş soğan, kırmızı toz biber, tuz, karabiber ve yeteri kadar suyu bir kasede karıştırın. Köftenin iç harcı için, soğanların kabuğunu soyup kıyın. Kıymayı Bizim Yağ Margarinle hafifçe kavurun. Soğanı ekleyip kavurmaya devam edin. Karabiber ve yenibahar ile tatlandırın. Kıymayı ocaktan alıp iri kırılmış ceviz ve Antep fıstığını ekleyin. Harcı ılınmaya bırakın. Köftenin dış harcının yarısını Bizim Yağ Margarin ile yağlanmış 30-35 santim çapında bir tepsiye elinizle bastırarak yayın. Üzerine iç harcı ekleyip kaşığın tersiyle üzerini düzeltin. Kalan bulgurlu harcı üzerine ekleyip çok düzgün olacak şekilde kaşığın tersiyle düzleyin. Keskin bir bıçağı soğuk suya batırarak tepsideki köfteyi kare şeklinde kesin. Bizim Yağ Margarini hafifçe eritip köftenin üzerine sürün. Önceden ısıtılmış 200 derece fırında 30-35 dakika pişirin. Köftenin yumuşak olması için fırından çıkardıktan sonra üzerine biraz su serpip tepsinin üstünü kapatın. Frenk soğanıyla süsleyerek sıcak servis yapın.", "350 çiğ köftelik kıyma\n" + "4 subardağı köftelik ince bulgur\n" + "2 yemek kaşığı un\n" + "1 rendelenmiş soğan\n" + "2 yemek kaşığı kırmızı toz biber\n" + "1 tatlı kaşığı tuz\n" + "1 tatlı kaşığı karabiber\n\n" + "Yoğurmak için\n" + "Yeterikadar su\n\n" + "İç harcı için\n" + "30g BizimYağ Margarin\n" + "500 yağlı kıyma\n" + "3 soğan\n" + "1 su bardağı ceviz içi\n" + "Yarımsu bardağı Antep fıstığı içi\n" + "Tuz\n" + "1’er çay kaşığı karabiber ve yenibahar\n\n" + "Üzeri için\n" + "\n" + "30g BizimYağ Margarin\n" + "Frenk soğanı"));
        tüm_yemekler.add(new Yemek("Söğürme", "50 dk", "6 kişilik", R.drawable.sogurme, "Patlıcanları yıkayıp kurulayın. Közleyip kabuğunu soyun. İçini parmak kalınlığında doğrayın. Soğanı küp şeklinde doğrayıp zeytinyağında hafifçe kavurun. Küp doğranmış domatesi ekleyip kavurmaya devam edin. Çekirdekleri çıkarılmış ve ince uzun parçalar şeklinde doğranmış kırmızıbiberi ekleyip Birkaç dakika kavurduktan sonra patlıcan, tuz ve şekeri ilave edin. Sarımsakları kıyıp ekleyin. 1 çay bardağı suyu ilave edip pişirin. Suyu tamamen azalınca üzerine kıyılmış maydanoz serpip servis yapın.", "2 bostan patlıcanı\n" + "2 domates\n" + "1 soğan\n" + "1 salçalık kırmızıbiber\n" + "2 sivri biber\n" + "Yarım çay bardağı zeytinyağı\n" + "2 kesme şeker\n" + "2 diş sarımsak\n" + "Tuz\n" + "Kırmızı pul biber\n" + "Kıyılmış maydanoz"));
        tüm_yemekler.add(new Yemek("Adana Avgan Pilavı", "40 dk", "6 kişilik", R.drawable.adana, "Küçük parçalar şeklinde doğranmış eti ve kıyılmış soğanı tencereye alıp bıraktığı suyu çekene kadar kavurun. Kıyılmış havuç ve bol suyla yıkanmış pirinci ekleyip birkaç dakika daha kavurun. Tuzla tatlandırın. Yenibahar ekleyip pirincin üzerini geçecek kadar kaynar su ekleyip bir kez karıştırın. Tencerenin kapağını kapatıp ateşi kısın. Kısık ateşte pilav suyu çekene kadar pişirin. 10 dakika demlendirip servis yapın.", "1 kg parça et\n" + "2 soğan\n" + "250 ml ayçiçeği yağı\n" + "500 gr baldo pirinç\n" + "Sıcak su\n" + "1 kg havuç\n" + "1 tatlı kaşığı yenibahar\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Peynirli İrmik Helvası", "45 dk", "6 kişilik", R.drawable.peynirliirmik, "Su ve şekeri tencereye alıp kaynatın. 1 tatlı kaşığı tereyağını tavaya alıp eritin. İrmiği ekleyip rengi hafifçe değişene kadar kavurun. Şekerli suyu ekleyip kısık ateşte su azalana ve irmik yumuşayana kadar pişirin. İnce parçalar şeklinde doğranmış peyniri ekleyin. 2-3 dakika daha pişirin tencereyi ocaktan alın. Kalan tereyağını ekleyip yavaşça karıştırın. Üzerine kavrulmuş çam fıstığı ekleyip servis yapın.", "1 su bardağı irmik\n" + "3 su bardağı su\n" + "2 su bardağı toz şeker\n" + "300 gr tuzsuz beyaz peynir\n" + "2 yemek kaşığı tereyağı\n" + "Kavrulmuş çam fıstığı"));
        tüm_yemekler.add(new Yemek("Testi Kebabı", "60 dk", "6 kişilik", R.drawable.testi, "İri parçalar şeklinde kesilmiş eti yıkayıp süzün. Eti büyük bir kabın içine alın. Arpacık soğanların kabuğunu soyup ete ekleyin. Domatesleri, biberleri iri parçalar şekline doğrayıp malzemeye ekleyin. Salça, tuz, kimyon, karabiber ve ayçiçeği yağını ilave edip karıştırın. Hazırladığınız harcı toprak testiye doldurun. Testinin ağız kısmını hazırladığınız bir hamurla sıkıca kapatın. Sıcak fırında 1.5 saat pişirin. Fırından alıp 20 dakika dinlendirin. Hamuru çıkarıp kebabı servis tabaklarına paylaştırın. Sıcak servis yapın.", "1.5 kg orta yağlı koyun eti\n" + "2 yemek kaşığı ayçiçeği yağı\n" + "1 kg arpacık soğan\n" + "Yarım yemek kaşığı domates salçası\n" + "2 büyük domates\n" + "Sivri biber\n" + "Defne yaprağı\n" + "Tuz\n" + "Kimyon\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Kabune", "50 dk", "8 kişilik", R.drawable.kabune, "Soğanı temizleyip halka halka doğrayın. Tuz ve biberle ovup yıkayın. Pirinci ılık suda 10-15 dakika bekletin ve yıkayıp süzün. Eti haşlayıp tel tel ayırın.\n" + "\n" + "Bir tencereye sırasıyla soğan, et ve pirinci yerleştirin. Tuz ve karabiber serpin. Üzerine bir porselen tabak kapatın. Tabağın hizasına kadar kaynar et suyu ilave edin. Kapağı kapalı olarak 25 dakika pişirin. 5-10 dakika dinlendirin. Servis tabağına ters çevirip sıcak olarak servis yapın.", "1 kg pirinç\n" + "500 gr kemiksiz et\n" + "3 soğan\n" + "2 çorba kaşığı margarin\n" + "Kaynar et suyu\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Samsa Tatlısı", "65 dk", "6 kişilik", R.drawable.samsa, "Bir kapta badem, şeker ve yumurta akını karıştırın. Milföy hamurunu 2 mm kalınlığında açıp hazırladığınız bademli karışımı ortasına uzunlamasına yayın. Hamuru rulo şeklinde sarıp bir tepsiye alın ve 45 dakika dinlendirin. Küçük parçalar halinde kesip önceden ısıtılmış 180 dereceye ayarlı fırında 40 dakika pişirin.\n" + "\n" + "Bir tencerede şeker, su ve limonu kaynatıp şerbet hazırlayın. Fırından aldığınız sıcak hamurun üzerine sıcak şerbeti gezdirerek dökün. Tatlı şurubu çekince ılık ya da soğuk olarak servis yapın.", "200 gr milföy hamuru\n" + "Yarım su bardağı toz badem\n" + "2 çorba kaşığı tozşeker\n" + "1 yumurta akı\n" + "Şerbet için:\n" + "3.5 kahve fincanı tozşeker\n" + "2 çay bardağı su\n" + "Yarım limon"));
        tüm_yemekler.add(new Yemek("Kaymaklı Künefe", "50 dk", "8 kişilik", R.drawable.knefe, "Şurup için; şeker ve suyu bir tencerede kaynatın. Limon suyunu ilave edip bir taşım daha kaynatın. Tencereyi ocaktan alıp ılınmaya bırakın.\n" + "\n" + "Küçük bir tavada tereyağını eritip ılıtın. Kadayıfı tepsiye yayıp yağı üzerine gezdirin. Kadayıfı elinizle tel tel ayırarak ve ovuşturarak tereyağını iyice yedirin. Kadayıfı 2 ayrı tepsiye paylaştırıp elinizle bastırarak yerleştirin. Tepsileri ocağa alın ve kısık ateş üzerinde sürekli çevirerek kadayıfın altını kızartın. Her ikisini de ocaktan alıp birinin üzerine kaymağı yayın. Diğer kadayıfı kızarmış tarafı üste gelecek şekilde kaymağın üzerine alın. \n" + "\n" + "Ilık şerbeti sıcak kadayıfın üzerine gezdirerek dökün. Antepfıstığı serpin. Dilimleyip servis yapın.", "1 kg kadayıf\n" + "800 gr kaymak\n" + "300 gr tereyağı\n" + "100 gr ince çekilmiş antepfıstığı\n" + "Şurup için:\n" + "1 kg tozşeker\n" + "3 su bardağı su\n" + "1 çorba kaşığı limon suyu"));
        tüm_yemekler.add(new Yemek("Pirzolalı Yaprak Sarma", "85 dk", "6 kişilik", R.drawable.pirzola, "Bir tencereye su doldurup tuz ve yarım limonun suyunu ekleyin. Ocağa alıp su kaynamaya başlayınca yaprakları ilave edip 5 dakika haşlayın ve süzgece alın. \n" + "\n" + "Soğan ve sarımsağı temizleyin. 2 diş sarımsak ve soğanı rendeleyin. Pirinci iyice yıkayıp süzün. Bir kapta pirinç, kıyma, salça, yağ, soğan, sarımsak, tuz ve karabiberi karıştırın. Hazırladığınız malzemeyi yapraklara sarın. \n" + "\n" + "Pirzolaları tuzlayıp biberleyin ve yayvan bir tencerenin tabanına dizin. Yaprak sarmaları pirzolaların üzerine yerleştirin. Kalan sarımsakları bütün olarak ilave edin. 1.5 bardak sıcak su ekleyip üzerine porselen bir tabak kapatın. 30 dakika pişirip üzerindeki tabağı alın. 1 limonun suyunu yemeğin üzerine gezdirin ve kısık ateşte 15 dakika daha pişirin. Sıcak olarak servis yapın.", "750 gr taze asma yaprağı\n" + "500 gr pirzola\n" + "400 gr az yağlı koyun kıyması\n" + "2.5 su bardağı pirinç\n" + "3 çorba kaşığı sıvıyağ\n" + "1 soğan\n" + "4-5 diş sarımsak\n" + "1 çorba kaşığı salça\n" + "1.5 çay bardağı su\n" + "1.5 limon\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Uluborlu Böreği", "40 dk", "8 kişilik", R.drawable.uluborlu, "Eti soğanla birlikte robotta çekin ya da satırla kıyın. Tuz, karabiber ve çok az su ilave edip yoğurun. \n" + "\n" + "Yufkayı dörde kesin. Her bir üçgenin ortasına bir miktar et yerleştirip bohça şeklinde kapatın. Malzeme bitinceye kadar işleme devam edin. \n" + "\n" + "Sacı ısıtın. Börekleri önlü arkalı pişirip tereyağı ile yağlayın. Kıyılmış maydanoz serpip servis yapın.", "500 gr kemiksiz et\n" + "2 soğan\n" + "4 yufka\n" + "2 çorba kaşığı tereyağı\n" + "2-3 dal maydanoz\n" + "Tuz\n" + "Karabiber"));


        tüm_yemekler.add(new Yemek("İzmir Köfte", "60 dk", "6 kişilik", R.drawable.izmirkofte, "Kıymayı yoğuracağınız kaba alın. Soğanı rendenin ince tarafı ile rendeleyin. Ekmekleri ıslatarak içini ufalayın. Kıyılmış maydanoz, tuz ve karabiberi ilave edip iyice yoğurun. Kıymalı harcı 18 parçaya ayırarak parmak şeklinde köfteler hazırlayın. Patatesleri soyup yıkayın ve elma dilimi şeklinde dilimleyin. Ayçiçeği yağında 2 yemek kaşığı kadar ayırın ve kalanını tavada kızdırın. Önce patatesleri, sonra köfteleri, en son olarak da sivri biberleri hafif pembeleşene kadar kızartın. 2 domatesi yıkayın. Kabuğunu soyup küp halinde doğrayın. Doğradığınız domateslerin bir kısmını fırın kabına yayın. Üzerine kızartmış olduğunuz köfte ve patatesleri arzu ettiğiniz biçimde sıralayın. Kalan domatesi de dilimleyip malzemenin üzerine ekleyin. Salçayı da 1 çay bardağı su ile ezip yemeğin üzerine gezdirin. Tavada hafif kızarttığınız sivri biberleri de malzemenin üzerine yerleştirin. Tuz ve tane karabiberi ilave edin. Tereyağını minik parçalar halinde malzemenin üzerine serpiştirin. Kalan ayçiçeği yağından 2 yemek kaşığı yemeğin üzerine gezdirin. 200 derece fırında yaklaşık 25 dakika kadar pişirin. Sıcak servis yapın.", "Malzemeler\n" + "\n" + "4 orta boy patates\n" + "6 sivri biber\n" + "3 orta boy domates\n" + "1 tatlı kaşığı domates salçası\n" + "Yarım çay kaşığı tane karabiber\n" + "1 tatlı kaşığı kaşığı tereyağı\n" + "1 su bardağı ayçiçek yağı (kızartmak için)\n" + "1 çay kaşığı tuz\n\n" + "Köfte için\n" + "\n" + "500 gr dana kıyma (az yağlı)\n" + "1 soğan\n" + "3 dilim bayat ekmek içi\n" + "1 çay kaşığı tuz\n" + "1 çay kaşığı karabiber\n" + "1 tutam maydanoz"));
        tüm_yemekler.add(new Yemek("Tahinli Kabak Tatlısı", "50 dk", "6 kişilik", R.drawable.kabak, "Kabakların kabuğunu soyup ince uzun parçalar şeklinde dilimleyin. Dikdörtgen fırın kabına kabakları yerleştirin. Üzerine şekeri serpin. Üzerini streç filmle kapatıp buzdolabında bir gece bekletin. Ertesi gün üzerini yağlı kağıt ile örterek 160 dereceye ayarlı fırında yaklaşık 25-30 dakika pişirin. Soğuyunca üzerine tahin gezdirin. Ceviz ile süsleyip servis edin.", "1.5 kg kabuğu soyulmuş bal kabağı\n" + "3 su bardağı toz şeker\n" + "1.5 çay bardağı tahin\n" + "1.5 çay bardağı iri çekilmiş ceviz içi"));
        tüm_yemekler.add(new Yemek("Çingene Pilavı", "20 dk", "6 kişilik", R.drawable.cingene, "Tulum çökeleğini bir kabın içine alıp ufalayın. Domates, biber ve soğanı küçük doğrayıp çökeleğe ekleyin. Maydanozu kıyıp ekleyin. Zeytinyağı ve çok az tuz ekleyip karıştırın. Servis yapın.", "1 kg tulum çökeleği\n" + "2 soğan\n" + "3 domates\n" + "4 sivri biber\n" + "Yarım demet maydanoz\n" + "3 yemek kaşığı zeytinyağı\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Tekke Çorbası", "50 dk", "4 kişilik", R.drawable.tekke, "Unu hamur yoğurma kabına alıp tuzla harmanlayın. Ortasını havuz gibi açıp yumurtayı ekleyin. Suyu azar azar ilave edip kulak memesi yumuşaklığında pürüzsüz bir hamur elde edin. Unlanmış zeminde hamuru merdane ile açın. 1?er santimlik kareler halinde kesin.\n" + "\n" + "Soğanı temizleyip rendeleyin. Margarini tencerede kızdırıp soğanı ve kıymayı kavurun. Domates ve biber salçaları ekleyip karıştırın. Sıcak suyu ekleyin. Su kaynamaya başlayınca hamurları ilave edin. Tuz, karabiber ve kuru nane ile tatlandırın.\n" + "\n" + " Servis kâselerine paylaştırıp üzerini nane ile süsleyin. Sıcak olarak servis yapın.", "100 gr kıyma\n" + "1 çorba kaşığı margarin\n" + "1 tatlı kaşığı domates salçası\n" + "1 çay kaşığı biber salçası\n" + "1 soğan\n" + "1 çay kaşığı kuru nane\n" + "5 su bardağı sıcak su\n" + "Tuz\n" + "Karabiber\n" + "Hamur için:\n" + "1 su bardağı un\n" + "1 yumurta\n" + "3 çay bardağı su\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Boyoz", "50 dk", "4 kişilik", R.drawable.boyoz, "Kabaklı iç malzeme için; patlıcanı soyup tuzlu suda bekletin. Domates, kabak ve soğanın kabuklarını soyun. Patlıcanın suyunu sıkıp kâğıt havlu ile kurulayın. Sebzeleri rendeleyin. Tavada sıvıyağı kızdırıp tuz ekleyerek sebzeleri suyunu salıp çekinceye kadar soteleyin. Patatesli iç malzeme için; patatesleri haşlayın. Kabuklarını soyup çatalla ezin. Yumurta, tulum ve kaşarpeynirini ekleyip karıştırın.\n" + "\n" + "Unu yoğurma kabına alın. Ortasını havuz gibi açıp su, sirke, limon suyu, 1 tatlı kaşığı mısırözü yağı ve tuzu ekleyin ve 10-15 dakika kuvvetlice yoğurun. Derin bir kaba 1 bardak mısırözü yağı ekleyin. Yumuşak kıvamlı hamurdan ceviz büyüklüğünde parçalar koparıp 10 dakika bekletin. \n" + "\n" + "Hamur topağını yağdan alıp elle, katmer hamuru inceliğinde yuvarlak açın. Ortasına kabaklı iç malzemeden 1 kaşık yayıp 4 köşesi ortaya gelmek üzere katlayın. Hamurların yarısını kabaklı, yarısını da patatesli iç malzemeyle hazırlayıp hafif yağlanmış tepsiye dizin. Önceden ısıtılmış 200 dereceye ayarlı fırında 20 dakika pişirin. Sıcak olarak servis yapın.", "2 su bardağı un\n" + "1 su bardağı su\n" + "1 tatlı kaşığı sirke\n" + "1 tatlı kaşığı limon suyu\n" + "1 tatlı kaşığı mısırözü yağı\n" + "Yarım tatlı kaşığı tuz\n" + "Kabaklı iç malzeme:\n" + "2 kabak\n" + "1 patlıcan\n" + "1 soğan\n" + "1 domates\n" + "2 çorba kaşığı sıvıyağ\n" + "Tuz\n" + "Patatesli iç malzeme:\n" + "2 patates\n" + "2 yumurta\n" + "1.5 kahve fincanı tulum peyniri\n" + "1 kahve fincanı rendelenmiş kaşar peyniri"));
        tüm_yemekler.add(new Yemek("Kuru Börülce Çorbası", "40 dk", "6 kişilik", R.drawable.brlce, "Kuru börülceyi haşlayıp suyunu süzün. Tencereye alıp 5 su bardağı su ekleyin ve yumuşayıncaya kadar pişirin. Pirinci yıkayıp süzün ve börülceye ilave edin. \n" + "\n" + "Tavada tereyağını kızdırıp salçayı ekleyin. Tuz serpip kaşıkla ezerek kavurun. Pirinçler pişince tencereye salçalı sosu ekleyip 1-2 dakika daha kaynatın. Sıcak olarak servis yapın.", "1 su bardağı kuru börülce\n" + "5 su bardağı su\n" + "1 kahve fincanı pirinç\n" + "1 çorba kaşığı tereyağı\n" + "1 çorba kaşığı salça\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Çaput Aşı", "75 dk", "4 kişilik", R.drawable.caput, "Pirinci 15 dakika soğuk suda bekletip nişastası gidene kadar soğuk suyla yıkayın ve suyunu süzün. Tereyağını tencerede eritip pirinci kavurun. Başka bir tencerede kuzu etini tuz, kimyon ve karabiber ile tatlandırarak kavurun. Koruk suyu (yeşil üzüm suyu), ince doğranmış asma yaprağı ve ets uyunu ilave edip kaynatın. Pirinci ekleyip suyunu çekinceye kadar kısık ateşte pişirin. Sıcak servis yapın.", "3 su bardağı baldo pirinç\n" + "4 su bardağı sıcak et suyu\n" + "100 gr tereyağı\n" + "150 ml koruk suyu\n" + "300 gr kuzu eti\n" + "30 taze asma yaprağı\n" + "Tuz\n" + "Karabiber\n" + "Kimyon"));
        tüm_yemekler.add(new Yemek("Sütlü İncir Tatlısı", "40 dk", "4 kişilik", R.drawable.incir, "İncirleri yıkayıp iri iri doğrayın. 1 çay bardağı su ile incirler yumuşayana kadar pişirin. Süte nişastayı ilave edip sürekli karıştırarak muhallebi kıvamına gelene kadar pişirin.\n" + "\n" + "Tozşeker ve incirleri ekleyip karıştırarak 5 dakika daha pişirin. Servis kâselerine paylaştırıp soğumaya bırakın. Üzerini antepfıstığı ile süsleyip soğuk olarak servis yapın.", "1 kg süt\n" + "10 kuru incir\n" + "1 kahve fincanı nişasta\n" + "3 kahve fincanı tozşeker\n" + "4 çorba kaşığı çekilmiş antepfıstığı"));
        tüm_yemekler.add(new Yemek("Etli Ekmek Dolması", "55 dk", "6 kişilik", R.drawable.etliekmek, "Ekmeğin bir ucunu keserek kapak şeklinde açın. Kaşık yardımıyla içini çıkarıp bir kaba ufalayın. Taze soğanları temizleyip kıyın. Sarımsakları soyup ezin. Dereotu veya maydanozu temizleyip kıyın.\n" + "\n" + "Kuşbaşı eti tencereye alın. 1 fincan su ilave ederek suyunu çekinceye kadar pişirin. 1 fincan su daha ekleyip kapağı kapalı olarak pişirin. Gerekirse 1 fincandan fazla olmamak kaydıyla su ekleyip pişirmeye devam edin. Et suyunu çekince tencereyi ocaktan indirin.\n" + "\n" + "Geniş bir tavada zeytinyağını ısıtın. Taze soğanları ekleyip hafif sarartın. Ekmek içi, sarımsak, salça, tuz ve baharatları ekleyip 2-3 dakika kavurun. Kuşbaşı et, dereotu veya maydanozu ilave edip karıştırın ve tavayı ocaktan alın.\n" + "\n" + "İç malzemeyi bir kaşıkla hiç boşluk bırakmayacak şekilde ekmeğin içine doldurun. Çıkardığınız kapağı ağzına kapatın. Büyük bir tencereye ısıya dayanıklı bir kâseyi ters yerleştirin. Ekmeği kâsenin üzerine oturtun. Kâsenin seviyesini geçmeyecek kadar su ekleyin. Kapağı kapalı olarak orta ateşte 15-20 dakika pişirin. Ekmeği tencereden alıp dilimleyerek servis yapın.", "1 bayat çavdar ekmeği\n" + "500 gr kuşbaşı kuzu eti\n" + "2 kahve fincanı sıcak su\n" + "6 taze soğan\n" + "1 kahve fincanı zeytinyağı\n" + "2 diş sarımsak\n" + "1 tatlı kaşığı domates salçası\n" + "1 demet maydanoz veya dereotu\n" + "Tuz\n" + "Karabiber\n" + "Kırmızı pulbiber"));
        tüm_yemekler.add(new Yemek("Kırlı Patlıcan Kızartması", "40 dk", "8 kişilik", R.drawable.kirlipatlican, "Patlıcanları saplı olarak alaca soyup bol tuzlu suda yarım saat bekletin. Bol suyla yıkayıp kurulayın. Sapı üzerinde kalacak ve kopmayacak şekilde uzunlamasına kesin. Kızgın ayçiçeği yağında kızartın. Soğanların ve sarımsakların kabuğunu soyup soğanları küçük doğrayın. Sarımsakları bütün olarak bırakın. Domateslerin kabuğunu soyup küp şeklinde doğrayın. Soğan ve domatesi çok az yağ eklenmiş tavada kavurun. Kızarttığınız patlıcanların üzerine yayın. Üzerlerine parmak uzunluğunda doğradığınız biberler, sarımsaklar ve tuz ilave edin. 180 derece fırında yarım saat pişirin. Ilık servis yapın.", "1.5 kg patlıcan\n" + "1 litre ayçiçeği yağı\n" + "1.5 kg domates\n" + "500 gr soğan\n" + "2 baş sarımsak\n" + "1 kg sivri biber\n" + "Tuz"));


        tüm_yemekler.add(new Yemek("Katmer", "30 dk", "2 kişilik", R.drawable.katmer, "Su ve tuzu geniş bir kaba alarak tuz tamamen eriyinceye kadar elinizle karıştırın. Unu azar azar ekleyerek kulak memesi kıvamında bir hamur elde edinceye kadar yoğurun. Hamuru sekiz eşit bezeye ayırıp üzerini nemli bir bezle örtün ve bir gün dinlendirin. Ertesi gün, dinlenen bezeleri üzerlerine nişasta serperek incecik olacak şekilde açın. Her birinin üzerine erittiğiniz 100 g Bizim Yağ’dan sürün. Üzerine kaymak parçaları ilebir kasede karıştırdığınız toz şeker ve Antep fıstığından serpip yufkayı kare şeklinde katlayın. Yapışmaz tavayı ısıtıp katmerlerin her iki yüzünü kızartın. Kaymak ve toz Antep fıstığı ile süsleyerek servis yapın.", "Hamuru için\n" + "100 g Bizim Yağ\n" + "200 ml su\n" + "2~3 su bardağı un\n" + "1 çay kaşığı tuz\n" + "\n" + "Açmak için\n" + "Nişasta\n" + "\n" + "Arası için\n" + "250 gr kaymak\n" + "10 yemek kaşığı toz şeker\n" + "10 yemek kaşığı toz Antep Fıstığı\n" + "\n" + "Üzeri için\n" + "Toz Antep fsıtğı\n" + "Kaymak"));
        tüm_yemekler.add(new Yemek("Soğan Kebabı", "70 dk", "2 kişilik", R.drawable.sogankebap, "Soğanların kabuklarını soymadan uç kısımlarını kesin. Her birini üstten alt kısmını koparmayacak şekilde derin kesin. Bir kasede kıyma, tuz, karabiber ve salçayı yoğurun. Soğanların arasına yoğurduğunuz kıymaları doldurup bir fırın kabına dizin. İkiye kestiğiniz biberler ve dörde böldüğünüz domatesleri de ilave edin. Nar ekşisi ve erittiğiniz 50 g Bizim Yağ’ı ve sıcak suyu küçük bir kasede karıştırıp soğanların üzerinde gezdirin. Önceden ısıtılmış 180 derece fırında 20 dakika pişirin. Sıcak servis yapın.", "50 g Bizim Yağ\n" + "1 kg sarı soğan\n" + "300 g kıyma\n" + "Tuz\n" + "Karabiber\n" + "1 tatlı kaşığı biber salçası\n" + "1 yemek kaşığı nar ekşisi\n" + "1 çay bardağı sıcak su\n" + "2 sivri biber\n" + "3 domates"));
        tüm_yemekler.add(new Yemek("Ali Nazik", "60 dk", "4 kişilik", R.drawable.alinazik, "Patlıcanları yıkayın. Üzerlerini çatalla delip fırında ya da ocakta közleyin. Közlenen patlıcanların kabuklarını soyup ince doğrayın ve bir servis tabağına alın. Sarımsakları ezip süzme yoğurda ekleyin. Bizim Yağı bir sos tenceresinde eritin. Kıyma, salça ve ince doğradığınız biberleri ekleyin ve kıymanın rengi dönene kadar iyice kavurun. Tuz ve baharatlarla tatlandırın. Bir servis tabağına sırasıyla közleyip doğradığınız patlıcan, sarımsaklı yoğurt ve kıymalı harçtan koyup sıcak servis yapın.", "1 kg patlıcan\n" + "4 diş sarımsak\n" + "50 ml süzme yoğurt\n" + "30 g Bizim Yağ\n" + "900 g orta yağlı kıyma\n" + "1 tatlı kaşığı domates salçası\n" + "1 sivri biber\n" + "1 kırmızı kapya biberi\n" + "Tuz\n" + "Karabiber\n" + "Kırmızı pul biber"));
        tüm_yemekler.add(new Yemek("Şiveydiz", "65 dk", "4 kişilik", R.drawable.sivesdeyiz, "Kuzu etini tencereye alın. Üzerini hafif geçecek kadar su ekleyin ve suyunu çekene kadar pişirin. Zeytinyağını ekleyip bir kaç dakika daha pişirin. Taze sarımsakları beyaz kısımlarını 3’er santimlik parçalar şeklinde kesin. Malzemelerin üzerini geçecek kadar sıcak suyla birlikte tencereye ilave edin. Yumuşayana kadar pişirin. Haşlanmış nohutları ekleyip 10 dakika daha pişirin. Bir kasede süzme yoğurt, un ve yumurta sarısını ekleyip çırpın. Yemeğin sıcak suyundan yavaş yavaş ilave ederek yoğurdu ılındırın. Karışımı azar azar tencereye ilave edip 5 dakika daha pişirin. Tuzla tatlandırın. Tereyağını eritip naneyi ekleyin. Yemeğin üzerine gezdirip servis yapın.", "Yarım çay bardağı zeytinyağı\n" + "250 g kuzu kuşbaşı\n" + "500 g ayıklanmış taze sarımsak\n" + "1 su bardağı haşlanmış nohut\n" + "6 yemek kaşığı süzme yoğurt\n" + "1 yumurta sarısı\n" + "2 yemek kaşığı un\n" + "Tuz\n" + "Sıcak su"));
        tüm_yemekler.add(new Yemek("Hünkar Beğendi", "75 dk", "6 kişilik", R.drawable.hunkar, "Bostan patlıcanların üzerini çatalla birkaç yerinden delin ve fırın ızgarasında yumuşayıncaya kadar közleyin. Hafif soğuyunca kabuklarını soyun ve bir kaseye alın. Bizim Yağ Margarini eritin. Unu ilave edip pembeleşinceye kadar kavurun. Sütü azar azar ekleyip karıştırın. Patlıcanı ilave edip karıştırın. Rendelenmiş kaşar peyniri, tuz ve karabiber ekleyip ocaktan alın. Ayrı bir tencerede yemeklik doğranmış soğan, kuşbaşı et, sarımsak ve defne yaprağını kalan Bizim Yağ Margarin ile kavurun. Salça ve suyu ekleyip etler yumuşayıncaya kadar pişirin. Tuz, karabiber ile tatlandırın. Beğendiyi servis tabağına alıp üzerine etleri yerleştirip servis yapın.", "50g BizimYağ Margarin\n" + "250 gkuşbaşı dana eti\n" + "1soğan\n" + "1 su bardağı su\n" + "1defne yaprağı\n" + "Yarım yemek kaşığı salça\n" + "2 diş sarımsak\n" + "Tuz + Karabiber\n" + "\n" + "Beğendi için\n" + "\n" + "30g BizimYağ Margarin\n" + "2 bostan patlıcan\n" + "1yemek kaşığı un\n" + "1 su bardağı süt\n" + "Yarım çay bardağı rendelenmiş kaşar peyniri\n" + "Tuz + Karabiber"));
        tüm_yemekler.add(new Yemek("Antep Fıstıklı Zeytinyağlı Sarma", "80 dk", "6 kişilik", R.drawable.antepsarma, "Pirinci yıkayıp suyunu süzün. Soğanların kabuğunu soyup kıyın. Zeytinyağını tencereye alıp ısıtın ve soğanı kısık ateşte kavurun. Kıyılmış sarımsak, pirinç, domates ve biber salçasını ekleyip hafifçe kavurmaya devam edin. Antep fıstığı, tuz, karabiber ve limon suyu ekleyip karıştırın. Yarım su bardağı sıcak su ekleyip 5 dakika pişirin. Salamura yaprakların saplarını koparıp kaynayan suya ekleyin ve 5 dakika bekletip soğuk su dolu bir kabın içine alın. Yaprakları süzgece alıp suyunu süzün. Yaprakların içine hazırladığınız iç malzemeyi paylaştırıp sarın. Tencerenin tabanına artan yaprakları ve saplarını dizin. Üzerine sarmaları yerleştirin. Sarmaların üzerine yaprak ve porselen bir tabak kapatın. Üzerini geçecek kadar tuzlu su ekleyip su kaynayana kadar hızlı daha sonra kısık ateşte 30 dakika pişirin. Porselen tabağı alıp 15 dakika daha pişirin. Sarmaları piştikten sonra tencere içinde 10 dakika bekletip servis yapın.", "750 gr salamura yaprak\n" + "1 su bardağı pirinç\n" + "1 yemek kaşığı biber salçası\n" + "1 yemek kaşığı domates salçası\n" + "1 su bardağı sızma zeytinyağı\n" + "2 soğan\n" + "1 baş sarımsak\n" + "Tuz\n" + "Karabiber\n" + "2 limonun suyu (koruk suyu veya sumak ekşisi de olabilir)\n" + "Soyulmuş Antep fıstığı"));
        tüm_yemekler.add(new Yemek("Yuvalama", "70 dk", "6 kişilik", R.drawable.yuvalama, "Kuzu etini bol suyla yıkayıp tencereye alın. 6-7 bardak su ekleyip 45 dakika pişirin. Üzerinde biriken köpüğü bir kaşıkla alın. Nohudu ekleyip pişirmeye devam edin. Köftenin harcı için pirinç ve kıymayı bir kaba alın. Tuz ve karabiber ekleyip yoğurun. Nohuttan küçük köfteler hazırlayın. Hazırladığınız köfteleri bir süzgecin içine alın. Süzgeci tencerenin üzerine yerleştirip tencerenin kapağını kapatın ve 20-25 dakika buharda pişirin. Süzme yoğurdu bir kaseye alıp çorbanın suyundan birkaç kaşık ekleyip yoğurdun ılınmasını sağlayın. Yoğurdu tencereye azar azar ve sürekli karıştırarak ekleyin. Bir taşım pişirip köfteleri ekleyip karıştırın. Tuz ve karabiberle tatlandırın. Tereyağı ve sadeyağı tavaya alıp ısıtın. Naneyi ekleyip çorbanın üzerine gezdirin. Yanında pirinç pilavıyla birlikte servis yapın.", "500 gr parça kuzu eti\n" + "1 su bardağı geceden ıslatılmış nohut\n" + "2 su bardağı pirinç (geceden ıslatılmış ve kurumaya bırakılmış)\n" + "250 gr yağsız dana kıyma (iki kere çekilmiş)\n" + "5 su bardağı süzme yoğurt\n" + "2 yemek kaşığı sadeyağ veya tereyağı\n" + "1 yemek kaşığı nane\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Antep Usulü Etli Karışık Dolma", "90 dk", "8 kişilik", R.drawable.dolma, "Patlıcanları alacalı soyup tuzlu suda bekletin. Patlıcanların içini oyarak hazırlayın. Domateslerin üzerinden bir kapak kesip içini çıkarın. Biberlerin sap ve tohumlarını temizleyin. Soğan ve sarımsağın kabuğunu temizleyip kıyın. Pirinç, soğan, sarımsak, kıyma, pirinç, domates salçası, biber salçası, limon suyu, bir miktar su, tuz ve karabiberi bir kapta karıştırın. Sebzelerin içlerine paylaştırıp ağız kısımlarını kestiğiniz parçalarıyla kapatın. Tencereye patlıcan, biber ve domates sıralamasıyla dizin. Dolmaların üzerine bir porselen tabak kapatıp üzerini hafifçe geçecek kadar su ekleyin. Önce hızlı su kaynamaya başladığında kısık ateşte 45 dakika pişirin. Dolmaların üzerindeki porselen tabağı alıp 15 dakika daha pişirin. Dolmaları tencerede 5 dakika bekletip sonrasında servis yapın.", "10 patlıcan\n" + "10 dolmalık biber\n" + "10 domates\n" + "1 baş sarımsak\n" + "2 soğan\n" + "500 gr yağlı kıyma\n" + "2 su bardağı pirinç\n" + "1 yemek kaşığı domates salçası\n" + "1 yemek kaşığı biber salçası\n" + "2 limonun suyu\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Yoğurtlu Patates", "70 dk", "6 kişilik", R.drawable.patates, "Parça et, nohut ve bir miktar suyu tenceye alıp üzerini geçecek kadar su ekleyin. Pişme sırasında üzerinde biriken köpüğü alın. Nohut ve et yumuşayana kadar pişirin. Patatesleri iri parçalar şeklinde doğrayın. Kızgın yağda kızartın. Patatesleri pişen nohutlu ete ekleyin. Süzme yoğurt, yumurta, un ve zeytinyağını bir kasede iyice çırpın. Pişen yemeğin suyundan birkaç kaşık ekleyip karışımı ılındırın. Yemeğe azar azar ve karıştırarak ekleyin. Un kokusu gidene kadar pişirin. Tuzla tatlandırın. Tereyağını tavada eritip haspiri ekleyin. Yemeğin üzerine gezdirin. Sıcak servis yapın.", "1 kg patates\n" + "1 su bardağı geceden ıslatılmış nohut\n" + "500 gr parça et\n" + "3 su bardağı süzme yoğurt\n" + "1 yumurta\n" + "1 yemek kaşığı un\n" + "3 yemek kaşığı zeytinyağı (yoğurt için)\n" + "2 yemek kaşığı sadeyağ veya tereyağı\n" + "1 yemek kaşığı haspir\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Şam Böreği", "65 dk", "6 kişilik", R.drawable.sam, "Unu bir kaba eleyin. Mayayı ılık su ile eriyinceye kadar karıştırın. Unu, tuz ve mayalı su ile yoğurarak bir hamur hazırlayın. Üzerini bez ya da streç film ile kapatarak ılık bir ortamda 30 dakika kabarmaya bırakın. Soğanı ve maydanozu kıyın. Pirinci yıkayıp, kaynar tuzlu suda haşlayın ve suyunu süzün. Kıymayı suyla birlikte bir tavaya alın. Suyunu çekinceye kadar pişirin. Haşlanmış pirinci, kıymayı, soğanı, maydanozu, tuzu ve biberleri bir kapta karıştırarak harcı hazırlayın. Dinlenmiş olan hamuru ceviz büyüklüğünde 30 eşit parçaya bölüp, yuvarlayarak topak haline getirin. Herbirini unlanmış tezgahta merdane ile 10 cm çapında açın. Açtığınız hamurların ortalarına harcı paylaştırın. Yarım ay biçiminde kapatıp, uçlarını açılmamaları için bastırın. Az miktarda ayçiçeği yağını tavada ısıtın. Hazırladığınız börekleri tavaya yerleştirip, her iki yanı da altın sarısı renk alıncaya kadar kızartın. Sıcak servis yapın.", "4 su bardağı un\n" + "1 su bardağı su\n" + "10 gr yaş maya\n" + "Tuz\n" + "1 soğan\n" + "1.5 çay kaşığı kırmızı pul biber\n" + "1 demet maydanoz\n" + "¾ su bardağı haşlanmış pirinç\n" + "250 gr yağsız kıyma\n" + "Yarım su bardağı su\n" + "Tuz\n" + "Karabiber\n" + "Kızartmak için ayçiçeği yağı"));

        tüm_yemekler.add(new Yemek("Simit Tiridi", "45 dk", "4 kişilik", R.drawable.simit, "Simitleri küçük parçalar şeklinde ufalayın. Et suyunu tencerede ısıtıp ekmekleri ekleyip yumuşatın. Kıymayı kendi yağında ve suyunda kavurun. Simit parçalarını servis tabaklarına paylaştırın. Üzerine kavrulmuş kıymayı ekleyin. Sarımsağı kıyıp yoğurtla karıştırın. Sarımsaklı yoğurdu üzerine ekleyin. Yağı kızdırıp üzerine gezdirin. Kıyılmış maydanoz serpip servis yapın.", "5 susamsız simit\n" + "250 gr kıyma\n" + "Maydanoz\n" + "Sarımsak\n" + "Yoğurt\n" + "Et suyu\n" + "100 gr tereyağı"));
        tüm_yemekler.add(new Yemek("Akçaabat Köftesi", "90 dk", "6 kişilik", R.drawable.akcabat, "Gerdan eti, döş eti, ekmek, gömlek yağı ve sarımsakları et kıyma makinesinden geçirin. Mümkünse mermer bir zemin üzerine alarak kıvam alana kadar yoğurun. Küçük yumurta büyüklüğünde parçalara ayırıp yassı yuvarlak şekil verin. Izgarada pişirip servis yapın.", "1 kg döş kıyma (dana)\n" + "600 gr gerdan kıyma (dana)\n" + "400 gr bayat ekmek içi\n" + "6 iri diş sarımsak\n" + "300 gr gömlek yağı\n" + "2 yemek kaşığı tuz"));
        tüm_yemekler.add(new Yemek("Pepeçura", "70 dk", "6 kişilik", R.drawable.pepecura, "Siyah üzümü iyice yıkayın. Suyla birlikte bir tencerede kaynatın. Toz şekeri ekleyip 5 dakika daha kaynatın. Süzgece alıp elinizle bastırarak suyunu süzün. Üzüm suyundan 1 su bardağı ayırıp nişastayla birlikte karıştırın. Pürüzsüz hale getirin. Kalan üzüm suyuna ekleyip sürekli karıştırarak pişirin. Küçük kaselere ya da kalıplara sıcak olarak paylaştırın. Buzdolabında iyice soğutup katılaşınca servis tabağına ters çevirin. Üzümlerle süsleyip servis yapın.", "1 kg siyah üzüm\n" + "6 su bardağı su\n" + "1 su bardağı toz şeker\n" + "1 çay bardağı mısır nişastası"));
        tüm_yemekler.add(new Yemek("Kuymak", "60 dk", "10 kişilik", R.drawable.kuymak, "Tereyağını bakır bir tavaya alıp kısık ateşte eritin. Mısır ununu ekleyip ateşi yükseltin ve 1 dakika kavurun. Suyu azar azar ekleyip ve karıştırarak kıvam alana kadar (tereyağı mısır ununun üzerine çıkana kadar) pişirin. Telli peyniri ilave edin. Peynir erimeye başlığında bekletmeden servis yapın.", "350 gr mısır unu\n" + "350 gr tereyağı\n" + "350 gr telli peynir\n" + "30 gr tuz\n" + "2 litre su"));
        tüm_yemekler.add(new Yemek("Çerkez Tavuğu", "75 dk", "6 kişilik", R.drawable.cerkez, "Tavuğu yıkadıktan sonra bir tencerede 4 su bardağı su ilavesiyle, iyice yumuşayana kadar haşlayın. Suyunu süzüp derisini çıkarın ve çok ufak parçalar halinde etini didikleyin. Bayat ekmek içi, ceviz ve sarmısakları bir mutfak robotundan geçirerek veya havanda ezerek püre haline getirin. Üzerine 1 su bardağı ılık tavuk suyu, tuz, toz kişniş ekleyip karıştırın. Tavuk etini ekleyip malzeme özleşene kadar karıştırın (karışımın kıvamı çok katı olursa biraz tavuk suyu ekleyebilirsiniz). Servis tabağına alın. Tereyağını tavada kızdırıp kırmızı pul biberi ekleyin. Hızlıca yemeğin üzerine gezdirip ılık olarak servis yapın.", "1 adet bütün tavuk\n" + "2 dilim bayat ekmek içi\n" + "3 diş sarmısak\n" + "1.5 su bardağı ceviz içi\n" + "1 çay kaşığı tuz\n" + "Karabiber\n" + "Toz kişniş\n" + "Sos için"));
        tüm_yemekler.add(new Yemek("Dible Fasulyeli Pilav", "45 dk", "6 kişilik", R.drawable.fasulyelipilav, "Taze fasulyeleri küçük parçalar şeklinde doğrayın. Soğanın akabuğunu soyup piyazlık doğrayın. Fasulyelerin yarısını tencereye alın. Üzerine soğan, pirinç, rendelenmiş domates, tuz ve pul biber ekleyin. Kalan fasulyeleri ilave edin. Su ve tereyağını ekleyip kısık ateşte kapağı kapalı olarak kendi buharında pişirin. Yemeği servis tabağına alın. Üzerine tavada ısıtılmış fındık yağını gezdirip servis yapın.", "1 kg taze fasulye\n" + "1 su bardağıpirinç\n" + "3 orta boy soğan\n" + "1 çay bardağı su\n" + "1 küçük domates\n" + "1 yemek kaşığı tereyağı\n" + "Tuz\n" + "Kırmızı pul biber\n" + "Fındık yağı"));
        tüm_yemekler.add(new Yemek("Karalahana Çorbası", "55 dk", "6 kişilik", R.drawable.karalahana, "Karalahanayı ince doğrayın. Üzerine tuz serpip biraz ovun ve acısının çıkmasını sağlayın. Tereyağı ile zeytinyağını tencerede ısıtın. Üzerine yemeklik doğradığınız soğanlar ekleyip soteleyin. Soğan yumuşayınca karalahanayı ilave edin. 4 su bardağı su ekleyip kaynamaya bırakın. Karalahana yumuşayınca kırmızıbiber, barbunya ve mısırı ekleyin. Yaklaşık 7-8 dakika kaynattıktan sonra tuz ve karabiber ile tatlandırın. Sıcak servis yapın.", "1 demet karalahana\n" + "200 gr haşlanmış barbunya\n" + "2 soğan\n" + "4 su bardağı su\n" + "1 su bardağı tane mısır\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı zeytinyağı\n" + "1~2 acı kuru kırmızıbiber\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Pumpum Çorbası", "60 dk", "8 kişilik", R.drawable.pumpum, "Tencereye 5 su bardağı ılık su veya et suyunu, mısır ununu ekleyip karıştırın. Kaynayana kadar karıştırın. Kavurmayı tavada 2-3 dakika kavurun. Kaynayıp koyulaşan çorbanın üzerine ekleyip karıştırın. Tuzla tatlandırın. Yaklaşık 4-5 dakika pişirin. Tereyağı ve pul biberi sos tenceresinde kızdırın. Hazırladığınız çorbanın üzerine gezdirip sıcak servis yapın.", "1 su bardağı mısır unu\n" + "5 su bardağı su veya et suyu\n" + "2 dilim kavurma\n" + "Tuz\n" + "2 tatlı kaşığı tereyağı\n" + "1 tatlı kaşığı kırmızı pul biber"));
        tüm_yemekler.add(new Yemek("Topik", "30 dk", "11 kişilik", R.drawable.topik, "", "Malzemeler\n" + "3 su bardağı nohut\n" + "5 patates\n" + "1 tatlı kaşığı tuz\n" + "1 tatlı kaşığı tozşeker\n" + "1 tatlı kaşığı tarçın\n" + "1 çay bardağı tahin\n" + "\n" + "İç malzeme için\n" + "3 kg soğan\n" + "1 tatlı kaşığı tuz\n" + "50 gr dolmalık üzüm\n" + "50 gr çamfıstığı\n" + "4 tatlı kaşığı tarçın\n" + "2 tatlı kaşığı yenibahar\n" + "2 tatlı kaşığı karabiber\n" + "2 tatlı kaşığı tozşeker\n" + "500 gr tahin"));
        tüm_yemekler.add(new Yemek("Fasulye Pilaki", "60 dk", "4 kişilik", R.drawable.fasulyepilaki, "Kuru fasulyeleri bir gün önceden ıslatın. Havuçları yeşilliklerinden ayırıp yıkayın ve zar şeklinde doğırayın. Sarımsakları ve soğanı ayıklayıp küp şeklinde doğrayın. Domatesleri yıkayıp rendeleyin. Sivribiberleri ince ince doğrayın. Patates, kereviz ve yapraklarını temizleyip yıkayın ve zar şeklinde doğrayın. Maydanozu yıkayıp kıyın.\n" + "\n" + "Fasulyeleri iyice yıkayıp bir tencereye alın. Domates, biber, sarımsak, soğan, havuç, karabiber, zeytinyağını ve yeterince sıcak suyu fasulyeye ekleyip pişirmeye başlayın. Fasulye ve havuçlar yarı yarıya piştiğinde patates, kereviz, yaprakları ve maydanozu ilave edin. Son olarak tuz ve tozşeker serpin. Tüm malzemeler pişince ocaktan alın. Sıcak ya da soğuk servis yapın.", "2 su bardağı kuru fasulye\n" + "1 demet kum havucu\n" + "7~8 diş sarımsak\n" + "1 soğan\n" + "2 domates\n" + "3~4 sivri biber\n" + "1 çay kaşığı kırmızıbiber\n" + "1 kahve fincanı zeytinyağı\n" + "2 patates\n" + "1 kereviz ve yaprakları\n" + "1 demet maydanoz\n" + "1 tatlı kaşığı tozşeker\n" + "Tuz\n" + "Karabiber"));

        tüm_yemekler.add(new Yemek("Gazete Baklavası", "90 dk", "6 kişilik", R.drawable.gazetebaklava, "Baklava hamuru için un, yumurta, kabartma tozu, yoğurt, soda ve eritilmiş Bizim Yağ, sirke ve limon suyunu karıştırıp iyice yoğurun. Hamuru 28 bezeye ayırıp unlanmış tezgaha alın. Baklavanın şerbeti için şeker, su ve limonu geniş bir tencereye alarak kaynatın. Kaynadıktan sonra soğuması içi kenara alın. Dinlenen hamurları aralarına nişasta serperek incecik açın. Açtığınız yufkaları oklavaya sarıp büzün. Büyükçe bir kağıdın üzerine açarak oklavadan ayırın. Diğer bezeleri de aynı şekilde açıp bir kağıdın üzerine yerleştirerek dinlendirin. Dinlenen yufkanın üzerine ceviz serpin. Kağıdı iki ucundan tutarak yufkayı sarın ve daha sonra dilimleyin. Yağlı kağıt serili fırın tepsisine yerleştirin. Bizim Yağı eritin. Üzerindeki köpüğü alıp tepsideki baklavaların üzerine dökün. Önceden ısıtılmış 180 derece fırında üzeri kızarıncaya kadar pişirin. Soğuyan şerbeti sıcak baklavanın üzerine döküp Antep fıstığı ile süsleyerek servis yapın. \n" + "\n", "Hamuru için\n" + "4 su bardağı un\n" + "2 yumurta\n" + "1 paket kabartma tozu\n" + "1 çay bardağı yoğurt\n" + "1 çay bardağı soda\n" + "1 çay bardağı eritilmiş Bizim Yağ\n" + "1 tatlı kaşığı sirke\n" + "1/4 limonun suyu\n" + "\n" + "İçi için\n" + "1 su bardağı ince çekilmiş ceviz\n" + "\n" + "Şerbeti için\n" + "4 su bardağı şeker\n" + "4 bardak su\n" + "1/2 limon\n" + "\n" + "Açmak için\n" + "Nişasta\n" + "\n" + "Üzeri için\n" + "150 g Bizim Yağ\n" + "1 çay bardağı Antep fıstığı"));
        tüm_yemekler.add(new Yemek("Yağ Mantısı", "100 dk", "6 kişilik", R.drawable.yagmantisi, "Hamuru hazırlamak için unu geniş bir kaba alın. Ortasını havuz gibi açıp yoğurt, yumurta, maya ve tuzu ekleyip yoğurun. Azar azar suyu ilave edip yoğurmaya devam edin. Hamurun üzerini nemli bir bezle örtüp 40 dakika dinlendirin. İç harcını hazırlamak için kıymayı geniş bir kaba alın. Üzerine rendelenmiş soğan, tuz ve karabiber ekleyip karıştırın. Sosu için Bizim Yağı bir sos tenceresinde eritin. Ezdiğiniz sarımsaklar, salça ve rendelediğiniz domatesi ekleyin. Tuz ve karabiberle tatlandırıp pişirin. Dinlenen hamuru unlanmış tezgah üzerinde açıp klasik mantı hamurundan daha büyük olacak kareler kesin. Ortalarına kıymalı harçtan yerleştirin. Uçlarını karşılıklı köşelerden birleştirerek kapatın. Bütün kareler için aynı işlemi tekrarladıktan sonra mantıları bol kızgın yağda kızartın. Kızaran mantıları servis tabağına alıp üzerine yoğurt ve domates sosundan gezdirip nane ile süsleyerek servis yapın.", "2 su bardağı un\n" + "2 yemek kaşığı yoğurt\n" + "1 yumurta\n" + "1 tatlı kaşığı kuru maya\n" + "1 tatlı kaşığı tuz\n" + "2 su bardağı su\n" + "İç harcı için\n" + "150 g kıyma\n" + "1 soğan\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Sosu için\n" + "60 g Bizim Yağ\n" + "2 diş sarımsak\n" + "1 tatlı kaşığı biber salçası\n" + "2 domates\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Kızartmak için\n" + "Bizim Ayçiçek Yağı\n" + "\n" + "Üzeri için\n" + "Yoğurt"));
        tüm_yemekler.add(new Yemek("Yağlama", "70 dk", "4 kişilik", R.drawable.yaglama, "Hamuru için malzemeleri bir kaba alarak yoğurun. Üzerini nemli bir bezle örtüp 20 dakika dinlendirin. Mayalanan hamuru küçük bezelere ayırın. Merdane yardımıyla 15 cm çapında açın. Tavayı Bizim Yağ Margarin ile yağlayıp hamurun iki yüzünü de pişirin. İç harcı için Bizim Yağ Margarini bir tencerede eritin. Kıymayı ekleyip kavurun. Yemeklik doğradığınız soğan, küp doğradığınız domates ve Bizim Ayçiçek Yağını ekleyerek pişirmeye devam edin. Yarım çay bardağı su ekleyip bir süre daha pişirin. Tuz ve karabiberle tatlandırın. Kıymalı harcı yağlamaların arasına sırasıyla koyup üzerine sarımsaklı yoğurt gezdirerek servis yapın.", "Bazlama hamuru için\n" + "4 subardağı un + Bir tutam tuz\n" + "Yarımpaket yaş maya + 1 çay bardağı su\n" + "\n" + "Harcı için\n" + "Yarımçay bardağı BizimAyçiçek Yağı\n" + "30g BizimYağ Margarin\n" + "300 gkıyma + 2 soğan\n" + "3domates + Tuz + Karabiber\n" + "Biryemek kaşığı salça\n" + "Yarımçay bardağı su"));
        tüm_yemekler.add(new Yemek("Sülbiye", "80 dk", "4 kişilik", R.drawable.sulbiye, "Tereyağını tencerede eritin. Etleri ekleyin ve etler suyunu bırakıp çekene kadar kavurun. Kabuğu soyulmuş arpacık soğanları ve sarımsakları bütün olarak ekleyip soğanlar şeffaflaşana kadar arada bir karıştırarak kavurmaya devam edin. Salçayı ekleyin ve 1-2 dakika daha kavurun. Tuz, baharat ve haşlanmış nohutları ekleyin. Etlerin ve diğer malzemelerin üstünü hafifçe aşacak kadar sıcak su ekleyin. Tenceredeki tüm malzemeler yumuşayıncaya kadar kısık ateşte pişirin. Üzerine taze çekilmiş karabiber serpip servis yapın.", "350 gr parça dana eti\n" + "350 gr arpacık soğanı\n" + "8~10 diş sarımsak\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı domates salçası\n" + "1.5 su bardağı haşlanmış nohut\n" + "1 tatlı kaşığı kimyon\n" + "Tuz\n" + "Karabiber\n" + "Sıcak su"));
        tüm_yemekler.add(new Yemek("Pekmezli Pelte", "65 dk", "6 kişilik", R.drawable.pekmezlipelte, "1 Su bardağı üzüm pekmezi, 2 su bardağı su ve 4.5 yemek kaşığı buğday nişastasını çukur bir kaba alıp iyice karıştırın. Kısık ateşte koyulaşıp muhallebi kıvamına gelene kadar pişirin. Hazırladığınız karışımı büyük bir tepsiye doldurun. Pelte soğuyana kadar bekletin. Üzerini cevizle süsleyip, servis yapın.", "1 su bardağı üzüm pekmezi\n" + "2 su bardağı su\n" + "4.5 yemek kaşığı buğday nişastası\n" + "\n" + "Üzeri için\n" + "Ceviz içi"));
        tüm_yemekler.add(new Yemek("Ankara Tava", "45 dk", "6 kişilik", R.drawable.ankaratava, "Orta büyüklükte parçalar şeklinde doğranmış eti tencereye alıp biraz yağ ilavesiyle soteleyin. İnce doğranmış soğanı ekleyip sotelemeye devam edin. Etin büyüklüğünde kesilmiş biberleri ekleyip sotelemeye devam edin. Yine yanı büyüklükte kesilmiş domatesi ilave edip pişirmeye devam edin. Domates salçası ve tuzu ekleyip malzeme yumuşayana kadar pişirin. Tuzla tatlandırın. Arpa şehriyeyi ayçiçeği yağında kavurun. Üzerini geçecek kadar sıcak su ekleyip yumuşayana kadar kısık ateşte pişirin. Tuzla tatlandırın. Arpa şehriyeyi servis tabağına alın. Üzerine eti ekleyip servis yapın.", "350 gr parça et\n" + "1 soğan\n" + "2 orta boy domates\n" + "2 sivri biber\n" + "2 salçalık kırmızıbiber\n" + "1 yemek kaşığı domates salçası\n" + "Ayçiçeği yağı\n" + "1 kase arpa şehriye\n" + "Sıcak su\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Çibörek", "60 dk", "6 kişilik", R.drawable.ciborek, "Un, tuz ve suyu bir kapta karıştırıp yumuşak bir hamur hazırlayın. Soğanın kabuğunu soyup rendeleyin. Kıyma, tuz, karabiber ve su ekleyip karıştırın. Hamuru ceviz büyüklüğünde bezelere ayırın. Yaklaşık 20 cm çapında açın. Hamurun yarısına kıymayı harcı ince bir tabaka halinde olacak şekilde yayın. Diğer tarafını üzerine kapatıp kenarlarına parmak uçlarınızla bastırın. Kızgın ayçiçeği yağında her iki yüzlerini kızartın. Sıcak servis yapın.", "4 su bardağı un\n" + "1 tatlı kaşığı tuz\n" + "Su\n" + "1 soğan\n" + "250 kg kıyma\n" + "1 çay kaşığı tuz\n" + "1 çay kaşığından biraz az karabiber\n" + "Yarım çay bardağı su\n" + "Kızartmak için ayçiçeği yağı"));
        tüm_yemekler.add(new Yemek("Bamya Çorbası", "50 dk", "6 kişilik", R.drawable.bamyacorba, "Kuru bamyaları avucunuzda ovalayarak küçük tüylerinden arındırın. Kaynar suya ekleyip yumuşayana kadar haşlayın. Soğanın kabuğunu soyup kıyın. Ayçiçeği yağını tencerede ısıtıp soğanı kısık ateşte kavurun. Salça, et ve et suyunu ilave edin. Su kaynadığında bamyaları ekleyin. Tuzla tatlandırın. Limon tuzunu ilave edip 10 dakika daha pişirin. Bekletmeden servis yapın.", "50 gr kuru bamya (100 gramlık paketlerde satılır)\n" + "200 gr küçük doğranmış et\n" + "3 su bardağı et suyu\n" + "1 soğan\n" + "Ayçiçeği yağı\n" + "1 yemek kaşığı domates salçası\n" + "2 parça limon tuzu\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Madımak", "70 dk", "6 kişilik", R.drawable.madimak, "Madımakları ayıklayın ve yıkayın. Ayçiçeği yağını tencerede ısıtın. Piyazlık doğranmış soğanı ekleyip kısık ateşte kavurun. İnce doğranmış biberleri ekleyip kavurmaya devam edin. Domatesi de küçük doğrayıp ekleyin. Madımakların suyunu süzüp ekleyin. Yemeğin pişmesine az kala ince bulguru ekleyip karıştırın. Tuzla tatlandırın. Ilık servis yapın.", "500 gr madımak\n" + "2 soğan\n" + "3 yemek kaşığı ayçiçeği yağı\n" + "1 domates\n" + "4~5 sivri biber\n" + "1 çay bardağı ince bulgur\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Kokina Çorbası", "45 dk", "4 kişilik", R.drawable.kokina, "Kuzu etini tencereye alın. Üzerine 4 su bardağı su ilave edip haşlayın. Ayrı bir tencerede tereyağı ile ayçiçeği yağını ısıtın. Üzerine yemeklik doğradığınız soğan ve sarımsağı ilave edip soteleyin. Haşladığınız eti ilave edip karıştırın. İnce kıydığınız lahana ve domates salçasını da ekleyip karıştırın. Bulgur, et suyu, tuz ve karabiberi ilave edip kaynamaya bırakın. Orta ateşte 15 dakika pişirip sıcak servis yapın.", "200 gr lahana turşusu\n" + "1 diş sarımsak\n" + "1 soğan\n" + "400 gr parça kuzu kuşbaşı eti\n" + "2/3 çay bardağı pilavlık bulgur\n" + "2 yemek kaşığı domates salçası\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı ayçiçeği yağı\n" + "4~5 su bardağı su veya et suyu\n" + "Tuz\n" + "Karabiber"));

        tüm_yemekler.add(new Yemek("Erzincan Lokumu", "90 dk", "6 kişilik", R.drawable.erzincanlokum, "Derin bir kapta yumurta, Bizim Yağ Margarin, Bizim Ayçiçek Yağı ve şekeri karıştırın. Üzerine un ve kabartma tozunu ilave edin. Kurabiye hamurundan biraz daha yumuşak bir hamur elde edene kadar yoğurun. Hazırladığınız hamuru yuvarlak bir fırın kabına elinizle yayın. Üzerini düzeltip 180 derece fırında hafif pembeleşinceye kadar pişirin. Soğuduktan sonra baklava şeklinde dilimleyin. Üzerine pudra şekeri serperek servis yapın.", "125g BizimYağ Margarin\n" + "1su bardağı BizimAyçiçek Yağı\n" + "1 subardağı şeker + 1 yumurta\n" + "1paket kabartma tozu\n" + "3~4 subardağı un"));
        tüm_yemekler.add(new Yemek("Kaburga Dolması", "70 dk", "6 kişilik", R.drawable.kaburgadolma, "Pirinci bol suyla yıkayıp suyunu süzün. Kaburganın yağlı kısmından cep şeklinde kesin. Tereyağını tencereye alıp eritin. Badem ve kıymayı ekleyip kavurun. Kıyılmış soğanı ekleyip kavurmaya devam edin. Tencereye alıp birkaç dakika kavurun. Kıyılmış maydanoz, baharat ve tuz ekleyip karıştırın. Sıcak su ekleyip kısık ateşte pirinçler hafifçe yumuşayana kadar pişirin. Hazırladığınız pilavı kaburgaya açtığınız cebe doldurun. Etin ağız kısmını iplikle dikin. Kaburganın her yerine salça sürüp yağda kızartın. Sıcak fırına alıp 2 saat boyunca pişirin. Sıcak servis yapın.", "2.5 kg kaburga (koyun eti~sağ göğüs kısmı)\n" + "250 gr tereyağı\n" + "150 gr kabuğu soyulmuş badem içi\n" + "300 gr kıyma\n" + "1 soğan\n" + "750 gr pirinç\n" + "2 yemek kaşığı domates salçası\n" + "1 demet maydanoz\n" + "2 su bardağı sıcak su\n" + "Tuz\n" + "Kırmızı toz biber\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Ev Helvası", "45 dk", "6 kişilik", R.drawable.evhelvasi, "Su ve şekeri tencereye alıp kaynatın. Şerbet kıvımına geldiğinde tencereyi ocaktan alın. Tereyağını başka tencereye alıp eritin. Hafif fokurdamaya başladığında unu azar azar ekleyip kavurun. Unun rengi değiştiğinde şerbeti azar azar ve sürekli karıştırmaya devam ederek ilave edin. Un şerbeti tamamen çekene kadar pişirin. Helva hafif ılındığında kaşıkla şekil vererek servis tabağına alın. Üzerine ufalanmış ceviz içi serpip servis yapın.", "1 kg un\n" + "250 gr tereyağı\n" + "1 litre su\n" + "1 kg toz şeker\n" + "Ufalanmış ceviz içi"));
        tüm_yemekler.add(new Yemek("Pancar Kavurma", "50 dk", "6 kişilik", R.drawable.pancarkavurma, "Pancar otlarını temizleyip iri parçalar şeklinde doğrayın. Haşlayıp suyunu süzün. Soğanların kabuğunu soyup kıyın. Biberlerin çekirdeklerini temizleyip ince doğrayın. Tereyağını tencerede eritip soğanı kısık ateşte kavurun. Biberleri ekleyip kavurmaya devam edin. Pancar otunu ilave edip birkaç dakika daha kavurun. Tuz ve karabiberle tatlandırın. Servis yapın.", "1 kg pancar otu\n" + "2 soğan\n" + "1 kırmızı sivri biber\n" + "1 sivri biber\n" + "3 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Küt Böreği", "80 dk", "6 kişilik", R.drawable.kutboregi, "Unu eleyip çukur bir kaba alın. Ortasını havuz şeklinde açıp kabartma tozu, ayçiçeği yağı, yoğurt, tuz ve yumurtayı ekleyip yoğurun (gerekirse ayçiçeği yağı ilavesi yapabilirsiniz). Hamuru 20 eşit bezeye ayırın. Bezeleri pasta tabağı büyüklüğünde açıp aralarına oda ısısında yumuşatılmış sade yağ sürerek üst üste dizin. Bezelerin hepsini oklavayla yuvarlak bir tepsi büyüklüğünde açın. Üzerine tekrar sade yağ sürüp rulo şekline sarın. Ruloyu üç parçaya kesip buzdolabında 1 saat bekletin. Ruloların kesik kısımlarından bastırıp hamurlara yassı şekil verin. Tepsi büyüklüğünde açıp aralarına sade yağ sürerek tepsiye dizin. Üstteki yufkanın üzerine sade yağ sürüp önceden ısıtılmış 180 derece fırında kızarana kadar pişirin. Küçük dikdörtgen parçalar şeklinde dilimleyin. Üzerine pudra şekeri serpip servis yapın.", "1 paket kabartma tozu\n" + "1 çay bardağı ayçiçeği yağı\n" + "1 çay bardağı yoğurt\n" + "2 yumurta\n" + "4.5 su bardağı un\n" + "200 gr sade yağ\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Mantar Yemeği", "60 dk", "6 kişilik", R.drawable.mantaryemegi, "Mantarları bol suyla yıkayıp küçük doğrayın. Soğanın kabuğunu soyup kıyın. Havuç ve biberleri temizleyip küçük parçalar şeklinde doğrayın. Tereyağını tencerede eritip havuç, biber ve soğanı kavurun. Mantarı ekleyip kavurmaya devam edin. Domates salçası, baharat, tuz ve çok az sıcak su ekleyip sebzeler yumuşayana kadar pişirin. Sıcak servis yapın.", "1 kg mantar\n" + "Tereyağı\n" + "1 soğan\n" + "1 havuç\n" + "2 salçalık kırmızıbiber\n" + "Domates salçası\n" + "Sıcak su\n" + "Kırmızı pul biber\n" + "Karabiber\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Aşotu Çorbası", "45 dk", "6 kişilik", R.drawable.asotucorba, "Buğdayı 4 su bardağı su ile yumuşayana kadar haşlayın. Yoğurt, yumurta sarısı ve unu derin bir kapta karıştırın. Buğdayı haşladığınız sudan 1 kepçe kadar alıp yoğurtlu karışıma ekleyerek karıştırın. Kaynamakta olan buğdaya ilave edip hızlıca karıştırın. Tavaya tereyağını ekleyip eritin. Üzerine yemeklik doğradığınız soğanı ilave edip soteleyin. Soğan yumuşayınca çorbaya ekleyip karıştırın. Kıyma, tuz ve karabiberi iyice yoğurun. Misketten daha küçük köfteler hazırlayın. Kaynayan çorbaya ilave edin. Kişniş, tuz ve karabiberi ilave edip köfteler yumuşayana kadar pişirin. Sıcak servis yapın.", "1 su bardağı buğday\n" + "1 soğan\n" + "1.5 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı aşotu (kişniş)\n" + "4 su bardağı yoğurt\n" + "1 yemek kaşığı un\n" + "1 yumurta sarısı\n" + "\n" + "Köfte için\n" + "250 gr kıyma\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Ciğer Taplemesi", "100 dk", "8 kişilik", R.drawable.cigertapleme, "Koyun ciğerini ince kıyın. Soğan ve biberi de ince kıyın. (ya da her birini kıyma makinesinden geçirin) Kıymayı, reyhanı, tuz ve karabiberi ilave edin. Bulguru ekleyip iyice yoğurun. Yoğurma işlemi sırasında suyu az az köfte hamuruna ilave edin. Yoğurma işlemi tamamlandıktan sonra avuç içerisinden ceviz büyüklüğünde yuvarlak köfteler hazırlayın. Elinizle yassılaştırarak 1 cm kalınlığında köfteler yapın. Bir tencereye bol su doldurup tuz ilave ederek kaynatın. Köfteleri kaynar suda ara ara karıştırarak haşlayın. Tencerenin kapağını kapatmayın. Pişme işlemi tamamlanınca büyük bir süzgeçle suyunu süzerek servis tabağına alın. Zeytinyağını (veya tereyağını) küçük bir tavada eritin. Kırmızı pul biberi ekleyip kızdırın. Köftelerin üzerine gezdirip, kıyılmış maydanoz ile sıcak servis yapın.", "1 kg. ciğer\n" + "400 gr kıyma\n" + "2 soğan\n" + "1 yeşil biber\n" + "1 su bardağı kuru reyhan\n" + "5 + 1/4 su bardağı köftelik bulgur\n" + "1.5 su bardağı su\n" + "Tuz\n" + "Karabiber\n" + "Yarım demet maydanoz\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Servis için\n" + "1 çay bardağı zeytinyağı\n" + "Kırmızı pul biber"));
        tüm_yemekler.add(new Yemek("Piti Kebabı", "80 dk", "8 kişilik", R.drawable.pitikebabi, "Nohutları akşamdan ıslatın. Suyunu değiştirip iyice haşlayın ve süzün. Nohutların kabuklarını soyup bir kâseye alın.\n" + "\n" + "Kuşbaşı etleri tuz ve karabiberle tatlandırıp bir tencereye alın. Az su ilave ederek iyice pişirin. Suyu azalırsa bir miktar daha su ekleyin.\n" + "\n" + "Yufkaları sac üzerinde kızartıp küçük parçalara ayırın ve bir tepsiye yayın. Üzerine kalan et suyunu gezdirin. Et ve nohudu harmanlayıp yufkaların üzerine yayın. Servis tabaklarına paylaştırıp servis yapın.", "500 gr kuşbaşı koyun eti\n" + "1 su bardağı nohut\n" + "4 yufka\n" + "Tuz\n" + "Karabiber"));
        tüm_yemekler.add(new Yemek("Kurze", "45 dk", "6 kişilik", R.drawable.kurze, "Soğanları temizleyip küp şeklinde doğrayın. Kıyma ve soğanı bir tavada sürekli karıştırarak kavurun. Tuz, 1 fincan sirke ve yarım limonun suyunu ilave edip tavayı ocaktan alın. \n" + "\n" + "Hamur için; unu bir kaba alın. Tuz serpip harmanlayın. Ortasını havuz gibi açıp yumurta ve suyu ekleyin. Unu kenarlardan ortaya toplayarak bir hamur yoğurun. Hamuru küçük bezelere ayırın. Hazırladığınız iç malzemeden ortasına yayın. Kenar uçlarını kapatarak rulo şeklinde sarın. \n" + "\n" + "Derin bir tencerede hafif tuzlu su kaynatın. Hamurları kaynar suda haşlayıp kevgirle süzgece alın. Mantıları servis tabaklarına paylaştırın. \n" + "\n" + "Salçayı suyla ezin. Tavaya alıp 1-2 dakika pişirin. Salçalı sosu kurzelerin (mantı) üzerine gezdirip servis yapın.", "500 gr yağlı koyun kıyması\n" + "2 soğan\n" + "1 kahve fincanı sirke\n" + "Yarım limonun suyu\n" + "3 çorba kaşığı domates salçası\n" + "Tuz\n" + "\n" + "Hamur malzemesi:\n" + " 2 su bardağı un\n" + "1 yumurta\n" + "Yarım su bardağı su"));

        //hindistan
        tüm_yemekler.add(new Yemek("Chicken Tikla", "45 dk", "6 kişilik", R.drawable.chickentikla, "Tavuğu bir tavaya alıp tuz, toz kırmızı biber, toz kakule ve limon suyu ile marine edin. Ocaktan alıp soğutun ve buzdolabında 6 saat bekletin. \n" + "\n" + "Süzme yoğurt, gıda boyası ve garam masalayı bir kaseye alıp karıştırın. Marine edilmiş tavukları ekleyip bu karışımla ovun. Tavukları önceden 250 dereceye ayarlanmış fırında 10 dakika ya da şişlere geçirip ızgarada iyice pişirin. Servis tabağına alın.  \n" + "\n" + "Yağı bir tavada ısıtın. Tane kimyon ve soğanı ekleyip pembeleşinceye kadar kavurun. Zencefil ve sarımsağı ekleyip 5 dakika daha soteleyin. Tavukların üzerine ekleyip servis yapın. \n", "500 gr kemiksiz tavuk eti\n" + "10 gr kırmızı toz biber\n" + "5 gr garam masala\n" + "5 gr toz yeşil kakule\n" + "5 gr toz kimyon\n" + "2 limonun suyu\n" + "200 gr süzme yoğurt\n" + "1 gr portakal rengi gıda boyası\n" + "Tuz"));
        tüm_yemekler.add(new Yemek("Dal Makhani", "45 dk", "6 kişilik", R.drawable.dal, "Sarımsakları temizleyip kıyın. Yeşil mercimek ve barbunyayı sekiz saat suda bekletin. Suyunu değiştirip mercimeği haşlayın. Pişince ocaktan alıp sudan geçirin. Zencefil ve kıyılmış sarımsağı ekleyip yeniden kaynatın. Kısık ateşte mercimeği iyice pişirin. \n" + "\n" + "Kıyılmış sarımsağı bir tavada soteleyin. Kırmızı toz biber ve domates püresini ekleyin. Birkaç dakika daha soteleyip ocaktan alın. Karışımı ve tereyağını  mercimeğe ilave edip 15 dakika daha pişirin. Son olarak krema ve garam masalayı  ekleyin. Kıyılmış taze kişniş ile süsleyerek servis yapın.  ", "500 gr yeşil mercimek\n" + "100 gr barbunya\n" + "100 gr tereyağı\n" + "75 ml krema\n" + "125 gr domates püresi\n" + "25 gr zencefil\n" + "3 diş sarımsak\n" + "10 gr garam masala\n" + "20 gr kırmızı toz biber\n" + "Tuz     "));
        tüm_yemekler.add(new Yemek("Murg Chatpata", "45 dk", "6 kişilik", R.drawable.murg, "Tavuk etlerini jülyen doğrayıp haşlayın. Soğan ve dolmalık biberi temizleyip jülyen doğrayın. Domatesin çekirdeklerini ayıklayıp jülyen doğrayın. Tüm malzemeleri bir kaseye alıp karıştırın. Kıyılmış taze kişniş ile süsleyip lavaş ekmeğine sararak servis yapın. ", "100 gr tavuk göğüs eti\n" + "3 soğan\n" + "2 domates\n" + "2 renkli dolmalık biber\n" + "10 gr kıyılmış taze kişniş\n" + "50 gr tatlı biber sosu\n" + "5 gr toz kırmızı biber\n" + "5 gr garam masala\n" + "Tuz  "));
        tüm_yemekler.add(new Yemek("Punjabi Samosa", "45 dk", "6 kişilik", R.drawable.punjabi, "Patatesleri küp şeklinde doğrayıp bol suda haşlayın. Bezelyeyi haşlayın. \n" + "\n" + "Sıvıyağın 1 çay bardağı kadarını bir tavada ısıtın. Kimyon, kişniş tohumu ve bezelyeyi ekleyip 5 dakika soteleyin. Toz kırmızıbiber, toz kişniş tuzu ekleyip sotelemeye devam edin. Patatesi ilave edip karıştırın. Limon suyu, garam masala ve taze kişnişi de ekleyip karıştırarak soğumaya bırakın. \n" + "\n" + "Hamur için, unu bir kaba eleyin. Tuz, yağ ve suyu ekleyip yoğurun. Hamuru 10 eşit yuvarlak parçaya ayırın. Her bir topu ortadan ikiye bölün. Açarak koni biçiminde parçalar elde edin. Parçalara iç malzemeyi bölüştürün. Hamurların uçlarını ıslatarak birleştirin.  \n" + "\n" + "Kalan yağı bir tavada ısıtıp iç malzemeyle dolu konileri kahverengileşinceye kadar kızartın. Sıcak ya da ılık servis yapın", "100 gr  patates\n" + "50 gr bezelye\n" + "5 gr kimyon\n" + "200 gr un\n" + "250 ml sıvıyağ\n" + "Tuz\n" + "5 gr gram masala\n" + "5 gr toz kırmızı biber\n" + "5 gr kişniş tohumu\n" + "10 gr toz kişniş\n" + "Yarım çay bardağı limon suyu\n" + "5 gr kıyılmış zencefil\n" + "1 su bardağı su"));

        //italya
        tüm_yemekler.add(new Yemek("Risotto Alla Pescatore", "45 dk", "4 kişilik", R.drawable.risottoalla, "Soğanları zeytinyağında kavurduktan sonra, üzerine pirinci ilave edip tekrar kavurun. Beyaz şarabı ekleyin. Beyaz şarabı çekince kepçe yardımı ile başka kapta kaynatılan balık suyunu azar azar yedirerek risottoyu pişirin. Pişmeye yakın karışık deniz mahsullerini ekleyip, 5-6 dakika daha pişirin. Fesleğen, kıyılmış maydanoz, tuz, karabiber ve zeytinyağını ekleyip akıcı bir risotto kıvamı olana kadar karıştırın. Risottoyu çukur veya hafif oval bir tabağa alıp, üzerine fesleğen ve ekstra sızma zeytinyağı ilave ederek servis yapın.", "280 gr risotto pirinci (Arborio tipi)\n" + "50 gr ince kıyılmış soğan\n" + "50 ml beyaz şarap\n" + "40 ml zeytinyağı\n" + "400 gr karışık kabuklu deniz mahsulleri (karides~vongole~midye~kalamar v.b. )\n" + "100 gr domates sos veya domates püresi\n" + "1 litre balık suyu\n" + "1/3 demet maydanoz\n" + "10 gr fesleğen\n" + "6 gr tuz\n" + "5 gr karabiber"));
        tüm_yemekler.add(new Yemek("Pasta", "30 dk", "4 kişilik", R.drawable.pasta, "Tencereye su doldurulup ocağın üzerinde kaynamaya bırakılır.\n" + "\n" + "Kaynayan suyun içerisine tuz ve makarnalar ilave edilip, makarnalar yumuşayıncaya kadar pişirilir.\n" + "\n" + "Makarnalar yumuşayınca ocaktan alınıp, süzgeç yardımı ile suyu süzülür.\n" + "\n" + "Makarnaların birbirine yapışmasını engellemek için, üzerine biraz soğuk su gezdirilir.\n" + "\n" + "Biber yıkanıp ortadan ikiye bölünür ve çekirdeği temizlenip doğranır.\n" + "\n" + "Doğranan biberler, 3 yemek kaşığı sıvı yağ içerisinde kavrulur.\n" + "\n" + "Üzerine sarımsak rendesi ve yarım yemek kaşığı salça ilave edilip, biraz kavrulur.\n" + "\n" + "Kabukları soyulup, küçük küp şeklinde doğranan domatesler ilave edilip, biraz pişirilir.\n" + "\n" + "Son olarak tuz, ince kıyılmış maydanoz ve baharatlar ilave edilip karıştırılır.\n" + "\n" + "Domatesli biberli sos içerisine, suyu süzülen makarnalar ilave edilip, güzelce karıştırılır.\n" + "\n" + "Hazırlanan domatesli biberli makarna, 2-3 dakika daha pişirilip, ocaktan alınır.\n" + "\n" + "Sıcak olarak servis edilir.", "Yarım paket makarna (250 gram),\n" + "2 adet domates,\n" + "1 adet biber,\n" + "3 yemek kaşığı sıvı yağ,\n" + "Yarım yemek kaşığı domates salçası,\n" + "1 tutam maydanoz,\n" + "1 diş sarımsak,\n" + "Pul biber,\n" + "Kuru nane,\n" + "Kekik,\n" + "Tuz."));
        tüm_yemekler.add(new Yemek("Tiramisu", "60 dk", "5 kişilik", R.drawable.tiramisu, "Öncelikle muhallebi için şeker, un, süt ve yumurta çırpılarak ocakta kaynayıncaya kadar karıştırılarak pişirilir. Kaynadıktan sonra altı kapatılarak ılımaya bırakılır. 15dk kadar bekleyip ılındıktan sonra labne peyniri ilave edilip mikser ile pürüzsüz hale gelene kadar çırpılır. Diğer taraftan sıcak su içinde hazır kahve çözdürülerek hazırlanır ve hafif soğuması beklenir. Servis tabağına pandispanya kekinin bir katı yerleştirilerek kahvenin yarısı ile ıslatılır. Üzerine kremanın yarısı ilave edilip kalan kahve ile üst kat da ıslatıldıktan sonra ikinci kat kapatılır. Kalan krema da dökülerek pastanın üzeri ve kenarları güzelce kapatılır. Son olarak pastanın üzerine süzgeç yardımı ile kakao serpilir. Buzdolabında birkaç saat dinlendirildikten sonra dilimlenerek servis edilir. ", "1 adet hazır pandispanya keki\n" + "\n" + "muhallebisi için;\n" + "2.5 su bardağı süt\n" + "3 yemek kaşığı toz şeker (tepeleme dolu)\n" + "3 yemek kaşığı un (tepeleme dolu)\n" + "1 adet yumurta\n" + "200 gram labne peyniri (1 paket)\n" + "\n" + "ıslatmak için;\n" + "1/2 su bardağı sıcak su\n" + "3’ü bir arada hazır kahve\n" + "\n" + "üzeri için;\n" + "kakao"));
        tüm_yemekler.add(new Yemek("Pizza", "80 dk", "6 kişilik", R.drawable.pizza, "Hamuru için; bir kaba mayayı, şekeri ve ılık sütü koyup karıştıralım.\n" + "\n" + "Bu şekilde 10 dakika bekletelim.\n" + "\n" + "Kabaran mayanın içine sıvı yağı, yumurtayı ve tuzu koyup iyice karıştıralım.\n" + "\n" + "Üzerine azar azar unu ilave edip yumuşak kıvamlı bir hamur yoğuralım.\n" + "\n" + "Hamurun üzerini kapatıp ılık bir ortamda 30 dakika mayalandıralım. Hamurumuz iki katına çıkmalı.\n" + "\n" + "Sosu için; salçayı, sıvı yağı, sarımsağı, kekiği, karabiberi ve tuzu koyup iyice karıştıralım.\n" + "\n" + "Yuvarlak bir tepsiyi ya da fırın tepsisini yağlayalım.\n" + "\n" + "Hamurun yarısını tepsiye alalım.\n" + "\n" + "Elimizi sıvı yağı ile yağlayıp hamuru nazik hareketlerle tepsiyi kaplayana kadar yayalım.\n" + "\n" + "Hamurun her yerine çatal ile delikler açalım. (pişerken kabarmaması için)\n" + "\n" + "Hazırladığımız hamurun üzerine hazırladığımız sostan sürelim.\n" + "\n" + "Rendelenmiş kaşarın yarısını sosun üzerine serpelim.\n" + "\n" + "Sonra üzerine sıra ile sucuğu, salamı, mantarı, çekirdekleri çıkarılmış zeytini, mısırı, ince ince doğradığımız sivri biberi ve domatesi yerleştirelim.\n" + "\n" + "Önceden ısıtılmış 200° fırında 20 dakika pişirelim.", "5 su bardağı un,\n" + "1 paket instant maya (10 gr),\n" + "1 yemek kaşığı toz şeker,\n" + "1,5 su bardağı ılık süt,\n" + "Yarım su bardağı sıvı yağı,\n" + "1 adet yumurta,\n" + "1 tatlı kaşığı tuz.\n" + "Sucuk,\n" + "Salam,\n" + "Mantar,\n" + "Zeytin,\n" + "Sivri biber,\n" + "Domates,"));
        tüm_yemekler.add(new Yemek("Cappaletti", "100 dk", "5 kişilik", R.drawable.cappaletti, "Hindi ve tavuk etlerini bir tencerede bol suyla haşlayın. Ayıklayıp didikleyin. Tereyağını bir tavada eritin. Etleri ekleyerek 2 dakikadan fazla olmamak şartıyla orta ateşte soteleyin. Sertleşmemesine ve kızarmamasına özen gösterin. Soğuması için büyük bir kaseye alın.  \n" + "\n" + "Jambonu çok ince doğrayın. Etler soğuduğunda peynir, hindistancevizi, tuz, biber ve yumurtayı bir kaşıkla iyice karıştırıp kenara ayırın. \n" + "\n" + "Yumurtaları çırpın. Una yavaş yavaş yedirerek tuzsuz ve yağsız bir hamur elde edin. Hamuru incecik açın. 5 cm genişliğinde uzun şeritlere ve sonra 5 cm’lik karelere bölün. Her parçanın içine bir çay kaşığı kadar malzeme koyup şekillendirerek kapatın. Hamurun yapışması için sık sık sütle ıslatın. \n" + "\n" + "Bir tepsiye mutfak bezi serip üzerine un serpin ve kestiğiniz hamurları dizip kuruması için bırakın. Kuruduktan sonra da buzdolabında 4 saat kadar dinlendirin. \n" + "\n" + "Büyük bir tencerede su kaynatın. Cappalettileri içine atın. Sık sık karıştırarak ağır ateşte 35 dakika pişirin. Ocaktan alıp süzün. Üzerine parmesan peyniri serpip servis yapın. ", "300 gr un\n" + "3 yumurta\n" + "1 fincan süt\n" + "İç malzeme\n" + "30 gr tuzsuz tereyağı\n" + "125 gr tavuk göğüs eti\n" + "125 gr hindi eti\n" + "150 gr dana jambon\n" + "30 gr parmesan peyniri\n" + "1 yumurta\n" + "Bir tutam hindistancevizi\n" + "Yarım çay kaşığı tuz\n" + "Yarım çay kaşığı beyaz biber"));
        tüm_yemekler.add(new Yemek("Lazanya", "65 dk", "5 kişilik", R.drawable.lazanya, "Geniş bir tavaya sıvı yağı alın. Küçük küçük doğradığınız soğanları ilave edin, biraz kavurduktan sonra üzerine kıymayı ilave ederek kavurmaya devam edin. Kıymalar yeterince kavrulunca doğradığınız sarımsakları ve kabuğunu soyup küp küp doğradığınız domatesleri de ilave edin ve orta ateşte 10 dakika kadar daha soteleyin. Üzerine salçayı ekleyerek kavurun ve yaklaşık 1 su bardağı sıcak su ekleyin. Tuzunu da ekledikten sonra ocaktan alıp soğumaya bırakın. Beşamel sos için tereyağı ve unu küçük bir tencereye koyun ve orta ateşte kavurun. Üzerine sütü azar azar ekleyin ve topaklanmaması için sürekli çırparak karıştırın. Muhallebi kıvamına gelince ocaktan alın.\n" + "Kıymalı sos ve beşamel sos hazırlandıktan sonra ısıya dayanıklı bir fırın kabını biraz yağlayın ve tabanına lazanya dizin. Lazanyaların üzerine biraz beşamel sos dökerek güzelce yayın. Ardından üzerine kıymalı harçtan dökün. Üzerine tekrar lazanya koyun. Bu işlemi malzemeleriniz bitene kadar devam ettirin. En üstteki lazanyalara tekrar beşamel sos dökün ve kaşar peyniri rendesi serpin. Lazanyaların yumuşaması için 10-15 dakika kadar bekletin.. Son olarak 180 derece fırında yaklaşık 15 dakika pişirin. Üzeri tamamen kızarınca dilimleyerek servis yapın.", "Yarım paket lazanya\n" + "300 g kıyma\n" + "2 adet  soğan\n" + "2 adet domates\n" + "2 yemek kaşığı salça\n" + "3 yemek kaşığı sıvı yağ\n" + "2 diş sarımsak\n" + "2 yemek kaşığı tereyağı\n" + "4 yemek kaşığı un\n" + "2 su bardağı süt"));

        //uzakdoğu
        tüm_yemekler.add(new Yemek("Siyah pirinç Pilavı", "50 dk", "4 kişilik", R.drawable.siyahpirinc, "Pirinci ılık suda 15-20 dakika beklettikten sonra yıkayıp süzün. Tereyağını tencerede eritin. Pirinç ve tuzu ekleyip hafif kavurduktan sonra sıcak suyu ilave edin. Tencerenin kapağını kapatın. Kaynamaya başlayınca ocağın altını kısıp suyunu çekene kadar pişirin. Üzerine kağıt havlu kapatıp demlenmeye bırakın. Limon kabuğu rendesiyle süsleyip sıcak servis yapın.", "2 su bardağı siyah pirinç\n" + "6 su bardağı sıcak su\n" + "45 g tereyağı\n" + "Tuz\n" + "Rendelenmiş limon kabuğu"));
        tüm_yemekler.add(new Yemek("Tempura", "20 dk", "2 kişilik", R.drawable.tempura, "Yumurta, un ve buzlu suyu bir kapta iyice çırpın. Karides, havuç, mantar, kabak ve taze soğanı unlu karışıma bulayın. Sıvıyağı derin bir tavada kızdırın. Önce havuç, mantar, kabak ve taze soğanı ardından karidesleri kızgın yağda kızartın. \n" + "\n" + "Kâğıt havlu üzerine alıp yağını süzdürün. Yanında soya sosuyla birlikte servis yapın.", "1 yumurta\n" + "1 su bardağı un\n" + "1 su bardağı buzlu su\n" + "3 temizlenmiş karides\n" + "1 uzun dilim havuç\n" + "3 dilim mantar\n" + "3 dilim kabak\n" + "1 temizlenmiş taze soğan\n" + "Soya sosu\n" + "Sıvıyağ"));
        tüm_yemekler.add(new Yemek("Sushi", "30 dk", "2 kişilik", R.drawable.sushi, "Japon pirincini bol suyla yıkayıp süzün. Özel tenceresine alıp hafif diri kalacak şekilde pişirin. Pirinçleri harmanlayıp soğutun. Pirinç sirkesi ve şekeri ekleyip tekrar harmanlayın. \n" + "\n" + "Pirinçten iki parmak kalınlığında ve bir parmak uzunluğunda köfte şeklinde parçalar hazırlayın. Pirinç köftelerinin üzerine aynı boyutlarda kesilmiş levrek, tonbalığı, somon veya karides yerleştirin. Servis tabağına dizdiğiniz sushileri zencefil turşusu, dilimlenmiş avokado, salatalık ve soya sosuyla birlikte servis yapın.", "100 gr Japon pirinci\n" + "1 çay bardağı pirinç sirkesi\n" + "1 tatlı kaşığı tozşeker\n" + "İnce somon dilimleri\n" + "Buharda pişmiş karides\n" + "İnce dilimlenmiş levrek ve tonbalığı\n" + "İnce dilimlenmiş salatalık ve avokado"));
        tüm_yemekler.add(new Yemek("Gyu Hire Teri", "20 dk", "1 kişilik", R.drawable.bonfile, "Ayçiçek yağını tavada kızdırın. Bonfileyi ekleyip iki taraflı pişirin. Mirin ve soya sosunu ekleyip et yumuşayıncaya ve sos koyulaşana kadar kısık ateşte pişirin. \n" + "\n" + "Beyaz lahana yaprağını kıyın. Et piştikten sonra dilimleyip servis tabağına alın. Eti, lahana, salatalık, domates ve dolmalık yeşilbiberle servis yapın.", "200 gr bonfile\n" + "2 çorba kaşığı ayçiçek yağı\n" + "Yarım su bardağı mirin (Japon şarabı)\n" + "2 çorba kaşığı soya sosu\n" + "2 dilim salatalık\n" + "2 dilim domates\n" + "2 halka kesilmiş dolmalık yeşilbiber\n" + "1 yaprak beyaz lahana"));
        tüm_yemekler.add(new Yemek("Nabeyaki Udon", "30 dk", "1 kişilik", R.drawable.udon, "Sebzeleri yıkayıp süzün. Pırasayı dilimleyin. Havucu uzunlamasına ortadan ikiye kesip tekrar enine ikiye kesin. Mantarların üzerine bıçakla çizgiler çizin. Çin lahasını iri parçalar şeklinde doğrayın. \n" + "\n" + "Soya yağını tavada kızdırıp sebzeleri soteleyin. Tavayı ocaktan alın. Balık suyunu 'nabe' adını verdikleri güveç kabına alıp ocakta ısıtın. Udonları ekleyip hafifçe yumuşayana kadar pişirin. Sebzeleri ekleyip 5-6 dakika daha pişirin. Üzerine 1 yumurtayı kırıp güveç kabını ocaktan indirin. Özel kaşığı ve kâsesi içinde servis yapın.", "3-4 ıspanak yaprağı\n" + "Yarım pırasa\n" + "Yarım havuç\n" + "2-3 shitake mantarı\n" + "1 yaprak Çin lahanası\n" + "2 çorba kaşığı soya yağı\n" + "190 gr udon (noodle veya erişte)\n" + "2 su bardağı balık suyu\n" + "1 yumurta"));


        txt_msg = (TextView) findViewById(R.id.txt_malzeme);
        txt_null= (TextView) findViewById(R.id.txt_null);
        txt_autocomplte1 = (AutoCompleteTextView) findViewById(R.id.autoCompleteTextView1);
        txt_autocomplte2 = (AutoCompleteTextView) findViewById(R.id.autoCompleteTextView2);
        txt_autocomplte3 = (AutoCompleteTextView) findViewById(R.id.autoCompleteTextView3);
        grid = (GridView) findViewById(R.id.grid);
        ara = (Button) findViewById(R.id.button);


        txt_autocomplte1.addTextChangedListener(this);
        txt_autocomplte2.addTextChangedListener(this);
        txt_autocomplte3.addTextChangedListener(this);

        txt_autocomplte1.setAdapter(new ArrayAdapter<String>(this, android.R.layout.simple_list_item_single_choice, malzemeler));
        txt_autocomplte2.setAdapter(new ArrayAdapter<String>(this, android.R.layout.simple_list_item_single_choice, malzemeler));
        txt_autocomplte3.setAdapter(new ArrayAdapter<String>(this, android.R.layout.simple_list_item_single_choice, malzemeler));


        ara.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                String mlz1 = txt_autocomplte1.getText().toString();
                String mlz2 = txt_autocomplte2.getText().toString();
                String mlz3 = txt_autocomplte3.getText().toString();

                bulunan = new ArrayList();
                Yemek yedek = new Yemek("", "", "", 0, "", "");
                for (int i = 0; i < tüm_yemekler.size(); i++) {
                    yedek = (Yemek) tüm_yemekler.get(i);
                    String[] parts = yedek.getMalzemeler().split("\n");
                    ArrayList sonuc = new ArrayList();
                    for (int l = 0; l < parts.length; l++) {
                        String[] parts2 = parts[l].split(" ");
                        for (int m = 0; m < parts2.length; m++) {
                            sonuc.add(parts2[m]);
                        }
                    }
                    int count = 0;

                    if (sonuc.contains(mlz1)) {
                        count++;
                    }
                    if (sonuc.contains(mlz2)) {
                        count++;
                    }
                    if (sonuc.contains(mlz3)) {
                        count++;
                    }


                    if (count > 1) {
                        bulunan.add(yedek);
                    }


                }


                if(bulunan.size()>2){
                    web=new String[3];
                    imageId=new int[3];
                    Yemek yedek2=(Yemek)bulunan.get(0);
                    web[0]=yedek2.getYemek_adi();
                    imageId[0]=yedek2.getYemek_img();
                    Yemek yedek3=(Yemek)bulunan.get(1);
                    web[1]=yedek3.getYemek_adi();
                    imageId[1]=yedek3.getYemek_img();
                    Yemek yedek4=(Yemek)bulunan.get(2);
                    web[2]=yedek4.getYemek_adi();
                    imageId[2]=yedek4.getYemek_img();
                }

                if(bulunan.size()==2){
                    web=new String[2];
                    imageId=new int[2];
                    Yemek yedek2=(Yemek)bulunan.get(0);
                    web[0]=yedek2.getYemek_adi();
                    imageId[0]=yedek2.getYemek_img();
                    Yemek yedek3=(Yemek)bulunan.get(1);
                    web[1]=yedek3.getYemek_adi();
                    imageId[1]=yedek3.getYemek_img();

                }
                if(bulunan.size()==1){
                    web=new String[1];
                    imageId=new int[1];
                    Yemek yedek2=(Yemek)bulunan.get(0);
                    web[0]=yedek2.getYemek_adi();
                    imageId[0]=yedek2.getYemek_img();
                }
                if(bulunan.size()!=0){
                    txt_null.setText("");
                    grid.setAdapter(new CustomGrid(yemek_ara.this, web, imageId));

                }
                if(bulunan.size()==0){
                    txt_null.setText("Uygun yemek bulunamadı :(");
                    grid.setAdapter(null);

                }
            }


        });



        grid.setOnItemClickListener(new AdapterView.OnItemClickListener() {

            @Override
            public void onItemClick(AdapterView<?> parent, View view,
                                    int position, long id) {

                Intent intent = new Intent(yemek_ara.this, Yemek_Bilgi.class);

                if(position==0){
                    Yemek ymk1= (Yemek)bulunan.get(position);

                    String[] yemek_bilgi=new String[5];
                    yemek_bilgi[0]=ymk1.getYemek_adi();
                    yemek_bilgi[1]=ymk1.getYapilisi();
                    yemek_bilgi[2]=ymk1.getMalzemeler();
                    int img=ymk1.getYemek_img();
                    intent.putExtra("yemek_bilgi",yemek_bilgi);
                    intent.putExtra("yemek_img",img);
                    startActivity(intent);
                }
                else if(position==1){
                    Yemek ymk2= (Yemek)bulunan.get(position);

                    String[] yemek_bilgi=new String[5];
                    yemek_bilgi[0]=ymk2.getYemek_adi();
                    yemek_bilgi[1]=ymk2.getYapilisi();
                    yemek_bilgi[2]=ymk2.getMalzemeler();
                    int img=ymk2.getYemek_img();
                    intent.putExtra("yemek_bilgi",yemek_bilgi);
                    intent.putExtra("yemek_img",img);
                    startActivity(intent);
                }
                else if(position==2){
                    Yemek ymk3= (Yemek)bulunan.get(position);

                    String[] yemek_bilgi=new String[5];
                    yemek_bilgi[0]=ymk3.getYemek_adi();
                    yemek_bilgi[1]=ymk3.getYapilisi();
                    yemek_bilgi[2]=ymk3.getMalzemeler();
                    int img=ymk3.getYemek_img();
                    intent.putExtra("yemek_bilgi",yemek_bilgi);
                    intent.putExtra("yemek_img",img);
                    startActivity(intent);
                }
            }
        });

    }



    @Override
    public void beforeTextChanged(CharSequence charSequence, int i, int i1, int i2) {

    }

    @Override
    public void onTextChanged(CharSequence charSequence, int i, int i1, int i2) {



    }

    @Override
    public void afterTextChanged(Editable editable) {

    }
}
