package com.example.arzu.finalproject;

import android.content.Intent;
import android.graphics.drawable.Drawable;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.AdapterView.OnItemSelectedListener;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;


public class yemek_turkiye extends AppCompatActivity {
    ListView liste;
    List marmara;
    List akdeniz;
LinearLayout layout;
    List ege;
    List güneydogu;
    List karadeniz;
    List icanadolu;
    List doguanadolu;


TextView textView;

    private static String[] yemek_türkiye = new String[] { "Lütfen yemek yöresi seçiniz!","Marmara Yöresi Yemekler",
            "Akdeniz Yöresi Yemekler","Ege Yöresi Yemekler","Güneydoğu Yöresi Yemekler","Karadeniz Yöresi Yemekler","İç Anadolu Yöresi Yemekler","Doğu Anadolu Yöresi Yemekler"};
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_yemek_turkiye);

         liste=(ListView)findViewById(R.id.listView);
         layout=(LinearLayout)findViewById(R.id.activity_yemek_turkiye);
         layout.setBackgroundResource(R.drawable.kasik);



        marmara = new ArrayList<>();
        marmara.add(new Yemek("Kemalpaşa Tatlısı","60 dk","6 kişilik",R.drawable.kemalpasa,"Şerbeti hazırlamak için su ve şekeri tencereye alıp kaynatın. Limon suyunu ekleyip 1-2 taşım daha kaynatın. Ocaktan alıp soğumaya bırakın. Tuzsuz taze beyaz peyniri rendeleyin. 2 kaşık unu daha sonra kullanmak üzere ayırın, " + "kalan unu elekten geçirerek geniş bir tepsiye alın. Ortasını havuç şeklinde açıp yumurta ve karbonat ekleyin." + " Oda ısısında yumuşatılmış 4 yemek kaşığı margarin ve peyniri ekleyip 3-4 dakika yoğurun." + " Hamuru 18 parçaya bölüp ayırdığınız una hafifçe bulayarak elinizde yuvarlayın." + " Hamur toplarını yağlanmış fırın tepsisine aralıklı olarak dizin. Önceden ısıtılmış" + " 180 dereceye ayarlı fırında pembeleşinceye kadar 20-25 dakika pişirin." + " Pişen hamurları ılık şerbete atıp yumuşayıncaya kadar yaklaşık 15 dakika kaynatın." + " Kevgirle alıp servis tabağına dizin." + " Soğuyunca rendelenmiş Hindistan cevizi ile süsleyip servis yapın.","2 su bardağı toz şeker\n" + "2 su bardağı su\n" + "2 tatlı kaşığı limon suyu\n" + "2 su bardağı un\n" + "Yarım tatlı kaşığı karbonat\n" + "2 yumurta\n" + "5 yemek kaşığı margarin\n" + "250 gr tuzsuz taze beyaz peynir"));
        marmara.add(new Yemek("Sebzeli Pilav","45 dk","6 kişilik",R.drawable.sebzelipilav,"Pirinci yıkayıp üzerini örtecek kadar suda 1 saat bekletin." + " Suyu süzüp pirinçleri birkaç kez yıkayın. 3 yemek kaşığı tereyağını tencerede eritip pirinci ekleyin ve kavurun. " + "Et suyunu ekleyin. Tuzla tatlandırın. Su kaynamaya" + " başladığında ateşi kısıp pirinçler yumuşayana kadar pişirin. Havuç, biber ve kabağı tavla zarı büyüklügünde doğrayın. Havucu kaynar suda 15 dakika," + " biberi 8 dakika, kabağı 5 dakika haşlayıp suyunu süzün. Sebzeleri kalan" + " tereyağıyla kavurun." + " Pilava ekleyip ezmeden harmanlayın. Sıcak servis yapın.","2.5 su bardağı baldo pirinç\n" + "3.5 su bardağı et suyu\n" + "4 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı tuz\n" + "1 küçük havuç\n" + "1 su bardağı haşlanmış bezelye\n" + "1 kabak\n" + "1 dolmalık yeşil biber"));
        marmara.add(new Yemek("Şaşa Şura","60 dk","4 kişilik",R.drawable.sasasura,"Soğanı soyup iri kıyın. Biberleri kalın halkalar şeklinde doğrayın. Domatesleri soyup küp şeklinde doğrayın. Fasulyeleri temizleyip ikiye bölün. Patates, kabak ve patlıcanları soyup küp şeklinde doğrayın. Sebzeleri bir kaba alıp karıştırın.\n" + " \n" + "Ayçiçeği yağını tencerede ısıtıp soğanı pembeleşinceye kadar kavurun. Biber ve domates ve bir çorba kaşığı ılık suda inceltilmiş salçayı ekleyip 12 dakika daha kavurun. Sebzeler, 1.5 su bardağı sıcak su, tuz ve karabiberi ilave edin. Bir taşım kaynatıp kısık ateşte 30 dakika kadar pişirin. Ilık veya soğuk servis yapın.", "500 gr taze fasulye\n" + "2 kabak\n" + "1 büyük kemer patlıcan\n" + "1 büyük patates\n" + "50 gr çarliston biber\n" + "1 soğan\n" + "1 kahve fincanı ayçiçeği yağı\n" + "1.5 su bardağı sıcak su\n" + "2 domates\n" + "2 çorba kaşığı domates salçası\n" + "Tuz\n" + "Karabiber"));
        marmara.add(new Yemek("Kaçamak","20 dk","6 kişilik",R.drawable.kacamak,"Suyu bir tencereye alıp kaynatın. Tuzunu ekleyip karıştırın. Mısır ununu azar azar eklerken tahta kaşıkla sürekli karıştırın. Kek hamuru kıvamına gelince tahta kaşığı 2-3 yerine batırıp 1 dakika daha pişirerek suyunu çektirin. Katılaşınca ocaktan alıp tepsiye boşaltın.\n" + "\n" + "Tereyağını bir tavada kızdırıp üzerine gezdirin. Tahta kaşıkla yedirerek iyice karıştırın. Kaşığın sırtı ile üzerini düzeltin. Lor peyniri serpiştirip sıcak olarak servis yapın.", "8 su bardağı su\n"+ "Aldığı kadar mısır unu\n"+ "20 gr tereyağı\n"+ "Tuz\n"+"Üzeri için: Lor peyniri"));
        marmara.add(new Yemek("Palamut Köftesi","35 dk","4 kişilik",R.drawable.palamutkofte,"Palamutu temizleyin. İyice yıkayıp süzgece alın. Soğanları soyun. 1 bütün soğan ve balığı tuzlu suda 20 dakika haşlayın. Balığı süzgece alıp soğutun. Derisini, siyah kısımlarını ve kılçıklarını ayıklayın. Beyaz etleri bir kaba alıp didikleyin.\n" + "\n" + "Kalan 2 soğanı rendeleyip suyunu sıkın. Patatesleri haşlayıp soyun ve rendeleyin. Maydanozu temizleyip kıyın. \n" + "\n" + "Soğan, patates, maydanoz, fıstık, kuşüzümü, 2 yumurta, 1 kaşık un, tuz, yenibahar ve karabiberi balığa ekleyip yoğurun. Elinizle uzun köfteler hazırlayın. Galeta ununa bulayıp sıvıyağda kızartın. Sıcak servis yapın.", "1 palamut\n"+ "3 soğan\n"+ "2 orta boy patates\n"+ "Yarım demet maydanoz\n"+ "1 kahve fincanı dolmalık fıstık\n"+ "1 kahve fincanı kuşüzümü\n"+ "2 yumurta1 çorba kaşığı yenibahar\n"+ "1 çorba kaşığı un\n"+ "Kızartma için sıvıyağ\n"+ "Galeta unu\n"+ "Tuz\n" + "Karabiber"));
        marmara.add(new Yemek("İnegöl Köftesi","30 dk","6 kişilik",R.drawable.inegol,"Kıymayı iyice yoğurup buzlukta 4 gün bekletin. Buzluktan çıkarıp buzu çözülünceye kadar oda ısısında bekletin. Bir kez daha kıyma makinesinden geçirip yoğurun. \n" + "Soğanı çok ince doğrayıp kıymaya ekleyin. Tuz ilave edip yoğurun. Küçük parçalar koparıp elinizde parmak şekli verin. Izgarada veya mangalda pişirip sıcak olarak servis yapın. ","Kıyma\n"+ "Soğan\n"+"Tuz"));
        marmara.add(new Yemek("Hoşmerim","35 dk","6 kişilik",R.drawable.hosmerim,"Peynire yumurta sarılarını ekleyip tahta kaşıkla karıştırın. Karışımı bir tencereye alıp tereyağını ilave edin. Azar azar un ekleyip tahta kaşıkla karıştırarak pişirin. Koyu kıvama geldiğinde şekeri ekleyip karıştırarak 10 dakika daha pişirin. \n" + "\n" + "Höşmerimi servis tabağına alın. İri çekilmiş ceviz içi ya da hindistancevizi ile süsleyip servis yapın.","500 gr tuzsuz taze peynir (yağlı) veya lor peyniri\n"+"2 yumurta sarısı\n"+ "1 su bardağı un\n"+"15 gr tereyağı\n" + "750 gr tozşeker\n"+ "Üzeri için: İri çekilmiş ceviz içi veya hindistan cevizi"));
        marmara.add(new Yemek("Kaysepi","45 dk","6 kişilik",R.drawable.kaysepi,"Kurutulmuş mürdüm eriğini yıkayıp tencereye alın. Bir miktar su ekleyip yumuşayana kadar pişirin. Suyunu süzün ve eriklerin çekirdeklerini çıkarın. Tencereye alıp 1 bardak kaynar su ekleyin. Üzerine şekeri ilave edip pişirin. \n" + "\n" + "Bir tavada tereyağını eritin. Erikleri servis tabağına alıp üzerine tereyağını gezdirin. Ceviz içi serpiştirip sıcak olarak servis yapın. ", "2 su bardağı kurutulmuş mürdüm eriği\n"+ "1 su bardağı su\n"+ "1.5 su bardağı tozşeker\n"+ "30 gr tereyağı\n"+ "1 çay bardağı çekilmiş ceviz içi"));
        marmara.add(new Yemek("Kabaklı Saroz Böreği","60 dk","6 kişilik",R.drawable.kabakli,"Böreğin iç harcı için, kabakların kabuğunu temizleyip rendenin iri yanıyla rendeleyin. Süzgece alıp suyunu süzün. Yumurta, lor peyniri, tuz, karabiber ve pul biber ekleyip karıştırın. Yufkalaradan ilkini geniş düz bir zemine yayın. Su ve ayçiçeği yağını bir kasede iyice çırpın. Yufkanın üzerine fırçayla sürün. İç harçtan paylaştırıp rulo şeklinde sarın. Bir kenarı sabitleyip diğer kenarı çevresinde sararak şekil verin. Tüm malzemeyi aynı şekilde hazırlayın. Kapaklı bir kabın içine börekleri dizip buzdolabında bir gece bekletin. Fırın tepsisine dizip üzerine yağlı su sürün. Önceden ısıtılmış 180 derece fırında 35 dakika pişirin. Ilık servis yapın.","3 hazır yufka\n" + "Sos için:\n" + "\n" + "1 kahve fincanı ayçiçeği yağı\n" + "1 kahve fincanı su\n" + "İç harcı için:\n" + "\n" + "2 orta boy kabak\n" + "1 yumurta\n" + "1 su bardağı lor peyniri\n" + "1 çay kaşığı tuz\n" + "Karabiber\n" + "Kırmızı pul biber"));
        marmara.add(new Yemek("Köbete","70 dk","8 kişilik",R.drawable.kobete,"Unu hamur yoğurma kabına alıp ortasını havuz gibi açın. Tuz, yumurta ve mayayı ilave edip azar azar su ekleyerek kulak memesi yumuşaklığında bir hamur yoğurun. Hamuru ılık ortamda 15 dakika dinlendirin. \n" + "\n" + "Tavuk göğüs etini tencereye alıp 3 bardak su ile haşlayın ve tel tel ayırın. Tavuk suyunu daha sonra kullanmak üzere muhafaza edin. \n" + "\n" + "Soğanları piyazlık doğrayıp sıvıyağda pembeleştirin. Sivri biberleri ve domatesleri doğrayıp soğana ekleyin, 5 dakika pişirin. Tavuk göğüs etini, tuz ve karabiberi ilave edip ateşten alın. \n" + "\n" + "Hamuru iki eşit parçaya ayırıp merdaneyle tepsi büyüklüğünde açın. Bir parçasını tepsiye yerleştirip iç malzemeyi üzerine yayın. Diğer hamuru üzerine kapatın. Yumurta sarısı ile sıvıyağı karıştırıp hamurun üzerine sürün. Önceden ısıtılmış 180 dereceye ayarlı fırında üzeri pembeleşinceye kadar pişirin. Fırından alıp börek sıcakken üzerine tavuk suyunu gezdirerek dökün. Suyunu çekince dilimleyip sıcak olarak servis yapın.", "Hamur malzemesi:\n"+ "4 su bardağı un\n"+ "1 yumurta\n" + "1 su bardağı su\n" + "1 çay kaşığı toz maya\n" + "Tuz\n " + "İç malzemesi: 1 tavuk göğüs eti\n" + "3 su bardağı su\n " + "3 soğan\n " + "3 sivri biber\n " + "1 domates\n " + "Yarım çay bardağı sıvıyağ\n" + "Tuz\n" + "Karabiber\n"+ "Üzeri için: 1 yumurta sarısı\n"+ "1 çorba kaşığı sıvıyağ"));



//
        akdeniz = new ArrayList<>();
        akdeniz.add(new Yemek("Sini KÖfte","70 dk","4 kişilik",R.drawable.sini,"Köftenin dış harcı için çiğ köftelik kıyma, ince bulgur, un, rendelenmiş soğan, kırmızı toz biber, tuz, karabiber ve yeteri kadar suyu bir kasede karıştırın. Köftenin iç harcı için, soğanların kabuğunu soyup kıyın. Kıymayı Bizim Yağ Margarinle hafifçe kavurun. Soğanı ekleyip kavurmaya devam edin. Karabiber ve yenibahar ile tatlandırın. Kıymayı ocaktan alıp iri kırılmış ceviz ve Antep fıstığını ekleyin. Harcı ılınmaya bırakın. Köftenin dış harcının yarısını Bizim Yağ Margarin ile yağlanmış 30-35 santim çapında bir tepsiye elinizle bastırarak yayın. Üzerine iç harcı ekleyip kaşığın tersiyle üzerini düzeltin. Kalan bulgurlu harcı üzerine ekleyip çok düzgün olacak şekilde kaşığın tersiyle düzleyin. Keskin bir bıçağı soğuk suya batırarak tepsideki köfteyi kare şeklinde kesin. Bizim Yağ Margarini hafifçe eritip köftenin üzerine sürün. Önceden ısıtılmış 200 derece fırında 30-35 dakika pişirin. Köftenin yumuşak olması için fırından çıkardıktan sonra üzerine biraz su serpip tepsinin üstünü kapatın. Frenk soğanıyla süsleyerek sıcak servis yapın.","350 çiğ köftelik kıyma\n" + "4 subardağı köftelik ince bulgur\n" + "2 yemek kaşığı un\n" + "1 rendelenmiş soğan\n" + "2 yemek kaşığı kırmızı toz biber\n" + "1 tatlı kaşığı tuz\n" + "1 tatlı kaşığı karabiber\n\n" + "Yoğurmak için\n" + "Yeterikadar su\n\n" + "İç harcı için\n" + "30g BizimYağ Margarin\n" + "500 yağlı kıyma\n" + "3 soğan\n" + "1 su bardağı ceviz içi\n"+ "Yarımsu bardağı Antep fıstığı içi\n" + "Tuz\n" +"1’er çay kaşığı karabiber ve yenibahar\n\n" + "Üzeri için\n" + "\n" + "30g BizimYağ Margarin\n" + "Frenk soğanı"));
        akdeniz.add(new Yemek("Söğürme","50 dk","6 kişilik",R.drawable.sogurme,"Patlıcanları yıkayıp kurulayın. Közleyip kabuğunu soyun. İçini parmak kalınlığında doğrayın. Soğanı küp şeklinde doğrayıp zeytinyağında hafifçe kavurun. Küp doğranmış domatesi ekleyip kavurmaya devam edin. Çekirdekleri çıkarılmış ve ince uzun parçalar şeklinde doğranmış kırmızıbiberi ekleyip Birkaç dakika kavurduktan sonra patlıcan, tuz ve şekeri ilave edin. Sarımsakları kıyıp ekleyin. 1 çay bardağı suyu ilave edip pişirin. Suyu tamamen azalınca üzerine kıyılmış maydanoz serpip servis yapın.","2 bostan patlıcanı\n" + "2 domates\n" + "1 soğan\n" + "1 salçalık kırmızıbiber\n" + "2 sivri biber\n" + "Yarım çay bardağı zeytinyağı\n" + "2 kesme şeker\n" + "2 diş sarımsak\n" + "Tuz\n" + "Kırmızı pul biber\n" + "Kıyılmış maydanoz"));
        akdeniz.add(new Yemek("Adana Avgan Pilavı","40 dk","6 kişilik",R.drawable.adana,"Küçük parçalar şeklinde doğranmış eti ve kıyılmış soğanı tencereye alıp bıraktığı suyu çekene kadar kavurun. Kıyılmış havuç ve bol suyla yıkanmış pirinci ekleyip birkaç dakika daha kavurun. Tuzla tatlandırın. Yenibahar ekleyip pirincin üzerini geçecek kadar kaynar su ekleyip bir kez karıştırın. Tencerenin kapağını kapatıp ateşi kısın. Kısık ateşte pilav suyu çekene kadar pişirin. 10 dakika demlendirip servis yapın.","1 kg parça et\n" + "2 soğan\n" + "250 ml ayçiçeği yağı\n" + "500 gr baldo pirinç\n" + "Sıcak su\n" + "1 kg havuç\n" + "1 tatlı kaşığı yenibahar\n" + "Tuz"));
        akdeniz.add(new Yemek("Peynirli İrmik Helvası","45 dk","6 kişilik",R.drawable.peynirliirmik,"Su ve şekeri tencereye alıp kaynatın. 1 tatlı kaşığı tereyağını tavaya alıp eritin. İrmiği ekleyip rengi hafifçe değişene kadar kavurun. Şekerli suyu ekleyip kısık ateşte su azalana ve irmik yumuşayana kadar pişirin. İnce parçalar şeklinde doğranmış peyniri ekleyin. 2-3 dakika daha pişirin tencereyi ocaktan alın. Kalan tereyağını ekleyip yavaşça karıştırın. Üzerine kavrulmuş çam fıstığı ekleyip servis yapın.","1 su bardağı irmik\n" + "3 su bardağı su\n" + "2 su bardağı toz şeker\n" + "300 gr tuzsuz beyaz peynir\n" + "2 yemek kaşığı tereyağı\n" + "Kavrulmuş çam fıstığı"));
        akdeniz.add(new Yemek("Testi Kebabı","60 dk","6 kişilik",R.drawable.testi,"İri parçalar şeklinde kesilmiş eti yıkayıp süzün. Eti büyük bir kabın içine alın. Arpacık soğanların kabuğunu soyup ete ekleyin. Domatesleri, biberleri iri parçalar şekline doğrayıp malzemeye ekleyin. Salça, tuz, kimyon, karabiber ve ayçiçeği yağını ilave edip karıştırın. Hazırladığınız harcı toprak testiye doldurun. Testinin ağız kısmını hazırladığınız bir hamurla sıkıca kapatın. Sıcak fırında 1.5 saat pişirin. Fırından alıp 20 dakika dinlendirin. Hamuru çıkarıp kebabı servis tabaklarına paylaştırın. Sıcak servis yapın.","1.5 kg orta yağlı koyun eti\n" + "2 yemek kaşığı ayçiçeği yağı\n" + "1 kg arpacık soğan\n" + "Yarım yemek kaşığı domates salçası\n" + "2 büyük domates\n" + "Sivri biber\n" + "Defne yaprağı\n" + "Tuz\n" + "Kimyon\n" + "Karabiber"));
        akdeniz.add(new Yemek("Kabune","50 dk","8 kişilik",R.drawable.kabune,"Soğanı temizleyip halka halka doğrayın. Tuz ve biberle ovup yıkayın. Pirinci ılık suda 10-15 dakika bekletin ve yıkayıp süzün. Eti haşlayıp tel tel ayırın.\n" + "\n" + "Bir tencereye sırasıyla soğan, et ve pirinci yerleştirin. Tuz ve karabiber serpin. Üzerine bir porselen tabak kapatın. Tabağın hizasına kadar kaynar et suyu ilave edin. Kapağı kapalı olarak 25 dakika pişirin. 5-10 dakika dinlendirin. Servis tabağına ters çevirip sıcak olarak servis yapın.","1 kg pirinç\n" + "500 gr kemiksiz et\n"+"3 soğan\n"+"2 çorba kaşığı margarin\n"+"Kaynar et suyu\n"+"Tuz\n"+"Karabiber"));
        akdeniz.add(new Yemek("Samsa Tatlısı","65 dk","6 kişilik",R.drawable.samsa,"Bir kapta badem, şeker ve yumurta akını karıştırın. Milföy hamurunu 2 mm kalınlığında açıp hazırladığınız bademli karışımı ortasına uzunlamasına yayın. Hamuru rulo şeklinde sarıp bir tepsiye alın ve 45 dakika dinlendirin. Küçük parçalar halinde kesip önceden ısıtılmış 180 dereceye ayarlı fırında 40 dakika pişirin.\n" + "\n" + "Bir tencerede şeker, su ve limonu kaynatıp şerbet hazırlayın. Fırından aldığınız sıcak hamurun üzerine sıcak şerbeti gezdirerek dökün. Tatlı şurubu çekince ılık ya da soğuk olarak servis yapın.","200 gr milföy hamuru\n"+"Yarım su bardağı toz badem\n"+"2 çorba kaşığı tozşeker\n"+"1 yumurta akı\n"+"Şerbet için:\n"+"3.5 kahve fincanı tozşeker\n"+"2 çay bardağı su\n"+"Yarım limon"));
        akdeniz.add(new Yemek("Kaymaklı Künefe","50 dk","8 kişilik",R.drawable.knefe,"Şurup için; şeker ve suyu bir tencerede kaynatın. Limon suyunu ilave edip bir taşım daha kaynatın. Tencereyi ocaktan alıp ılınmaya bırakın.\n" + "\n" + "Küçük bir tavada tereyağını eritip ılıtın. Kadayıfı tepsiye yayıp yağı üzerine gezdirin. Kadayıfı elinizle tel tel ayırarak ve ovuşturarak tereyağını iyice yedirin. Kadayıfı 2 ayrı tepsiye paylaştırıp elinizle bastırarak yerleştirin. Tepsileri ocağa alın ve kısık ateş üzerinde sürekli çevirerek kadayıfın altını kızartın. Her ikisini de ocaktan alıp birinin üzerine kaymağı yayın. Diğer kadayıfı kızarmış tarafı üste gelecek şekilde kaymağın üzerine alın. \n" + "\n" + "Ilık şerbeti sıcak kadayıfın üzerine gezdirerek dökün. Antepfıstığı serpin. Dilimleyip servis yapın.","1 kg kadayıf\n"+"800 gr kaymak\n"+"300 gr tereyağı\n"+"100 gr ince çekilmiş antepfıstığı\n"+"Şurup için:\n"+"1 kg tozşeker\n"+"3 su bardağı su\n"+"1 çorba kaşığı limon suyu"));
        akdeniz.add(new Yemek("Pirzolalı Yaprak Sarma","85 dk","6 kişilik",R.drawable.pirzola,"Bir tencereye su doldurup tuz ve yarım limonun suyunu ekleyin. Ocağa alıp su kaynamaya başlayınca yaprakları ilave edip 5 dakika haşlayın ve süzgece alın. \n" + "\n" + "Soğan ve sarımsağı temizleyin. 2 diş sarımsak ve soğanı rendeleyin. Pirinci iyice yıkayıp süzün. Bir kapta pirinç, kıyma, salça, yağ, soğan, sarımsak, tuz ve karabiberi karıştırın. Hazırladığınız malzemeyi yapraklara sarın. \n" + "\n" + "Pirzolaları tuzlayıp biberleyin ve yayvan bir tencerenin tabanına dizin. Yaprak sarmaları pirzolaların üzerine yerleştirin. Kalan sarımsakları bütün olarak ilave edin. 1.5 bardak sıcak su ekleyip üzerine porselen bir tabak kapatın. 30 dakika pişirip üzerindeki tabağı alın. 1 limonun suyunu yemeğin üzerine gezdirin ve kısık ateşte 15 dakika daha pişirin. Sıcak olarak servis yapın.","750 gr taze asma yaprağı\n"+"500 gr pirzola\n"+"400 gr az yağlı koyun kıyması\n"+"2.5 su bardağı pirinç\n"+"3 çorba kaşığı sıvıyağ\n"+"1 soğan\n"+"4-5 diş sarımsak\n"+"1 çorba kaşığı salça\n"+"1.5 çay bardağı su\n"+"1.5 limon\n" +"Tuz\n" + "Karabiber"));
        akdeniz.add(new Yemek("Uluborlu Böreği","40 dk","8 kişilik",R.drawable.uluborlu,"Eti soğanla birlikte robotta çekin ya da satırla kıyın. Tuz, karabiber ve çok az su ilave edip yoğurun. \n" + "\n" + "Yufkayı dörde kesin. Her bir üçgenin ortasına bir miktar et yerleştirip bohça şeklinde kapatın. Malzeme bitinceye kadar işleme devam edin. \n" + "\n" + "Sacı ısıtın. Börekleri önlü arkalı pişirip tereyağı ile yağlayın. Kıyılmış maydanoz serpip servis yapın.","500 gr kemiksiz et\n"+"2 soğan\n"+"4 yufka\n"+"2 çorba kaşığı tereyağı\n"+"2-3 dal maydanoz\n"+"Tuz\n" + "Karabiber"));

        ege = new ArrayList<>();
        ege.add(new Yemek("İzmir Köfte","60 dk","6 kişilik",R.drawable.izmirkofte,"Kıymayı yoğuracağınız kaba alın. Soğanı rendenin ince tarafı ile rendeleyin. Ekmekleri ıslatarak içini ufalayın. Kıyılmış maydanoz, tuz ve karabiberi ilave edip iyice yoğurun. Kıymalı harcı 18 parçaya ayırarak parmak şeklinde köfteler hazırlayın. Patatesleri soyup yıkayın ve elma dilimi şeklinde dilimleyin. Ayçiçeği yağında 2 yemek kaşığı kadar ayırın ve kalanını tavada kızdırın. Önce patatesleri, sonra köfteleri, en son olarak da sivri biberleri hafif pembeleşene kadar kızartın. 2 domatesi yıkayın. Kabuğunu soyup küp halinde doğrayın. Doğradığınız domateslerin bir kısmını fırın kabına yayın. Üzerine kızartmış olduğunuz köfte ve patatesleri arzu ettiğiniz biçimde sıralayın. Kalan domatesi de dilimleyip malzemenin üzerine ekleyin. Salçayı da 1 çay bardağı su ile ezip yemeğin üzerine gezdirin. Tavada hafif kızarttığınız sivri biberleri de malzemenin üzerine yerleştirin. Tuz ve tane karabiberi ilave edin. Tereyağını minik parçalar halinde malzemenin üzerine serpiştirin. Kalan ayçiçeği yağından 2 yemek kaşığı yemeğin üzerine gezdirin. 200 derece fırında yaklaşık 25 dakika kadar pişirin. Sıcak servis yapın.", "Malzemeler\n" + "\n" + "4 orta boy patates\n" + "6 sivri biber\n" + "3 orta boy domates\n" + "1 tatlı kaşığı domates salçası\n" + "Yarım çay kaşığı tane karabiber\n" + "1 tatlı kaşığı kaşığı tereyağı\n" + "1 su bardağı ayçiçek yağı (kızartmak için)\n" + "1 çay kaşığı tuz\n\n" + "Köfte için\n" + "\n" + "500 gr dana kıyma (az yağlı)\n" + "1 soğan\n" + "3 dilim bayat ekmek içi\n" + "1 çay kaşığı tuz\n" + "1 çay kaşığı karabiber\n" + "1 tutam maydanoz"));
        ege.add(new Yemek("Tahinli Kabak Tatlısı","50 dk","6 kişilik",R.drawable.kabak,"Kabakların kabuğunu soyup ince uzun parçalar şeklinde dilimleyin. Dikdörtgen fırın kabına kabakları yerleştirin. Üzerine şekeri serpin. Üzerini streç filmle kapatıp buzdolabında bir gece bekletin. Ertesi gün üzerini yağlı kağıt ile örterek 160 dereceye ayarlı fırında yaklaşık 25-30 dakika pişirin. Soğuyunca üzerine tahin gezdirin. Ceviz ile süsleyip servis edin.", "1.5 kg kabuğu soyulmuş bal kabağı\n" + "3 su bardağı toz şeker\n" + "1.5 çay bardağı tahin\n" + "1.5 çay bardağı iri çekilmiş ceviz içi"));
        ege.add(new Yemek("Çingene Pilavı","20 dk","6 kişilik",R.drawable.cingene,"Tulum çökeleğini bir kabın içine alıp ufalayın. Domates, biber ve soğanı küçük doğrayıp çökeleğe ekleyin. Maydanozu kıyıp ekleyin. Zeytinyağı ve çok az tuz ekleyip karıştırın. Servis yapın.", "1 kg tulum çökeleği\n" + "2 soğan\n" + "3 domates\n" + "4 sivri biber\n" + "Yarım demet maydanoz\n" + "3 yemek kaşığı zeytinyağı\n" + "Tuz"));
        ege.add(new Yemek("Tekke Çorbası","50 dk","4 kişilik",R.drawable.tekke,"Unu hamur yoğurma kabına alıp tuzla harmanlayın. Ortasını havuz gibi açıp yumurtayı ekleyin. Suyu azar azar ilave edip kulak memesi yumuşaklığında pürüzsüz bir hamur elde edin. Unlanmış zeminde hamuru merdane ile açın. 1?er santimlik kareler halinde kesin.\n" + "\n" + "Soğanı temizleyip rendeleyin. Margarini tencerede kızdırıp soğanı ve kıymayı kavurun. Domates ve biber salçaları ekleyip karıştırın. Sıcak suyu ekleyin. Su kaynamaya başlayınca hamurları ilave edin. Tuz, karabiber ve kuru nane ile tatlandırın.\n" + "\n" + " Servis kâselerine paylaştırıp üzerini nane ile süsleyin. Sıcak olarak servis yapın.", "100 gr kıyma\n"+ "1 çorba kaşığı margarin\n"+"1 tatlı kaşığı domates salçası\n"+"1 çay kaşığı biber salçası\n"+"1 soğan\n"+"1 çay kaşığı kuru nane\n"+"5 su bardağı sıcak su\n"+"Tuz\n" +"Karabiber\n"+"Hamur için:\n"+"1 su bardağı un\n"+"1 yumurta\n"+"3 çay bardağı su\n"+"Tuz"));
        ege.add(new Yemek("Boyoz","50 dk","4 kişilik",R.drawable.boyoz,"Kabaklı iç malzeme için; patlıcanı soyup tuzlu suda bekletin. Domates, kabak ve soğanın kabuklarını soyun. Patlıcanın suyunu sıkıp kâğıt havlu ile kurulayın. Sebzeleri rendeleyin. Tavada sıvıyağı kızdırıp tuz ekleyerek sebzeleri suyunu salıp çekinceye kadar soteleyin. Patatesli iç malzeme için; patatesleri haşlayın. Kabuklarını soyup çatalla ezin. Yumurta, tulum ve kaşarpeynirini ekleyip karıştırın.\n" + "\n" + "Unu yoğurma kabına alın. Ortasını havuz gibi açıp su, sirke, limon suyu, 1 tatlı kaşığı mısırözü yağı ve tuzu ekleyin ve 10-15 dakika kuvvetlice yoğurun. Derin bir kaba 1 bardak mısırözü yağı ekleyin. Yumuşak kıvamlı hamurdan ceviz büyüklüğünde parçalar koparıp 10 dakika bekletin. \n" + "\n" + "Hamur topağını yağdan alıp elle, katmer hamuru inceliğinde yuvarlak açın. Ortasına kabaklı iç malzemeden 1 kaşık yayıp 4 köşesi ortaya gelmek üzere katlayın. Hamurların yarısını kabaklı, yarısını da patatesli iç malzemeyle hazırlayıp hafif yağlanmış tepsiye dizin. Önceden ısıtılmış 200 dereceye ayarlı fırında 20 dakika pişirin. Sıcak olarak servis yapın.", "2 su bardağı un\n"+"1 su bardağı su\n"+"1 tatlı kaşığı sirke\n"+"1 tatlı kaşığı limon suyu\n"+"1 tatlı kaşığı mısırözü yağı\n"+"Yarım tatlı kaşığı tuz\n"+"Kabaklı iç malzeme:\n"+"2 kabak\n"+"1 patlıcan\n"+"1 soğan\n"+"1 domates\n"+"2 çorba kaşığı sıvıyağ\n"+"Tuz\n"+"Patatesli iç malzeme:\n"+"2 patates\n"+"2 yumurta\n"+"1.5 kahve fincanı tulum peyniri\n"+"1 kahve fincanı rendelenmiş kaşar peyniri"));
        ege.add(new Yemek("Kuru Börülce Çorbası","40 dk","6 kişilik",R.drawable.brlce,"Kuru börülceyi haşlayıp suyunu süzün. Tencereye alıp 5 su bardağı su ekleyin ve yumuşayıncaya kadar pişirin. Pirinci yıkayıp süzün ve börülceye ilave edin. \n" + "\n" + "Tavada tereyağını kızdırıp salçayı ekleyin. Tuz serpip kaşıkla ezerek kavurun. Pirinçler pişince tencereye salçalı sosu ekleyip 1-2 dakika daha kaynatın. Sıcak olarak servis yapın.","1 su bardağı kuru börülce\n"+"5 su bardağı su\n"+"1 kahve fincanı pirinç\n"+"1 çorba kaşığı tereyağı\n"+"1 çorba kaşığı salça\n"+"Tuz"));
        ege.add(new Yemek("Çaput Aşı","75 dk","4 kişilik",R.drawable.caput,"Pirinci 15 dakika soğuk suda bekletip nişastası gidene kadar soğuk suyla yıkayın ve suyunu süzün. Tereyağını tencerede eritip pirinci kavurun. Başka bir tencerede kuzu etini tuz, kimyon ve karabiber ile tatlandırarak kavurun. Koruk suyu (yeşil üzüm suyu), ince doğranmış asma yaprağı ve ets uyunu ilave edip kaynatın. Pirinci ekleyip suyunu çekinceye kadar kısık ateşte pişirin. Sıcak servis yapın.", "3 su bardağı baldo pirinç\n" + "4 su bardağı sıcak et suyu\n" + "100 gr tereyağı\n" + "150 ml koruk suyu\n" + "300 gr kuzu eti\n" + "30 taze asma yaprağı\n" + "Tuz\n" + "Karabiber\n" + "Kimyon"));
        ege.add(new Yemek("Sütlü İncir Tatlısı","40 dk","4 kişilik",R.drawable.incir,"İncirleri yıkayıp iri iri doğrayın. 1 çay bardağı su ile incirler yumuşayana kadar pişirin. Süte nişastayı ilave edip sürekli karıştırarak muhallebi kıvamına gelene kadar pişirin.\n" + "\n" + "Tozşeker ve incirleri ekleyip karıştırarak 5 dakika daha pişirin. Servis kâselerine paylaştırıp soğumaya bırakın. Üzerini antepfıstığı ile süsleyip soğuk olarak servis yapın.", "1 kg süt\n"+"10 kuru incir\n"+"1 kahve fincanı nişasta\n"+"3 kahve fincanı tozşeker\n"+"4 çorba kaşığı çekilmiş antepfıstığı"));
        ege.add(new Yemek("Etli Ekmek Dolması","55 dk","6 kişilik",R.drawable.etliekmek,"Ekmeğin bir ucunu keserek kapak şeklinde açın. Kaşık yardımıyla içini çıkarıp bir kaba ufalayın. Taze soğanları temizleyip kıyın. Sarımsakları soyup ezin. Dereotu veya maydanozu temizleyip kıyın.\n" + "\n" + "Kuşbaşı eti tencereye alın. 1 fincan su ilave ederek suyunu çekinceye kadar pişirin. 1 fincan su daha ekleyip kapağı kapalı olarak pişirin. Gerekirse 1 fincandan fazla olmamak kaydıyla su ekleyip pişirmeye devam edin. Et suyunu çekince tencereyi ocaktan indirin.\n" + "\n" + "Geniş bir tavada zeytinyağını ısıtın. Taze soğanları ekleyip hafif sarartın. Ekmek içi, sarımsak, salça, tuz ve baharatları ekleyip 2-3 dakika kavurun. Kuşbaşı et, dereotu veya maydanozu ilave edip karıştırın ve tavayı ocaktan alın.\n" + "\n" + "İç malzemeyi bir kaşıkla hiç boşluk bırakmayacak şekilde ekmeğin içine doldurun. Çıkardığınız kapağı ağzına kapatın. Büyük bir tencereye ısıya dayanıklı bir kâseyi ters yerleştirin. Ekmeği kâsenin üzerine oturtun. Kâsenin seviyesini geçmeyecek kadar su ekleyin. Kapağı kapalı olarak orta ateşte 15-20 dakika pişirin. Ekmeği tencereden alıp dilimleyerek servis yapın.", "1 bayat çavdar ekmeği\n"+"500 gr kuşbaşı kuzu eti\n"+"2 kahve fincanı sıcak su\n"+"6 taze soğan\n"+"1 kahve fincanı zeytinyağı\n"+"2 diş sarımsak\n"+"1 tatlı kaşığı domates salçası\n"+"1 demet maydanoz veya dereotu\n"+"Tuz\n" + "Karabiber\n" + "Kırmızı pulbiber"));
        ege.add(new Yemek("Kırlı Patlıcan Kızartması","40 dk","8 kişilik",R.drawable.kirlipatlican,"Patlıcanları saplı olarak alaca soyup bol tuzlu suda yarım saat bekletin. Bol suyla yıkayıp kurulayın. Sapı üzerinde kalacak ve kopmayacak şekilde uzunlamasına kesin. Kızgın ayçiçeği yağında kızartın. Soğanların ve sarımsakların kabuğunu soyup soğanları küçük doğrayın. Sarımsakları bütün olarak bırakın. Domateslerin kabuğunu soyup küp şeklinde doğrayın. Soğan ve domatesi çok az yağ eklenmiş tavada kavurun. Kızarttığınız patlıcanların üzerine yayın. Üzerlerine parmak uzunluğunda doğradığınız biberler, sarımsaklar ve tuz ilave edin. 180 derece fırında yarım saat pişirin. Ilık servis yapın.","1.5 kg patlıcan\n" + "1 litre ayçiçeği yağı\n" + "1.5 kg domates\n" + "500 gr soğan\n" + "2 baş sarımsak\n" + "1 kg sivri biber\n" + "Tuz"));

        //eklemeler yapılacak buraya.
        güneydogu = new ArrayList<>();
        güneydogu.add(new Yemek("Katmer","30 dk","2 kişilik",R.drawable.katmer,"Su ve tuzu geniş bir kaba alarak tuz tamamen eriyinceye kadar elinizle karıştırın. Unu azar azar ekleyerek kulak memesi kıvamında bir hamur elde edinceye kadar yoğurun. Hamuru sekiz eşit bezeye ayırıp üzerini nemli bir bezle örtün ve bir gün dinlendirin. Ertesi gün, dinlenen bezeleri üzerlerine nişasta serperek incecik olacak şekilde açın. Her birinin üzerine erittiğiniz 100 g Bizim Yağ’dan sürün. Üzerine kaymak parçaları ilebir kasede karıştırdığınız toz şeker ve Antep fıstığından serpip yufkayı kare şeklinde katlayın. Yapışmaz tavayı ısıtıp katmerlerin her iki yüzünü kızartın. Kaymak ve toz Antep fıstığı ile süsleyerek servis yapın.", "Hamuru için\n"+ "100 g Bizim Yağ\n" + "200 ml su\n" + "2~3 su bardağı un\n" + "1 çay kaşığı tuz\n" +  "\n" + "Açmak için\n" + "Nişasta\n" + "\n"+ "Arası için\n" + "250 gr kaymak\n" + "10 yemek kaşığı toz şeker\n" + "10 yemek kaşığı toz Antep Fıstığı\n" +  "\n"+ "Üzeri için\n" + "Toz Antep fsıtğı\n" + "Kaymak"));
        güneydogu.add(new Yemek("Soğan Kebabı","70 dk","2 kişilik",R.drawable.sogankebap,"Soğanların kabuklarını soymadan uç kısımlarını kesin. Her birini üstten alt kısmını koparmayacak şekilde derin kesin. Bir kasede kıyma, tuz, karabiber ve salçayı yoğurun. Soğanların arasına yoğurduğunuz kıymaları doldurup bir fırın kabına dizin. İkiye kestiğiniz biberler ve dörde böldüğünüz domatesleri de ilave edin. Nar ekşisi ve erittiğiniz 50 g Bizim Yağ’ı ve sıcak suyu küçük bir kasede karıştırıp soğanların üzerinde gezdirin. Önceden ısıtılmış 180 derece fırında 20 dakika pişirin. Sıcak servis yapın.", "50 g Bizim Yağ\n" + "1 kg sarı soğan\n" + "300 g kıyma\n" + "Tuz\n" + "Karabiber\n" + "1 tatlı kaşığı biber salçası\n" + "1 yemek kaşığı nar ekşisi\n" + "1 çay bardağı sıcak su\n" + "2 sivri biber\n" + "3 domates"));
        güneydogu.add(new Yemek("Ali Nazik","60 dk","4 kişilik",R.drawable.alinazik,"Patlıcanları yıkayın. Üzerlerini çatalla delip fırında ya da ocakta közleyin. Közlenen patlıcanların kabuklarını soyup ince doğrayın ve bir servis tabağına alın. Sarımsakları ezip süzme yoğurda ekleyin. Bizim Yağı bir sos tenceresinde eritin. Kıyma, salça ve ince doğradığınız biberleri ekleyin ve kıymanın rengi dönene kadar iyice kavurun. Tuz ve baharatlarla tatlandırın. Bir servis tabağına sırasıyla közleyip doğradığınız patlıcan, sarımsaklı yoğurt ve kıymalı harçtan koyup sıcak servis yapın.", "1 kg patlıcan\n" + "4 diş sarımsak\n" + "50 ml süzme yoğurt\n" + "30 g Bizim Yağ\n" + "900 g orta yağlı kıyma\n" + "1 tatlı kaşığı domates salçası\n" + "1 sivri biber\n" + "1 kırmızı kapya biberi\n" + "Tuz\n" + "Karabiber\n" + "Kırmızı pul biber"));
        güneydogu.add(new Yemek("Şiveydiz","65 dk","4 kişilik",R.drawable.sivesdeyiz,"Kuzu etini tencereye alın. Üzerini hafif geçecek kadar su ekleyin ve suyunu çekene kadar pişirin. Zeytinyağını ekleyip bir kaç dakika daha pişirin. Taze sarımsakları beyaz kısımlarını 3’er santimlik parçalar şeklinde kesin. Malzemelerin üzerini geçecek kadar sıcak suyla birlikte tencereye ilave edin. Yumuşayana kadar pişirin. Haşlanmış nohutları ekleyip 10 dakika daha pişirin. Bir kasede süzme yoğurt, un ve yumurta sarısını ekleyip çırpın. Yemeğin sıcak suyundan yavaş yavaş ilave ederek yoğurdu ılındırın. Karışımı azar azar tencereye ilave edip 5 dakika daha pişirin. Tuzla tatlandırın. Tereyağını eritip naneyi ekleyin. Yemeğin üzerine gezdirip servis yapın.","Yarım çay bardağı zeytinyağı\n" + "250 g kuzu kuşbaşı\n" + "500 g ayıklanmış taze sarımsak\n" + "1 su bardağı haşlanmış nohut\n" + "6 yemek kaşığı süzme yoğurt\n" + "1 yumurta sarısı\n" + "2 yemek kaşığı un\n" + "Tuz\n" + "Sıcak su"));
        güneydogu.add(new Yemek("Hünkar Beğendi","75 dk","6 kişilik",R.drawable.hunkar,"Bostan patlıcanların üzerini çatalla birkaç yerinden delin ve fırın ızgarasında yumuşayıncaya kadar közleyin. Hafif soğuyunca kabuklarını soyun ve bir kaseye alın. Bizim Yağ Margarini eritin. Unu ilave edip pembeleşinceye kadar kavurun. Sütü azar azar ekleyip karıştırın. Patlıcanı ilave edip karıştırın. Rendelenmiş kaşar peyniri, tuz ve karabiber ekleyip ocaktan alın. Ayrı bir tencerede yemeklik doğranmış soğan, kuşbaşı et, sarımsak ve defne yaprağını kalan Bizim Yağ Margarin ile kavurun. Salça ve suyu ekleyip etler yumuşayıncaya kadar pişirin. Tuz, karabiber ile tatlandırın. Beğendiyi servis tabağına alıp üzerine etleri yerleştirip servis yapın.", "50g BizimYağ Margarin\n" + "250 gkuşbaşı dana eti\n" + "1soğan\n"+ "1 su bardağı su\n" + "1defne yaprağı\n" + "Yarım yemek kaşığı salça\n" + "2 diş sarımsak\n" + "Tuz + Karabiber\n" + "\n" + "Beğendi için\n" + "\n" + "30g BizimYağ Margarin\n" + "2 bostan patlıcan\n" + "1yemek kaşığı un\n"+ "1 su bardağı süt\n" + "Yarım çay bardağı rendelenmiş kaşar peyniri\n" + "Tuz + Karabiber"));
        güneydogu.add(new Yemek("Antep Fıstıklı Zeytinyağlı Sarma","80 dk","6 kişilik",R.drawable.antepsarma,"Pirinci yıkayıp suyunu süzün. Soğanların kabuğunu soyup kıyın. Zeytinyağını tencereye alıp ısıtın ve soğanı kısık ateşte kavurun. Kıyılmış sarımsak, pirinç, domates ve biber salçasını ekleyip hafifçe kavurmaya devam edin. Antep fıstığı, tuz, karabiber ve limon suyu ekleyip karıştırın. Yarım su bardağı sıcak su ekleyip 5 dakika pişirin. Salamura yaprakların saplarını koparıp kaynayan suya ekleyin ve 5 dakika bekletip soğuk su dolu bir kabın içine alın. Yaprakları süzgece alıp suyunu süzün. Yaprakların içine hazırladığınız iç malzemeyi paylaştırıp sarın. Tencerenin tabanına artan yaprakları ve saplarını dizin. Üzerine sarmaları yerleştirin. Sarmaların üzerine yaprak ve porselen bir tabak kapatın. Üzerini geçecek kadar tuzlu su ekleyip su kaynayana kadar hızlı daha sonra kısık ateşte 30 dakika pişirin. Porselen tabağı alıp 15 dakika daha pişirin. Sarmaları piştikten sonra tencere içinde 10 dakika bekletip servis yapın.","750 gr salamura yaprak\n" + "1 su bardağı pirinç\n" + "1 yemek kaşığı biber salçası\n" + "1 yemek kaşığı domates salçası\n" + "1 su bardağı sızma zeytinyağı\n" + "2 soğan\n" + "1 baş sarımsak\n" + "Tuz\n" + "Karabiber\n" + "2 limonun suyu (koruk suyu veya sumak ekşisi de olabilir)\n" + "Soyulmuş Antep fıstığı"));
        güneydogu.add(new Yemek("Yuvalama","70 dk","6 kişilik",R.drawable.yuvalama,"Kuzu etini bol suyla yıkayıp tencereye alın. 6-7 bardak su ekleyip 45 dakika pişirin. Üzerinde biriken köpüğü bir kaşıkla alın. Nohudu ekleyip pişirmeye devam edin. Köftenin harcı için pirinç ve kıymayı bir kaba alın. Tuz ve karabiber ekleyip yoğurun. Nohuttan küçük köfteler hazırlayın. Hazırladığınız köfteleri bir süzgecin içine alın. Süzgeci tencerenin üzerine yerleştirip tencerenin kapağını kapatın ve 20-25 dakika buharda pişirin. Süzme yoğurdu bir kaseye alıp çorbanın suyundan birkaç kaşık ekleyip yoğurdun ılınmasını sağlayın. Yoğurdu tencereye azar azar ve sürekli karıştırarak ekleyin. Bir taşım pişirip köfteleri ekleyip karıştırın. Tuz ve karabiberle tatlandırın. Tereyağı ve sadeyağı tavaya alıp ısıtın. Naneyi ekleyip çorbanın üzerine gezdirin. Yanında pirinç pilavıyla birlikte servis yapın.","500 gr parça kuzu eti\n" + "1 su bardağı geceden ıslatılmış nohut\n" + "2 su bardağı pirinç (geceden ıslatılmış ve kurumaya bırakılmış)\n" + "250 gr yağsız dana kıyma (iki kere çekilmiş)\n" + "5 su bardağı süzme yoğurt\n" + "2 yemek kaşığı sadeyağ veya tereyağı\n" + "1 yemek kaşığı nane\n" + "Tuz\n" + "Karabiber"));
        güneydogu.add(new Yemek("Antep Usulü Etli Karışık Dolma","90 dk","8 kişilik",R.drawable.dolma,"Patlıcanları alacalı soyup tuzlu suda bekletin. Patlıcanların içini oyarak hazırlayın. Domateslerin üzerinden bir kapak kesip içini çıkarın. Biberlerin sap ve tohumlarını temizleyin. Soğan ve sarımsağın kabuğunu temizleyip kıyın. Pirinç, soğan, sarımsak, kıyma, pirinç, domates salçası, biber salçası, limon suyu, bir miktar su, tuz ve karabiberi bir kapta karıştırın. Sebzelerin içlerine paylaştırıp ağız kısımlarını kestiğiniz parçalarıyla kapatın. Tencereye patlıcan, biber ve domates sıralamasıyla dizin. Dolmaların üzerine bir porselen tabak kapatıp üzerini hafifçe geçecek kadar su ekleyin. Önce hızlı su kaynamaya başladığında kısık ateşte 45 dakika pişirin. Dolmaların üzerindeki porselen tabağı alıp 15 dakika daha pişirin. Dolmaları tencerede 5 dakika bekletip sonrasında servis yapın.","10 patlıcan\n" + "10 dolmalık biber\n" + "10 domates\n" + "1 baş sarımsak\n" + "2 soğan\n" + "500 gr yağlı kıyma\n" + "2 su bardağı pirinç\n" + "1 yemek kaşığı domates salçası\n" + "1 yemek kaşığı biber salçası\n" + "2 limonun suyu\n" + "Tuz\n" + "Karabiber"));
        güneydogu.add(new Yemek("Yoğurtlu Patates","70 dk","6 kişilik",R.drawable.patates,"Parça et, nohut ve bir miktar suyu tenceye alıp üzerini geçecek kadar su ekleyin. Pişme sırasında üzerinde biriken köpüğü alın. Nohut ve et yumuşayana kadar pişirin. Patatesleri iri parçalar şeklinde doğrayın. Kızgın yağda kızartın. Patatesleri pişen nohutlu ete ekleyin. Süzme yoğurt, yumurta, un ve zeytinyağını bir kasede iyice çırpın. Pişen yemeğin suyundan birkaç kaşık ekleyip karışımı ılındırın. Yemeğe azar azar ve karıştırarak ekleyin. Un kokusu gidene kadar pişirin. Tuzla tatlandırın. Tereyağını tavada eritip haspiri ekleyin. Yemeğin üzerine gezdirin. Sıcak servis yapın.","1 kg patates\n" + "1 su bardağı geceden ıslatılmış nohut\n" + "500 gr parça et\n" + "3 su bardağı süzme yoğurt\n" + "1 yumurta\n" + "1 yemek kaşığı un\n" + "3 yemek kaşığı zeytinyağı (yoğurt için)\n" + "2 yemek kaşığı sadeyağ veya tereyağı\n" + "1 yemek kaşığı haspir\n" + "Tuz"));
        güneydogu.add(new Yemek("Şam Böreği","65 dk","6 kişilik",R.drawable.sam,"Unu bir kaba eleyin. Mayayı ılık su ile eriyinceye kadar karıştırın. Unu, tuz ve mayalı su ile yoğurarak bir hamur hazırlayın. Üzerini bez ya da streç film ile kapatarak ılık bir ortamda 30 dakika kabarmaya bırakın. Soğanı ve maydanozu kıyın. Pirinci yıkayıp, kaynar tuzlu suda haşlayın ve suyunu süzün. Kıymayı suyla birlikte bir tavaya alın. Suyunu çekinceye kadar pişirin. Haşlanmış pirinci, kıymayı, soğanı, maydanozu, tuzu ve biberleri bir kapta karıştırarak harcı hazırlayın. Dinlenmiş olan hamuru ceviz büyüklüğünde 30 eşit parçaya bölüp, yuvarlayarak topak haline getirin. Herbirini unlanmış tezgahta merdane ile 10 cm çapında açın. Açtığınız hamurların ortalarına harcı paylaştırın. Yarım ay biçiminde kapatıp, uçlarını açılmamaları için bastırın. Az miktarda ayçiçeği yağını tavada ısıtın. Hazırladığınız börekleri tavaya yerleştirip, her iki yanı da altın sarısı renk alıncaya kadar kızartın. Sıcak servis yapın.","4 su bardağı un\n" + "1 su bardağı su\n" + "10 gr yaş maya\n" + "Tuz\n" + "1 soğan\n" + "1.5 çay kaşığı kırmızı pul biber\n" + "1 demet maydanoz\n" + "¾ su bardağı haşlanmış pirinç\n" + "250 gr yağsız kıyma\n" + "Yarım su bardağı su\n" + "Tuz\n" + "Karabiber\n" + "Kızartmak için ayçiçeği yağı"));

        karadeniz = new ArrayList<>();
        karadeniz.add(new Yemek("Simit Tiridi","45 dk","4 kişilik",R.drawable.simit,"Simitleri küçük parçalar şeklinde ufalayın. Et suyunu tencerede ısıtıp ekmekleri ekleyip yumuşatın. Kıymayı kendi yağında ve suyunda kavurun. Simit parçalarını servis tabaklarına paylaştırın. Üzerine kavrulmuş kıymayı ekleyin. Sarımsağı kıyıp yoğurtla karıştırın. Sarımsaklı yoğurdu üzerine ekleyin. Yağı kızdırıp üzerine gezdirin. Kıyılmış maydanoz serpip servis yapın.","5 susamsız simit\n" + "250 gr kıyma\n" + "Maydanoz\n" + "Sarımsak\n" + "Yoğurt\n" + "Et suyu\n" + "100 gr tereyağı"));
        karadeniz.add(new Yemek("Akçaabat Köftesi","90 dk","6 kişilik",R.drawable.akcabat,"Gerdan eti, döş eti, ekmek, gömlek yağı ve sarımsakları et kıyma makinesinden geçirin. Mümkünse mermer bir zemin üzerine alarak kıvam alana kadar yoğurun. Küçük yumurta büyüklüğünde parçalara ayırıp yassı yuvarlak şekil verin. Izgarada pişirip servis yapın.","1 kg döş kıyma (dana)\n" + "600 gr gerdan kıyma (dana)\n" + "400 gr bayat ekmek içi\n" + "6 iri diş sarımsak\n" + "300 gr gömlek yağı\n" + "2 yemek kaşığı tuz"));
        karadeniz.add(new Yemek("Pepeçura","70 dk","6 kişilik",R.drawable.pepecura,"Siyah üzümü iyice yıkayın. Suyla birlikte bir tencerede kaynatın. Toz şekeri ekleyip 5 dakika daha kaynatın. Süzgece alıp elinizle bastırarak suyunu süzün. Üzüm suyundan 1 su bardağı ayırıp nişastayla birlikte karıştırın. Pürüzsüz hale getirin. Kalan üzüm suyuna ekleyip sürekli karıştırarak pişirin. Küçük kaselere ya da kalıplara sıcak olarak paylaştırın. Buzdolabında iyice soğutup katılaşınca servis tabağına ters çevirin. Üzümlerle süsleyip servis yapın.","1 kg siyah üzüm\n" + "6 su bardağı su\n" + "1 su bardağı toz şeker\n" + "1 çay bardağı mısır nişastası"));
        karadeniz.add(new Yemek("Kuymak","60 dk","10 kişilik",R.drawable.kuymak,"Tereyağını bakır bir tavaya alıp kısık ateşte eritin. Mısır ununu ekleyip ateşi yükseltin ve 1 dakika kavurun. Suyu azar azar ekleyip ve karıştırarak kıvam alana kadar (tereyağı mısır ununun üzerine çıkana kadar) pişirin. Telli peyniri ilave edin. Peynir erimeye başlığında bekletmeden servis yapın.","350 gr mısır unu\n" + "350 gr tereyağı\n" + "350 gr telli peynir\n" + "30 gr tuz\n" + "2 litre su"));
        karadeniz.add(new Yemek("Çerkez Tavuğu","75 dk","6 kişilik",R.drawable.cerkez,"Tavuğu yıkadıktan sonra bir tencerede 4 su bardağı su ilavesiyle, iyice yumuşayana kadar haşlayın. Suyunu süzüp derisini çıkarın ve çok ufak parçalar halinde etini didikleyin. Bayat ekmek içi, ceviz ve sarmısakları bir mutfak robotundan geçirerek veya havanda ezerek püre haline getirin. Üzerine 1 su bardağı ılık tavuk suyu, tuz, toz kişniş ekleyip karıştırın. Tavuk etini ekleyip malzeme özleşene kadar karıştırın (karışımın kıvamı çok katı olursa biraz tavuk suyu ekleyebilirsiniz). Servis tabağına alın. Tereyağını tavada kızdırıp kırmızı pul biberi ekleyin. Hızlıca yemeğin üzerine gezdirip ılık olarak servis yapın.","1 adet bütün tavuk\n" + "2 dilim bayat ekmek içi\n" + "3 diş sarmısak\n" + "1.5 su bardağı ceviz içi\n" + "1 çay kaşığı tuz\n" + "Karabiber\n" + "Toz kişniş\n" + "Sos için"));
        karadeniz.add(new Yemek("Dible Fasulyeli Pilav","45 dk","6 kişilik",R.drawable.fasulyelipilav,"Taze fasulyeleri küçük parçalar şeklinde doğrayın. Soğanın akabuğunu soyup piyazlık doğrayın. Fasulyelerin yarısını tencereye alın. Üzerine soğan, pirinç, rendelenmiş domates, tuz ve pul biber ekleyin. Kalan fasulyeleri ilave edin. Su ve tereyağını ekleyip kısık ateşte kapağı kapalı olarak kendi buharında pişirin. Yemeği servis tabağına alın. Üzerine tavada ısıtılmış fındık yağını gezdirip servis yapın.","1 kg taze fasulye\n" + "1 su bardağıpirinç\n" + "3 orta boy soğan\n" + "1 çay bardağı su\n" + "1 küçük domates\n" + "1 yemek kaşığı tereyağı\n" + "Tuz\n" + "Kırmızı pul biber\n" + "Fındık yağı"));
        karadeniz.add(new Yemek("Karalahana Çorbası","55 dk","6 kişilik",R.drawable.karalahana,"Karalahanayı ince doğrayın. Üzerine tuz serpip biraz ovun ve acısının çıkmasını sağlayın. Tereyağı ile zeytinyağını tencerede ısıtın. Üzerine yemeklik doğradığınız soğanlar ekleyip soteleyin. Soğan yumuşayınca karalahanayı ilave edin. 4 su bardağı su ekleyip kaynamaya bırakın. Karalahana yumuşayınca kırmızıbiber, barbunya ve mısırı ekleyin. Yaklaşık 7-8 dakika kaynattıktan sonra tuz ve karabiber ile tatlandırın. Sıcak servis yapın.","1 demet karalahana\n" + "200 gr haşlanmış barbunya\n" + "2 soğan\n" + "4 su bardağı su\n" + "1 su bardağı tane mısır\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı zeytinyağı\n" + "1~2 acı kuru kırmızıbiber\n" + "Tuz\n" + "Karabiber"));
        karadeniz.add(new Yemek("Pumpum Çorbası","60 dk","8 kişilik",R.drawable.pumpum,"Tencereye 5 su bardağı ılık su veya et suyunu, mısır ununu ekleyip karıştırın. Kaynayana kadar karıştırın. Kavurmayı tavada 2-3 dakika kavurun. Kaynayıp koyulaşan çorbanın üzerine ekleyip karıştırın. Tuzla tatlandırın. Yaklaşık 4-5 dakika pişirin. Tereyağı ve pul biberi sos tenceresinde kızdırın. Hazırladığınız çorbanın üzerine gezdirip sıcak servis yapın.","1 su bardağı mısır unu\n" + "5 su bardağı su veya et suyu\n" + "2 dilim kavurma\n" + "Tuz\n"+"2 tatlı kaşığı tereyağı\n" + "1 tatlı kaşığı kırmızı pul biber"));
        karadeniz.add(new Yemek("Topik","30 dk","11 kişilik",R.drawable.topik,"","Malzemeler\n" + "3 su bardağı nohut\n" + "5 patates\n" + "1 tatlı kaşığı tuz\n" + "1 tatlı kaşığı tozşeker\n" + "1 tatlı kaşığı tarçın\n" + "1 çay bardağı tahin\n" + "\n" + "İç malzeme için\n" + "3 kg soğan\n" + "1 tatlı kaşığı tuz\n" + "50 gr dolmalık üzüm\n" + "50 gr çamfıstığı\n" + "4 tatlı kaşığı tarçın\n" + "2 tatlı kaşığı yenibahar\n" + "2 tatlı kaşığı karabiber\n" + "2 tatlı kaşığı tozşeker\n" + "500 gr tahin"));
        karadeniz.add(new Yemek("Fasulye Pilaki","60 dk","4 kişilik",R.drawable.fasulyepilaki,"Kuru fasulyeleri bir gün önceden ıslatın. Havuçları yeşilliklerinden ayırıp yıkayın ve zar şeklinde doğırayın. Sarımsakları ve soğanı ayıklayıp küp şeklinde doğrayın. Domatesleri yıkayıp rendeleyin. Sivribiberleri ince ince doğrayın. Patates, kereviz ve yapraklarını temizleyip yıkayın ve zar şeklinde doğrayın. Maydanozu yıkayıp kıyın.\n" + "\n" + "Fasulyeleri iyice yıkayıp bir tencereye alın. Domates, biber, sarımsak, soğan, havuç, karabiber, zeytinyağını ve yeterince sıcak suyu fasulyeye ekleyip pişirmeye başlayın. Fasulye ve havuçlar yarı yarıya piştiğinde patates, kereviz, yaprakları ve maydanozu ilave edin. Son olarak tuz ve tozşeker serpin. Tüm malzemeler pişince ocaktan alın. Sıcak ya da soğuk servis yapın.","2 su bardağı kuru fasulye\n" + "1 demet kum havucu\n" + "7~8 diş sarımsak\n" + "1 soğan\n" + "2 domates\n" + "3~4 sivri biber\n" + "1 çay kaşığı kırmızıbiber\n" + "1 kahve fincanı zeytinyağı\n" + "2 patates\n" + "1 kereviz ve yaprakları\n" + "1 demet maydanoz\n" + "1 tatlı kaşığı tozşeker\n" + "Tuz\n" + "Karabiber"));

        icanadolu = new ArrayList<>();
        icanadolu.add(new Yemek("Gazete Baklavası","90 dk","6 kişilik",R.drawable.gazetebaklava,"Baklava hamuru için un, yumurta, kabartma tozu, yoğurt, soda ve eritilmiş Bizim Yağ, sirke ve limon suyunu karıştırıp iyice yoğurun. Hamuru 28 bezeye ayırıp unlanmış tezgaha alın. Baklavanın şerbeti için şeker, su ve limonu geniş bir tencereye alarak kaynatın. Kaynadıktan sonra soğuması içi kenara alın. Dinlenen hamurları aralarına nişasta serperek incecik açın. Açtığınız yufkaları oklavaya sarıp büzün. Büyükçe bir kağıdın üzerine açarak oklavadan ayırın. Diğer bezeleri de aynı şekilde açıp bir kağıdın üzerine yerleştirerek dinlendirin. Dinlenen yufkanın üzerine ceviz serpin. Kağıdı iki ucundan tutarak yufkayı sarın ve daha sonra dilimleyin. Yağlı kağıt serili fırın tepsisine yerleştirin. Bizim Yağı eritin. Üzerindeki köpüğü alıp tepsideki baklavaların üzerine dökün. Önceden ısıtılmış 180 derece fırında üzeri kızarıncaya kadar pişirin. Soğuyan şerbeti sıcak baklavanın üzerine döküp Antep fıstığı ile süsleyerek servis yapın. \n" + "\n","Hamuru için\n" + "4 su bardağı un\n" + "2 yumurta\n" + "1 paket kabartma tozu\n" + "1 çay bardağı yoğurt\n" + "1 çay bardağı soda\n" + "1 çay bardağı eritilmiş Bizim Yağ\n" + "1 tatlı kaşığı sirke\n" + "1/4 limonun suyu\n" +  "\n" + "İçi için\n" + "1 su bardağı ince çekilmiş ceviz\n" + "\n" + "Şerbeti için\n" + "4 su bardağı şeker\n" + "4 bardak su\n" + "1/2 limon\n" +  "\n" + "Açmak için\n" + "Nişasta\n" +  "\n" + "Üzeri için\n" + "150 g Bizim Yağ\n" + "1 çay bardağı Antep fıstığı"));
        icanadolu.add(new Yemek("Yağ Mantısı","100 dk","6 kişilik",R.drawable.yagmantisi,"Hamuru hazırlamak için unu geniş bir kaba alın. Ortasını havuz gibi açıp yoğurt, yumurta, maya ve tuzu ekleyip yoğurun. Azar azar suyu ilave edip yoğurmaya devam edin. Hamurun üzerini nemli bir bezle örtüp 40 dakika dinlendirin. İç harcını hazırlamak için kıymayı geniş bir kaba alın. Üzerine rendelenmiş soğan, tuz ve karabiber ekleyip karıştırın. Sosu için Bizim Yağı bir sos tenceresinde eritin. Ezdiğiniz sarımsaklar, salça ve rendelediğiniz domatesi ekleyin. Tuz ve karabiberle tatlandırıp pişirin. Dinlenen hamuru unlanmış tezgah üzerinde açıp klasik mantı hamurundan daha büyük olacak kareler kesin. Ortalarına kıymalı harçtan yerleştirin. Uçlarını karşılıklı köşelerden birleştirerek kapatın. Bütün kareler için aynı işlemi tekrarladıktan sonra mantıları bol kızgın yağda kızartın. Kızaran mantıları servis tabağına alıp üzerine yoğurt ve domates sosundan gezdirip nane ile süsleyerek servis yapın.","2 su bardağı un\n" + "2 yemek kaşığı yoğurt\n" + "1 yumurta\n" + "1 tatlı kaşığı kuru maya\n" + "1 tatlı kaşığı tuz\n" + "2 su bardağı su\n" + "İç harcı için\n" + "150 g kıyma\n" + "1 soğan\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Sosu için\n" + "60 g Bizim Yağ\n" + "2 diş sarımsak\n" + "1 tatlı kaşığı biber salçası\n" + "2 domates\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Kızartmak için\n" + "Bizim Ayçiçek Yağı\n" + "\n" + "Üzeri için\n" + "Yoğurt"));
        icanadolu.add(new Yemek("Yağlama","70 dk","4 kişilik",R.drawable.yaglama,"Hamuru için malzemeleri bir kaba alarak yoğurun. Üzerini nemli bir bezle örtüp 20 dakika dinlendirin. Mayalanan hamuru küçük bezelere ayırın. Merdane yardımıyla 15 cm çapında açın. Tavayı Bizim Yağ Margarin ile yağlayıp hamurun iki yüzünü de pişirin. İç harcı için Bizim Yağ Margarini bir tencerede eritin. Kıymayı ekleyip kavurun. Yemeklik doğradığınız soğan, küp doğradığınız domates ve Bizim Ayçiçek Yağını ekleyerek pişirmeye devam edin. Yarım çay bardağı su ekleyip bir süre daha pişirin. Tuz ve karabiberle tatlandırın. Kıymalı harcı yağlamaların arasına sırasıyla koyup üzerine sarımsaklı yoğurt gezdirerek servis yapın.","Bazlama hamuru için\n" + "4 subardağı un + Bir tutam tuz\n" + "Yarımpaket yaş maya + 1 çay bardağı su\n" +"\n" + "Harcı için\n" + "Yarımçay bardağı BizimAyçiçek Yağı\n" + "30g BizimYağ Margarin\n" + "300 gkıyma + 2 soğan\n" + "3domates + Tuz + Karabiber\n" + "Biryemek kaşığı salça\n" + "Yarımçay bardağı su"));
        icanadolu.add(new Yemek("Sülbiye","80 dk","4 kişilik",R.drawable.sulbiye,"Tereyağını tencerede eritin. Etleri ekleyin ve etler suyunu bırakıp çekene kadar kavurun. Kabuğu soyulmuş arpacık soğanları ve sarımsakları bütün olarak ekleyip soğanlar şeffaflaşana kadar arada bir karıştırarak kavurmaya devam edin. Salçayı ekleyin ve 1-2 dakika daha kavurun. Tuz, baharat ve haşlanmış nohutları ekleyin. Etlerin ve diğer malzemelerin üstünü hafifçe aşacak kadar sıcak su ekleyin. Tenceredeki tüm malzemeler yumuşayıncaya kadar kısık ateşte pişirin. Üzerine taze çekilmiş karabiber serpip servis yapın.","350 gr parça dana eti\n" + "350 gr arpacık soğanı\n" + "8~10 diş sarımsak\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı domates salçası\n" + "1.5 su bardağı haşlanmış nohut\n" + "1 tatlı kaşığı kimyon\n" + "Tuz\n" + "Karabiber\n" + "Sıcak su"));
        icanadolu.add(new Yemek("Pekmezli Pelte","65 dk","6 kişilik",R.drawable.pekmezlipelte,"1 Su bardağı üzüm pekmezi, 2 su bardağı su ve 4.5 yemek kaşığı buğday nişastasını çukur bir kaba alıp iyice karıştırın. Kısık ateşte koyulaşıp muhallebi kıvamına gelene kadar pişirin. Hazırladığınız karışımı büyük bir tepsiye doldurun. Pelte soğuyana kadar bekletin. Üzerini cevizle süsleyip, servis yapın.","1 su bardağı üzüm pekmezi\n" + "2 su bardağı su\n" + "4.5 yemek kaşığı buğday nişastası\n" +"\n" + "Üzeri için\n" + "Ceviz içi"));
        icanadolu.add(new Yemek("Ankara Tava","45 dk","6 kişilik",R.drawable.ankaratava,"Orta büyüklükte parçalar şeklinde doğranmış eti tencereye alıp biraz yağ ilavesiyle soteleyin. İnce doğranmış soğanı ekleyip sotelemeye devam edin. Etin büyüklüğünde kesilmiş biberleri ekleyip sotelemeye devam edin. Yine yanı büyüklükte kesilmiş domatesi ilave edip pişirmeye devam edin. Domates salçası ve tuzu ekleyip malzeme yumuşayana kadar pişirin. Tuzla tatlandırın. Arpa şehriyeyi ayçiçeği yağında kavurun. Üzerini geçecek kadar sıcak su ekleyip yumuşayana kadar kısık ateşte pişirin. Tuzla tatlandırın. Arpa şehriyeyi servis tabağına alın. Üzerine eti ekleyip servis yapın.","350 gr parça et\n" + "1 soğan\n" + "2 orta boy domates\n" + "2 sivri biber\n" + "2 salçalık kırmızıbiber\n" + "1 yemek kaşığı domates salçası\n" + "Ayçiçeği yağı\n" + "1 kase arpa şehriye\n" + "Sıcak su\n" + "Tuz"));
        icanadolu.add(new Yemek("Çibörek","60 dk","6 kişilik",R.drawable.ciborek,"Un, tuz ve suyu bir kapta karıştırıp yumuşak bir hamur hazırlayın. Soğanın kabuğunu soyup rendeleyin. Kıyma, tuz, karabiber ve su ekleyip karıştırın. Hamuru ceviz büyüklüğünde bezelere ayırın. Yaklaşık 20 cm çapında açın. Hamurun yarısına kıymayı harcı ince bir tabaka halinde olacak şekilde yayın. Diğer tarafını üzerine kapatıp kenarlarına parmak uçlarınızla bastırın. Kızgın ayçiçeği yağında her iki yüzlerini kızartın. Sıcak servis yapın.","4 su bardağı un\n" + "1 tatlı kaşığı tuz\n" + "Su\n" + "1 soğan\n" + "250 kg kıyma\n" + "1 çay kaşığı tuz\n" + "1 çay kaşığından biraz az karabiber\n" + "Yarım çay bardağı su\n" + "Kızartmak için ayçiçeği yağı"));
        icanadolu.add(new Yemek("Bamya Çorbası","50 dk","6 kişilik",R.drawable.bamyacorba,"Kuru bamyaları avucunuzda ovalayarak küçük tüylerinden arındırın. Kaynar suya ekleyip yumuşayana kadar haşlayın. Soğanın kabuğunu soyup kıyın. Ayçiçeği yağını tencerede ısıtıp soğanı kısık ateşte kavurun. Salça, et ve et suyunu ilave edin. Su kaynadığında bamyaları ekleyin. Tuzla tatlandırın. Limon tuzunu ilave edip 10 dakika daha pişirin. Bekletmeden servis yapın.","50 gr kuru bamya (100 gramlık paketlerde satılır)\n" + "200 gr küçük doğranmış et\n" + "3 su bardağı et suyu\n" + "1 soğan\n" + "Ayçiçeği yağı\n" + "1 yemek kaşığı domates salçası\n" + "2 parça limon tuzu\n" + "Tuz"));
        icanadolu.add(new Yemek("Madımak","70 dk","6 kişilik",R.drawable.madimak,"Madımakları ayıklayın ve yıkayın. Ayçiçeği yağını tencerede ısıtın. Piyazlık doğranmış soğanı ekleyip kısık ateşte kavurun. İnce doğranmış biberleri ekleyip kavurmaya devam edin. Domatesi de küçük doğrayıp ekleyin. Madımakların suyunu süzüp ekleyin. Yemeğin pişmesine az kala ince bulguru ekleyip karıştırın. Tuzla tatlandırın. Ilık servis yapın.","500 gr madımak\n" + "2 soğan\n" + "3 yemek kaşığı ayçiçeği yağı\n" + "1 domates\n" + "4~5 sivri biber\n" + "1 çay bardağı ince bulgur\n" + "Tuz"));
        icanadolu.add(new Yemek("Kokina Çorbası","45 dk","4 kişilik",R.drawable.kokina,"Kuzu etini tencereye alın. Üzerine 4 su bardağı su ilave edip haşlayın. Ayrı bir tencerede tereyağı ile ayçiçeği yağını ısıtın. Üzerine yemeklik doğradığınız soğan ve sarımsağı ilave edip soteleyin. Haşladığınız eti ilave edip karıştırın. İnce kıydığınız lahana ve domates salçasını da ekleyip karıştırın. Bulgur, et suyu, tuz ve karabiberi ilave edip kaynamaya bırakın. Orta ateşte 15 dakika pişirip sıcak servis yapın.","200 gr lahana turşusu\n" + "1 diş sarımsak\n" + "1 soğan\n" + "400 gr parça kuzu kuşbaşı eti\n" + "2/3 çay bardağı pilavlık bulgur\n" + "2 yemek kaşığı domates salçası\n" + "1 yemek kaşığı tereyağı\n" + "1 yemek kaşığı ayçiçeği yağı\n" + "4~5 su bardağı su veya et suyu\n" + "Tuz\n" + "Karabiber"));

        doguanadolu = new ArrayList<>();
        doguanadolu.add(new Yemek("Erzincan Lokumu","90 dk","6 kişilik",R.drawable.erzincanlokum,"Derin bir kapta yumurta, Bizim Yağ Margarin, Bizim Ayçiçek Yağı ve şekeri karıştırın. Üzerine un ve kabartma tozunu ilave edin. Kurabiye hamurundan biraz daha yumuşak bir hamur elde edene kadar yoğurun. Hazırladığınız hamuru yuvarlak bir fırın kabına elinizle yayın. Üzerini düzeltip 180 derece fırında hafif pembeleşinceye kadar pişirin. Soğuduktan sonra baklava şeklinde dilimleyin. Üzerine pudra şekeri serperek servis yapın.","125g BizimYağ Margarin\n" + "1su bardağı BizimAyçiçek Yağı\n" + "1 subardağı şeker + 1 yumurta\n" + "1paket kabartma tozu\n" + "3~4 subardağı un"));
        doguanadolu.add(new Yemek("Kaburga Dolması","70 dk","6 kişilik",R.drawable.kaburgadolma,"Pirinci bol suyla yıkayıp suyunu süzün. Kaburganın yağlı kısmından cep şeklinde kesin. Tereyağını tencereye alıp eritin. Badem ve kıymayı ekleyip kavurun. Kıyılmış soğanı ekleyip kavurmaya devam edin. Tencereye alıp birkaç dakika kavurun. Kıyılmış maydanoz, baharat ve tuz ekleyip karıştırın. Sıcak su ekleyip kısık ateşte pirinçler hafifçe yumuşayana kadar pişirin. Hazırladığınız pilavı kaburgaya açtığınız cebe doldurun. Etin ağız kısmını iplikle dikin. Kaburganın her yerine salça sürüp yağda kızartın. Sıcak fırına alıp 2 saat boyunca pişirin. Sıcak servis yapın.","2.5 kg kaburga (koyun eti~sağ göğüs kısmı)\n" + "250 gr tereyağı\n" + "150 gr kabuğu soyulmuş badem içi\n" + "300 gr kıyma\n" + "1 soğan\n" + "750 gr pirinç\n" + "2 yemek kaşığı domates salçası\n" + "1 demet maydanoz\n" + "2 su bardağı sıcak su\n" + "Tuz\n" + "Kırmızı toz biber\n" + "Karabiber"));
        doguanadolu.add(new Yemek("Ev Helvası","45 dk","6 kişilik",R.drawable.evhelvasi,"Su ve şekeri tencereye alıp kaynatın. Şerbet kıvımına geldiğinde tencereyi ocaktan alın. Tereyağını başka tencereye alıp eritin. Hafif fokurdamaya başladığında unu azar azar ekleyip kavurun. Unun rengi değiştiğinde şerbeti azar azar ve sürekli karıştırmaya devam ederek ilave edin. Un şerbeti tamamen çekene kadar pişirin. Helva hafif ılındığında kaşıkla şekil vererek servis tabağına alın. Üzerine ufalanmış ceviz içi serpip servis yapın.","1 kg un\n" + "250 gr tereyağı\n" + "1 litre su\n" + "1 kg toz şeker\n" + "Ufalanmış ceviz içi"));
        doguanadolu.add(new Yemek("Pancar Kavurma","50 dk","6 kişilik",R.drawable.pancarkavurma,"Pancar otlarını temizleyip iri parçalar şeklinde doğrayın. Haşlayıp suyunu süzün. Soğanların kabuğunu soyup kıyın. Biberlerin çekirdeklerini temizleyip ince doğrayın. Tereyağını tencerede eritip soğanı kısık ateşte kavurun. Biberleri ekleyip kavurmaya devam edin. Pancar otunu ilave edip birkaç dakika daha kavurun. Tuz ve karabiberle tatlandırın. Servis yapın.","1 kg pancar otu\n" + "2 soğan\n" + "1 kırmızı sivri biber\n" + "1 sivri biber\n" + "3 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı tuz\n" + "Karabiber"));
        doguanadolu.add(new Yemek("Küt Böreği","80 dk","6 kişilik",R.drawable.kutboregi,"Unu eleyip çukur bir kaba alın. Ortasını havuz şeklinde açıp kabartma tozu, ayçiçeği yağı, yoğurt, tuz ve yumurtayı ekleyip yoğurun (gerekirse ayçiçeği yağı ilavesi yapabilirsiniz). Hamuru 20 eşit bezeye ayırın. Bezeleri pasta tabağı büyüklüğünde açıp aralarına oda ısısında yumuşatılmış sade yağ sürerek üst üste dizin. Bezelerin hepsini oklavayla yuvarlak bir tepsi büyüklüğünde açın. Üzerine tekrar sade yağ sürüp rulo şekline sarın. Ruloyu üç parçaya kesip buzdolabında 1 saat bekletin. Ruloların kesik kısımlarından bastırıp hamurlara yassı şekil verin. Tepsi büyüklüğünde açıp aralarına sade yağ sürerek tepsiye dizin. Üstteki yufkanın üzerine sade yağ sürüp önceden ısıtılmış 180 derece fırında kızarana kadar pişirin. Küçük dikdörtgen parçalar şeklinde dilimleyin. Üzerine pudra şekeri serpip servis yapın.","1 paket kabartma tozu\n" + "1 çay bardağı ayçiçeği yağı\n" + "1 çay bardağı yoğurt\n" + "2 yumurta\n" + "4.5 su bardağı un\n" + "200 gr sade yağ\n" + "Tuz"));
        doguanadolu.add(new Yemek("Mantar Yemeği","60 dk","6 kişilik",R.drawable.mantaryemegi,"Mantarları bol suyla yıkayıp küçük doğrayın. Soğanın kabuğunu soyup kıyın. Havuç ve biberleri temizleyip küçük parçalar şeklinde doğrayın. Tereyağını tencerede eritip havuç, biber ve soğanı kavurun. Mantarı ekleyip kavurmaya devam edin. Domates salçası, baharat, tuz ve çok az sıcak su ekleyip sebzeler yumuşayana kadar pişirin. Sıcak servis yapın.","1 kg mantar\n" + "Tereyağı\n" + "1 soğan\n" + "1 havuç\n" + "2 salçalık kırmızıbiber\n" + "Domates salçası\n" + "Sıcak su\n" + "Kırmızı pul biber\n" + "Karabiber\n" + "Tuz"));
        doguanadolu.add(new Yemek("Aşotu Çorbası","45 dk","6 kişilik",R.drawable.asotucorba,"Buğdayı 4 su bardağı su ile yumuşayana kadar haşlayın. Yoğurt, yumurta sarısı ve unu derin bir kapta karıştırın. Buğdayı haşladığınız sudan 1 kepçe kadar alıp yoğurtlu karışıma ekleyerek karıştırın. Kaynamakta olan buğdaya ilave edip hızlıca karıştırın. Tavaya tereyağını ekleyip eritin. Üzerine yemeklik doğradığınız soğanı ilave edip soteleyin. Soğan yumuşayınca çorbaya ekleyip karıştırın. Kıyma, tuz ve karabiberi iyice yoğurun. Misketten daha küçük köfteler hazırlayın. Kaynayan çorbaya ilave edin. Kişniş, tuz ve karabiberi ilave edip köfteler yumuşayana kadar pişirin. Sıcak servis yapın.","1 su bardağı buğday\n" + "1 soğan\n" + "1.5 yemek kaşığı tereyağı\n" + "1 tatlı kaşığı aşotu (kişniş)\n" + "4 su bardağı yoğurt\n" + "1 yemek kaşığı un\n" + "1 yumurta sarısı\n" + "\n" + "Köfte için\n" + "250 gr kıyma\n" + "Tuz\n" + "Karabiber"));
        doguanadolu.add(new Yemek("Ciğer Taplemesi","100 dk","8 kişilik",R.drawable.cigertapleme,"Koyun ciğerini ince kıyın. Soğan ve biberi de ince kıyın. (ya da her birini kıyma makinesinden geçirin) Kıymayı, reyhanı, tuz ve karabiberi ilave edin. Bulguru ekleyip iyice yoğurun. Yoğurma işlemi sırasında suyu az az köfte hamuruna ilave edin. Yoğurma işlemi tamamlandıktan sonra avuç içerisinden ceviz büyüklüğünde yuvarlak köfteler hazırlayın. Elinizle yassılaştırarak 1 cm kalınlığında köfteler yapın. Bir tencereye bol su doldurup tuz ilave ederek kaynatın. Köfteleri kaynar suda ara ara karıştırarak haşlayın. Tencerenin kapağını kapatmayın. Pişme işlemi tamamlanınca büyük bir süzgeçle suyunu süzerek servis tabağına alın. Zeytinyağını (veya tereyağını) küçük bir tavada eritin. Kırmızı pul biberi ekleyip kızdırın. Köftelerin üzerine gezdirip, kıyılmış maydanoz ile sıcak servis yapın.","1 kg. ciğer\n" + "400 gr kıyma\n" + "2 soğan\n" + "1 yeşil biber\n" + "1 su bardağı kuru reyhan\n" + "5 + 1/4 su bardağı köftelik bulgur\n" + "1.5 su bardağı su\n" + "Tuz\n" + "Karabiber\n" + "Yarım demet maydanoz\n" + "Tuz\n" + "Karabiber\n" + "\n" + "Servis için\n" + "1 çay bardağı zeytinyağı\n" + "Kırmızı pul biber"));
        doguanadolu.add(new Yemek("Piti Kebabı","80 dk","8 kişilik",R.drawable.pitikebabi,"Nohutları akşamdan ıslatın. Suyunu değiştirip iyice haşlayın ve süzün. Nohutların kabuklarını soyup bir kâseye alın.\n" + "\n" + "Kuşbaşı etleri tuz ve karabiberle tatlandırıp bir tencereye alın. Az su ilave ederek iyice pişirin. Suyu azalırsa bir miktar daha su ekleyin.\n" + "\n" + "Yufkaları sac üzerinde kızartıp küçük parçalara ayırın ve bir tepsiye yayın. Üzerine kalan et suyunu gezdirin. Et ve nohudu harmanlayıp yufkaların üzerine yayın. Servis tabaklarına paylaştırıp servis yapın.","500 gr kuşbaşı koyun eti\n"+"1 su bardağı nohut\n"+"4 yufka\n"+"Tuz\n" + "Karabiber"));
        doguanadolu.add(new Yemek("Kurze","45 dk","6 kişilik",R.drawable.kurze,"Soğanları temizleyip küp şeklinde doğrayın. Kıyma ve soğanı bir tavada sürekli karıştırarak kavurun. Tuz, 1 fincan sirke ve yarım limonun suyunu ilave edip tavayı ocaktan alın. \n" + "\n" + "Hamur için; unu bir kaba alın. Tuz serpip harmanlayın. Ortasını havuz gibi açıp yumurta ve suyu ekleyin. Unu kenarlardan ortaya toplayarak bir hamur yoğurun. Hamuru küçük bezelere ayırın. Hazırladığınız iç malzemeden ortasına yayın. Kenar uçlarını kapatarak rulo şeklinde sarın. \n" + "\n" + "Derin bir tencerede hafif tuzlu su kaynatın. Hamurları kaynar suda haşlayıp kevgirle süzgece alın. Mantıları servis tabaklarına paylaştırın. \n" + "\n" + "Salçayı suyla ezin. Tavaya alıp 1-2 dakika pişirin. Salçalı sosu kurzelerin (mantı) üzerine gezdirip servis yapın.","500 gr yağlı koyun kıyması\n"+"2 soğan\n"+"1 kahve fincanı sirke\n"+"Yarım limonun suyu\n"+"3 çorba kaşığı domates salçası\n"+"Tuz\n"+"\n"+"Hamur malzemesi:\n"+" 2 su bardağı un\n"+"1 yumurta\n"+"Yarım su bardağı su"));

        final ListAdapter adapter_marmara = new ListAdapter(this,marmara);
        final ListAdapter adapter_akdeniz = new ListAdapter(this,akdeniz);
        final ListAdapter adapter_ege = new ListAdapter(this,ege);
        final ListAdapter adapter_güneydogu = new ListAdapter(this,güneydogu);
        final ListAdapter adapter_karadeniz = new ListAdapter(this,karadeniz);
        final ListAdapter adapter_icanadolu = new ListAdapter(this,icanadolu);
        final ListAdapter adapter_doguanadolu = new ListAdapter(this,doguanadolu);


        Spinner spinner = (Spinner) findViewById(R.id.spinner);

        final ArrayAdapter<String> adapterspinner = new ArrayAdapter<String>(this,
                android.R.layout.simple_list_item_checked, android.R.id.text1,
                yemek_türkiye);
        spinner.setAdapter(adapterspinner);
        textView=(TextView) findViewById(R.id.textView);
        spinner.setOnItemSelectedListener(new OnItemSelectedListener() {


            @Override
            public void onItemSelected(AdapterView<?> parent, View view,int pos, long id) {


                if (pos > 0) {
                    textView.setText(yemek_türkiye[pos]);

                }
                else if(pos==0){
                    textView.setText(yemek_türkiye[0]);
                }


                if(textView.getText()=="Lütfen yemek yöresi seçiniz!"){
                    liste.setAdapter(null);
                    layout.setBackgroundResource(R.drawable.kasik);
                }
                else if(textView.getText()=="Marmara Yöresi Yemekler"){
                    liste.setAdapter(adapter_marmara);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else if(textView.getText()=="Akdeniz Yöresi Yemekler"){
                    liste.setAdapter(adapter_akdeniz);
                    layout.setBackgroundResource(R.drawable.yemek);
                }
                else if(textView.getText()=="Ege Yöresi Yemekler"){
                    liste.setAdapter(adapter_ege);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else if(textView.getText()=="Güneydoğu Yöresi Yemekler"){
                    liste.setAdapter(adapter_güneydogu);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else if(textView.getText()=="Karadeniz Yöresi Yemekler"){
                     liste.setAdapter(adapter_karadeniz);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else if(textView.getText()=="İç Anadolu Yöresi Yemekler"){
                    liste.setAdapter(adapter_icanadolu);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else if(textView.getText()=="Doğu Anadolu Yöresi Yemekler"){
                    liste.setAdapter(adapter_doguanadolu);
                    layout.setBackgroundResource(R.drawable.yemek);

                }
                else{

                }

            }



            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });

        liste.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position,
                                    long id) {
                Intent intent = new Intent(yemek_turkiye.this, Yemek_Bilgi.class);

                if(textView.getText()=="Marmara Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_marmara.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }

                }
                else if(textView.getText()=="Akdeniz Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_akdeniz.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }
                else if(textView.getText()=="Ege Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_ege.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }
                else if(textView.getText()=="Güneydoğu Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_güneydogu.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }
                else if(textView.getText()=="Karadeniz Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_karadeniz.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }
                else if(textView.getText()=="İç Anadolu Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_icanadolu.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }
                else if(textView.getText()=="Doğu Anadolu Yöresi Yemekler"){
                    if(position<10){
                        Yemek item = (Yemek) adapter_doguanadolu.getItem(position);
                        String[] yemek_bilgi=new String[5];
                        yemek_bilgi[0]=item.getYemek_adi();
                        yemek_bilgi[1]=item.getYapilisi();
                        yemek_bilgi[2]=item.getMalzemeler();
                        int img=item.getYemek_img();
                        intent.putExtra("yemek_bilgi",yemek_bilgi);
                        intent.putExtra("yemek_img",img);
                        startActivity(intent);
                    }
                }


            }
        });

    }
}
